/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.24
 * Generated at: 2020-10-06 23:44:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.status;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class statusMiddleView_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(6);
    _jspx_dependants.put("jar:file:/C:/dev/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp15/wtpwebapps/corona/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/C:/dev/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp15/wtpwebapps/corona/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/include/include-body.jspf", Long.valueOf(1595128796000L));
    _jspx_dependants.put("jar:file:/C:/dev/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp15/wtpwebapps/corona/WEB-INF/lib/jstl-1.2.jar!/META-INF/fn.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1595463255549L));
    _jspx_dependants.put("/WEB-INF/include/include-header.jspf", Long.valueOf(1599786548129L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Fontfaces CSS-->\r\n");
      out.write("<link href=\"/corona/bootstrap/css/font-face.css\" rel=\"stylesheet\" media=\"all\">\r\n");
      out.write("<link href=\"/corona/bootstrap/vendor/font-awesome-4.7/css/font-awesome.min.css\" rel=\"stylesheet\" media=\"all\">\r\n");
      out.write("<link href=\"/corona/bootstrap/vendor/font-awesome-5/css/fontawesome-all.min.css\" rel=\"stylesheet\" media=\"all\">\r\n");
      out.write("<link href=\"/corona/bootstrap/vendor/mdi-font/css/material-design-iconic-font.min.css\" rel=\"stylesheet\" media=\"all\">\r\n");
      out.write("\r\n");
      out.write("<!-- Bootstrap CSS-->\r\n");
      out.write("<link href=\"/corona/bootstrap/vendor/bootstrap-4.1/bootstrap.min.css\" rel=\"stylesheet\" media=\"all\">\r\n");
      out.write("\r\n");
      out.write("<!-- Vendor CSS-->\r\n");
      out.write("<link href=\"/corona/bootstrap/vendor/animsition/animsition.min.css\" rel=\"stylesheet\" media=\"all\">\r\n");
      out.write("<link href=\"/corona/bootstrap/vendor/bootstrap-progressbar/bootstrap-progressbar-3.3.4.min.css\" rel=\"stylesheet\" media=\"all\">\r\n");
      out.write("<link href=\"/corona/bootstrap/vendor/wow/animate.css\" rel=\"stylesheet\" media=\"all\">\r\n");
      out.write("<link href=\"/corona/bootstrap/vendor/css-hamburgers/hamburgers.min.css\" rel=\"stylesheet\" media=\"all\">\r\n");
      out.write("<link href=\"/corona/bootstrap/vendor/slick/slick.css\" rel=\"stylesheet\" media=\"all\">\r\n");
      out.write("<link href=\"/corona/bootstrap/vendor/select2/select2.min.css\" rel=\"stylesheet\" media=\"all\">\r\n");
      out.write("<link href=\"/corona/bootstrap/vendor/perfect-scrollbar/perfect-scrollbar.css\" rel=\"stylesheet\" media=\"all\">\r\n");
      out.write("\r\n");
      out.write("<!-- Main CSS-->\r\n");
      out.write("<link href=\"/corona/bootstrap/css/theme.css\" rel=\"stylesheet\" media=\"all\">\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Jquery JS-->\r\n");
      out.write("<script src=\"/corona/bootstrap/vendor/jquery-3.2.1.min.js\"></script>\r\n");
      out.write("<!-- Bootstrap JS-->\r\n");
      out.write("<script src=\"/corona/bootstrap/vendor/bootstrap-4.1/popper.min.js\"></script>\r\n");
      out.write("<script src=\"/corona/bootstrap/vendor/bootstrap-4.1/bootstrap.min.js\"></script>\r\n");
      out.write("<!-- Vendor JS       -->\r\n");
      out.write("<script src=\"/corona/bootstrap/vendor/slick/slick.min.js\">\r\n");
      out.write("</script>\r\n");
      out.write("<script src=\"/corona/bootstrap/vendor/wow/wow.min.js\"></script>\r\n");
      out.write("<script src=\"/corona/bootstrap/vendor/animsition/animsition.min.js\"></script>\r\n");
      out.write("<script src=\"/corona/bootstrap/vendor/bootstrap-progressbar/bootstrap-progressbar.min.js\">\r\n");
      out.write("</script>\r\n");
      out.write("<script src=\"/corona/bootstrap/vendor/counter-up/jquery.waypoints.min.js\"></script>\r\n");
      out.write("<script src=\"/corona/bootstrap/vendor/counter-up/jquery.counterup.min.js\">\r\n");
      out.write("</script>\r\n");
      out.write("<script src=\"/corona/bootstrap/vendor/circle-progress/circle-progress.min.js\"></script>\r\n");
      out.write("<script src=\"/corona/bootstrap/vendor/perfect-scrollbar/perfect-scrollbar.js\"></script>\r\n");
      out.write("<script src=\"/corona/bootstrap/vendor/chartjs/Chart.bundle.min.js\"></script>\r\n");
      out.write("<script src=\"/corona/bootstrap/vendor/select2/select2.min.js\">\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<!-- Main JS-->\r\n");
      out.write("<script src=\"/corona/bootstrap/js/main.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- alert -->\r\n");
      out.write("<script src=\"/corona/jquery.modal-master/js/DesignAlert.js\"></script>\r\n");
      out.write("<script src=\"/corona/jquery.modal-master/js/jquery.modal.js\"></script>\r\n");
      out.write("<script src=\"/corona/jquery.modal-master/js/jquery.modal.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<link href=\"/corona/jquery.modal-master/css/jquery.modal.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"/corona/jquery.modal-master/css/jquery.modal.theme-atlant.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"/corona/jquery.modal-master/css/jquery.modal.theme-xenon.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- jQuery -->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/corona/css/jquery-ui.css\" />\r\n");
      out.write("<!-- <script src=\"http://code.jquery.com/jquery.min.js\"></script>-->\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      if (_jspx_meth_c_005furl_005f0(_jspx_page_context))
        return;
      out.write("\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      if (_jspx_meth_c_005furl_005f1(_jspx_page_context))
        return;
      out.write("\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      if (_jspx_meth_c_005furl_005f2(_jspx_page_context))
        return;
      out.write("\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      if (_jspx_meth_c_005furl_005f3(_jspx_page_context))
        return;
      out.write("\"></script>\r\n");
      out.write("<script src=\"");
      if (_jspx_meth_c_005furl_005f4(_jspx_page_context))
        return;
      out.write("\" charset=\"utf-8\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- \r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/corona/css/common.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/corona/css/import.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/corona/css/skin01.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/corona/css/corona.css\" />\r\n");
      out.write(" -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"https://www.gstatic.com/charts/loader.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tvar user_right = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.userinfo.userright}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\r\n");
      out.write("\r\n");
      out.write("\t$(document).ready(function() {\r\n");
      out.write("\t\t//공통\r\n");
      out.write("\t\tvar WRITE_DATE=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${WRITE_DATE}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\r\n");
      out.write("\t\tvar DEPART=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${DEPART}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar totalStatisticList=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${totalStatisticList}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\r\n");
      out.write("\t\t//구글차트 그리기\r\n");
      out.write("\t\tgoogle.charts.load('current', {'packages':['line','controls']});\r\n");
      out.write("\t\tchartConsultDrow(totalStatisticList); //chartDrow() 실행\r\n");
      out.write("\r\n");
      out.write("\t\t//상담민원\r\n");
      out.write("\t\tfn_selectConsultMiddle(WRITE_DATE,'주간','TODAY');\r\n");
      out.write("\t\tfn_selectConsultMiddle(WRITE_DATE,'야간','TODAY');\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfn_selectConsultMiddle(WRITE_DATE,'주간','누적');\r\n");
      out.write("\t\tfn_selectConsultMiddle(WRITE_DATE,'야간','누적');\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t//상담상세\r\n");
      out.write("\tfunction go_consultDtl(CONSULT_DEPART,CONSULT_JUYA_GUBUN,CONSULT_CONSULT_GUBUN,WRITE_DATE){\r\n");
      out.write("\t\t\r\n");
      out.write(" \t\tvar comSubmit = new ComSubmit();\r\n");
      out.write("\t\tcomSubmit.setUrl(\"");
      if (_jspx_meth_c_005furl_005f5(_jspx_page_context))
        return;
      out.write("\");\r\n");
      out.write("\t\tcomSubmit.addParam(\"CONSULT_DEPART\", CONSULT_DEPART);\r\n");
      out.write("\t\tcomSubmit.addParam(\"CONSULT_JUYA_GUBUN\", CONSULT_JUYA_GUBUN);\r\n");
      out.write("\t\tcomSubmit.addParam(\"CONSULT_CONSULT_GUBUN\", CONSULT_CONSULT_GUBUN);\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tcomSubmit.addParam(\"WRITE_DATE\", WRITE_DATE);\r\n");
      out.write("\t\tcomSubmit.submit();\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t//상담민원차트 그리기\r\n");
      out.write("\t  function chartConsultDrow(consultStatisticList){\r\n");
      out.write("\t    var chartData = '';\r\n");
      out.write("\r\n");
      out.write("\t    //날짜형식 변경하고 싶으시면 이 부분 수정하세요.\r\n");
      out.write("\t    var chartDateformat     = 'yyyy년MM월dd일';\r\n");
      out.write("\t    //라인차트의 라인 수\r\n");
      out.write("\t    var chartLineCount    = 15;\r\n");
      out.write("\t    //컨트롤러 바 차트의 라인 수\r\n");
      out.write("\t    var controlLineCount    = 10;\r\n");
      out.write("\r\n");
      out.write("\t    function drawDashboard() {\r\n");
      out.write("\t      var data = new google.visualization.DataTable();\r\n");
      out.write("\t      //그래프에 표시할 컬럼 추가\r\n");
      out.write("\t      data.addColumn('datetime' , '날짜');\r\n");
      out.write("\t      data.addColumn('number'   , '전체');\r\n");
      out.write("\t      data.addColumn('number'   , '주간상담');\r\n");
      out.write("\t      data.addColumn('number'   , '야간상담');\r\n");
      out.write("\t      //그래프에 표시할 데이터\r\n");
      out.write("\t      var dataRow = [];\r\n");
      out.write("\t  \t\r\n");
      out.write("\t  \t");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t  \t\r\n");
      out.write("\r\n");
      out.write("\t        var chart = new google.visualization.ChartWrapper({\r\n");
      out.write("\t          chartType   : 'LineChart',\r\n");
      out.write("\t          containerId : 'lineChartArea', //라인 차트 생성할 영역\r\n");
      out.write("\t          options     : {\r\n");
      out.write("\t                          isStacked   : 'percent',\r\n");
      out.write("\t                          focusTarget : 'category',\r\n");
      out.write("\t                          height          : 300,\r\n");
      out.write("\t                          width              : '100%',\r\n");
      out.write("\t                          legend          : { position: \"top\", textStyle: {fontSize: 13}},\r\n");
      out.write("\t                          pointSize        : 5,\r\n");
      out.write("\t                          tooltip          : {textStyle : {fontSize:12}, showColorCode : true,trigger: 'both'},\r\n");
      out.write("\t                          hAxis              : {format: chartDateformat, gridlines:{count:chartLineCount,units: {\r\n");
      out.write("\t                                                              years : {format: ['yyyy년']},\r\n");
      out.write("\t                                                              months: {format: ['MM월']},\r\n");
      out.write("\t                                                              days  : {format: ['dd일']},\r\n");
      out.write("\t                                                              hours : {format: ['HH시']}}\r\n");
      out.write("\t                                                            },textStyle: {fontSize:12}},\r\n");
      out.write("\t\t\t\t\t\t\tvAxis              : {\r\n");
      out.write("\t                                   \t             \t\t\t\tminValue: 1,\r\n");
      out.write("\t                                   \t             \t\t\t\tviewWindow:{min:0},\r\n");
      out.write("\t                                   \t             \t\t\t\tgridlines:{count:8},\r\n");
      out.write("\t                                   \t             \t\t\t\ttextStyle:{fontSize:12}\r\n");
      out.write("\t                                   \t             \t\t\t\t},\r\n");
      out.write("\t            animation        : {startup: true,duration: 1000,easing: 'in' },\r\n");
      out.write("\t            annotations    : {pattern: chartDateformat,\r\n");
      out.write("\t                            textStyle: {\r\n");
      out.write("\t                            fontSize: 15,\r\n");
      out.write("\t                            bold: true,\r\n");
      out.write("\t                            italic: true,\r\n");
      out.write("\t                            color: '#871b47',\r\n");
      out.write("\t                            auraColor: '#d799ae',\r\n");
      out.write("\t                            opacity: 0.8,\r\n");
      out.write("\t                            pattern: chartDateformat\r\n");
      out.write("\t                          }\r\n");
      out.write("\t                        }\r\n");
      out.write("\t          }\r\n");
      out.write("\t        });\r\n");
      out.write("\r\n");
      out.write("\t        var control = new google.visualization.ControlWrapper({\r\n");
      out.write("\t          controlType: 'ChartRangeFilter',\r\n");
      out.write("\t          containerId: 'controlsArea',  //control bar를 생성할 영역\r\n");
      out.write("\t          options: {\r\n");
      out.write("\t              ui:{\r\n");
      out.write("\t                    chartType: 'LineChart',\r\n");
      out.write("\t                    chartOptions: {\r\n");
      out.write("\t                    chartArea: {'width': '60%','height' : 40},\r\n");
      out.write("\t                      hAxis: {'baselineColor': 'none', format: chartDateformat, textStyle: {fontSize:12},\r\n");
      out.write("\t                        gridlines:{count:controlLineCount,units: {\r\n");
      out.write("\t                              years : {format: ['yyyy년']},\r\n");
      out.write("\t                              months: {format: ['MM월']},\r\n");
      out.write("\t                              days  : {format: ['dd일']},\r\n");
      out.write("\t                              hours : {format: ['HH시']}}\r\n");
      out.write("\t                        }}\r\n");
      out.write("\t                    }\r\n");
      out.write("\t              },\r\n");
      out.write("\t                filterColumnIndex: 0\r\n");
      out.write("\t            }\r\n");
      out.write("\t        });\r\n");
      out.write("\r\n");
      out.write("\t        var date_formatter = new google.visualization.DateFormat({ pattern: chartDateformat});\r\n");
      out.write("\t        date_formatter.format(data, 0);\r\n");
      out.write("\r\n");
      out.write("\t        var dashboard = new google.visualization.Dashboard(document.getElementById('Line_Controls_Chart'));\r\n");
      out.write("\t        window.addEventListener('resize', function() { dashboard.draw(data); }, false); //화면 크기에 따라 그래프 크기 변경\r\n");
      out.write("\t        dashboard.bind([control], [chart]);\r\n");
      out.write("\t        dashboard.draw(data);\r\n");
      out.write("\r\n");
      out.write("\t    }\r\n");
      out.write("\t      google.charts.setOnLoadCallback(drawDashboard);\r\n");
      out.write("\r\n");
      out.write("\t  }\r\n");
      out.write("\t\r\n");
      out.write("\t//상담 중간 요약\r\n");
      out.write("\tfunction fn_selectConsultMiddle(WRITE_DATE,JUYA_GUBUN,DEPART){\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar comAjax = new ComAjax();\r\n");
      out.write("\t\tcomAjax.setUrl(\"");
      if (_jspx_meth_c_005furl_005f6(_jspx_page_context))
        return;
      out.write("\");\r\n");
      out.write("\t\tcomAjax.addParam(\"WRITE_DATE\", WRITE_DATE);\r\n");
      out.write("\t\tcomAjax.addParam(\"JUYA_GUBUN\", JUYA_GUBUN);\r\n");
      out.write("\t\tcomAjax.addParam(\"DEPART\", DEPART);\r\n");
      out.write("\t\tcomAjax.setCallback(\"fn_selectConsultMiddleCallback\");\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tcomAjax.ajax();\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction fn_selectConsultMiddleCallback(data){\r\n");
      out.write("\t\tvar total = data.total;\t\t\t\r\n");
      out.write("\t\tvar body = $(\"#mytable\");\r\n");
      out.write("\t\tvar recordcnt = $(\"#RECORD_COUNT\").val();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"#tcnt\").text(comma(total));\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//body.empty();\r\n");
      out.write("\t\tif(total == 0){\r\n");
      out.write("\t\t\tvar str = \"<tr>\" + \r\n");
      out.write("\t\t\t\t  \"<td colspan='14' style='text-align:center;'>조회된 결과가 없습니다.</td>\" +\r\n");
      out.write("\t\t\t\t  \"</tr>\";\r\n");
      out.write("\t\t\tbody.append(str);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\telse{\r\n");
      out.write("\t\t\tvar params = {\r\n");
      out.write("\t\t\t\tdivId : \"PAGE_NAVI\",\r\n");
      out.write("\t\t\t\tpageIndex : \"PAGE_INDEX\",\r\n");
      out.write("\t\t\t\ttotalCount : total,\r\n");
      out.write("\t\t\t\trecordCount : recordcnt,\r\n");
      out.write("\t\t\t\teventName : \"fn_selectTotalMiddle\"\r\n");
      out.write("\t\t\t};\r\n");
      out.write("\t\t\tgfn_renderPaging(params);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar str = \"\";\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar insert_str = null;\r\n");
      out.write("\t\t\tvar accum_juya_background = \"\";\r\n");
      out.write("\t\t\tvar accum_juya_background2 = \"\";\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$.each(data.list, function(key, value){\r\n");
      out.write("\t\t\t\tif(value.ODR_CONSULT_GUBUN ==2){\r\n");
      out.write("\t\t\t\t\tif(value.DEPART == 'TODAY'){\r\n");
      out.write("\t\t\t\t\t\tinsert_str = value.WRITE_DATE+\"(\"+value.CONSULT_GUBUN_CNT+\")\";\r\n");
      out.write("\t\t\t\t\t\tif(value.JUYA_GUBUN =='주간'){\r\n");
      out.write("\t\t\t\t\t\t\taccum_juya_background = \"style='background-color:#088A85;'\";\r\n");
      out.write("\t\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\t\taccum_juya_background = \"style='background-color:white;'\";\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\tinsert_str = \"누적(\"+value.CONSULT_GUBUN_CNT+\")\";\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\tif(value.JUYA_GUBUN =='주간'){\r\n");
      out.write("\t\t\t\t\t\t\taccum_juya_background = \"style='background-color:#ffc314;'\";\r\n");
      out.write("\t\t\t\t\t\t\taccum_juya_background2 = \"style='color:#ff0000;CURSOR:hand;font-weight:bold;'\";\r\n");
      out.write("\t\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\t\taccum_juya_background = \"style='background-color:white;'\";\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t  str += \r\n");
      out.write("\t\t\t\t\t\t  \"<div style='display: inline-block;vertical-align:top;'>  \"+\r\n");
      out.write("\t\t\t\t\t\t  \"<table style='width:300;'>  \"+   \r\n");
      out.write("\t\t\t\t\t\t  \"<thead style='background-color:#0B2161;'>  \"+\r\n");
      out.write("\t\t\t\t\t\t        \"<tr align='center' \"+accum_juya_background+\">                      \"+\r\n");
      out.write("\t\t\t\t\t\t\t\t\"<th \"+accum_juya_background2+\" colspan='2' onclick='go_consultDtl(\\\"\"+value.DEPART+\"\\\",\\\"\\\",\\\"\\\",\\\"\"+value.WRITE_DATE+\"\\\")'>\"+insert_str+\"</th>              \"+\r\n");
      out.write("\t\t\t\t\t\t\t\t\"</tr>                                    \";\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t  accum_juya_background = \"\";\r\n");
      out.write("\t\t\t\t\t  accum_juya_background2 = \"style='CURSOR:hand;font-weight:bold;'\"\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tif(typeof value.CONSULT_GUBUN =='undefined' && value.ODR_CONSULT_GUBUN !=2){\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t  str += \r\n");
      out.write("\t\t\t\t\t\t  \"<div style='display: inline-block;vertical-align:top;'>  \"+\r\n");
      out.write("\t\t\t\t\t\t  \"<table style='width:300;'>  \"+   \r\n");
      out.write("\t\t\t\t\t\t  \"<thead style='background-color:#0B2161;'>  \"+\r\n");
      out.write("\t\t\t\t\t\t        \"<tr align='center'>                      \"+\r\n");
      out.write("\t\t\t\t\t\t\t\t\"<th colspan='3' style='CURSOR:hand;font-weight:bold;' onclick='go_consultDtl(\\\"\"+value.DEPART+\"\\\",\\\"\"+value.JUYA_GUBUN+\"\\\",\\\"\\\",\\\"\"+value.WRITE_DATE+\"\\\")'>\"+value.JUYA_GUBUN+\"(\"+value.CONSULT_GUBUN_CNT+\")</th>              \"+\r\n");
      out.write("\t\t\t\t\t\t\t\t\"</tr>                                    \"+\r\n");
      out.write("\t\t\t\t\t\t        \"<tr align='center'>                      \"+\r\n");
      out.write("\t\t\t\t\t\t\t\t\"\t<th width='60%'>상담유형</th>                           \"+\r\n");
      out.write("\t\t\t\t\t\t\t\t\"\t<th width='40%'>상담자수</th>                           \"+\r\n");
      out.write("\t\t\t\t\t\t\t\t\"</tr>                                    \"+\r\n");
      out.write("\t\t\t\t\t\t      \"</thead>                                  \"+\r\n");
      out.write("\t\t\t\t    \t   \"<tbody>\";\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tif(typeof value.CONSULT_GUBUN !='undefined'){\r\n");
      out.write("\t\t\t\t\tstr += \r\n");
      out.write("\t\t\t\t\t\t\"<tr>                                    \" +\r\n");
      out.write("\t\t\t\t\t\t\"\t<td>\"+value.CONSULT_GUBUN+\"</td>  \" +\r\n");
      out.write("\t\t\t\t\t\t\"\t<td style='CURSOR:hand;color:#0099FF;text-align:center;' onclick='go_consultDtl(\\\"\"+value.DEPART+\"\\\",\\\"\"+value.JUYA_GUBUN+\"\\\",\\\"\"+value.CONSULT_GUBUN+\"\\\",\\\"\"+value.WRITE_DATE+\"\\\")'>\"+value.CONSULT_GUBUN_CNT+\"</td>  \" +\r\n");
      out.write("\t\t\t\t\t\t\"</tr>                                   \"; \r\n");
      out.write("\t\t\t\t\tbefore_so = \"\";\t\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}); \r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif(data.list_size == 1){\r\n");
      out.write("\t\t\t\tstr += \r\n");
      out.write("\t\t\t\t\t\"<tr>                                    \" +\r\n");
      out.write("\t\t\t\t\t\"\t<td colspan=2 style='background-color:white;text-align:center;'>조회결과없음</td>  \" +\r\n");
      out.write("\t\t\t\t\t\"</tr>                                   \"; \r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tstr += \"</tbody>\"+\r\n");
      out.write("\t\t\t\t\t\"</table>\"+\r\n");
      out.write("\t\t\t\t\t\"</div>\";\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\tbody.append(str);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write(" u {\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("    border-bottom: 10px solid black;\r\n");
      out.write("  }​\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div style=\"background-color:#170B3B;color:white; margin-bottom:10px; width: 100%;\">\r\n");
      out.write("\t<a href=\"#this\" class=\"btn\" id=\"logout\">\r\n");
      out.write("\t\t<img src=\"/corona/images/popup_title.gif\" align=\"absmiddle\">\r\n");
      out.write("\t</a>현황 요약 정보\r\n");
      out.write("\t\r\n");
      out.write("\t<div style=\"padding-right:10px;padding-top:7px;float:right;\">\r\n");
      out.write("\t\t<a href=\"/corona/status/mainStatusView.do\" class=\"btn btn-success\" id=\"statistics\"><i class=\"fa fa-reply\"></i> 코로나19 현황</a>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("  table {\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    border: 1px solid #444444;\r\n");
      out.write("  }\r\n");
      out.write("  th, td {\r\n");
      out.write("    border: 1px solid #444444;\r\n");
      out.write("  }\r\n");
      out.write("</style>\r\n");
      out.write("\t\t<!-- 재난안전과 요청 테이블 -->\r\n");
      out.write("\t\t<div class=\"table-responsive m-b-40\" style=\"display:none;\">\r\n");
      out.write("\t\t\t<table>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td rowspan='2'>주야간 구분</td>\r\n");
      out.write("\t\t\t\t\t<td rowspan='2'>주간(09:00~22:00)</td>\r\n");
      out.write("\t\t\t\t\t<td>건</td>\r\n");
      out.write("\t\t\t\t\t<td rowspan='2'>야간(22:00~09:00)</td>\r\n");
      out.write("\t\t\t\t\t<td>건</td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>%</td>\r\n");
      out.write("\t\t\t\t\t<td>%</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t\t<table style='border:1px solid;'>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td colspan='2'>1. 검사결과 문의</td>\r\n");
      out.write("\t\t\t\t\t<td colspan='2'>2. 검사관련 문의</td>\r\n");
      out.write("\t\t\t\t\t<td colspan='2'>3. 자가격리(자)관련 문의</td>\r\n");
      out.write("\t\t\t\t\t<td colspan='2'>4. 선별진료소(시간)관련 문의</td>\r\n");
      out.write("\t\t\t\t\t<td colspan='2'>5. 확진자 관련 문의</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>금일</td>\r\n");
      out.write("\t\t\t\t\t<td>건(%)</td>\r\n");
      out.write("\t\t\t\t\t<td>금일</td>\r\n");
      out.write("\t\t\t\t\t<td>건(%)</td>\r\n");
      out.write("\t\t\t\t\t<td>금일</td>\r\n");
      out.write("\t\t\t\t\t<td>건(%)</td>\r\n");
      out.write("\t\t\t\t\t<td>금일</td>\r\n");
      out.write("\t\t\t\t\t<td>건(%)</td>\r\n");
      out.write("\t\t\t\t\t<td>금일</td>\r\n");
      out.write("\t\t\t\t\t<td>건(%)</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>누계</td>\r\n");
      out.write("\t\t\t\t\t<td>건(%)</td>\r\n");
      out.write("\t\t\t\t\t<td>누계</td>\r\n");
      out.write("\t\t\t\t\t<td>건(%)</td>\r\n");
      out.write("\t\t\t\t\t<td>누계</td>\r\n");
      out.write("\t\t\t\t\t<td>건(%)</td>\r\n");
      out.write("\t\t\t\t\t<td>누계</td>\r\n");
      out.write("\t\t\t\t\t<td>건(%)</td>\r\n");
      out.write("\t\t\t\t\t<td>누계</td>\r\n");
      out.write("\t\t\t\t\t<td>건(%)</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td colspan='2'>6. 역학조사 관련문의</td>\r\n");
      out.write("\t\t\t\t\t<td colspan='2'>7. 임시생활시설관련 문의</td>\r\n");
      out.write("\t\t\t\t\t<td colspan='2'>8. 사회적 거리두기 관련 문의</td>\r\n");
      out.write("\t\t\t\t\t<td colspan='2'>9. 방역관련 문의</td>\r\n");
      out.write("\t\t\t\t\t<td colspan='2'>10. 기타 문의</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>금일</td>\r\n");
      out.write("\t\t\t\t\t<td>건(%)</td>\r\n");
      out.write("\t\t\t\t\t<td>금일</td>\r\n");
      out.write("\t\t\t\t\t<td>건(%)</td>\r\n");
      out.write("\t\t\t\t\t<td>금일</td>\r\n");
      out.write("\t\t\t\t\t<td>건(%)</td>\r\n");
      out.write("\t\t\t\t\t<td>금일</td>\r\n");
      out.write("\t\t\t\t\t<td>건(%)</td>\r\n");
      out.write("\t\t\t\t\t<td>금일</td>\r\n");
      out.write("\t\t\t\t\t<td>건(%)</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>누계</td>\r\n");
      out.write("\t\t\t\t\t<td>건(%)</td>\r\n");
      out.write("\t\t\t\t\t<td>누계</td>\r\n");
      out.write("\t\t\t\t\t<td>건(%)</td>\r\n");
      out.write("\t\t\t\t\t<td>누계</td>\r\n");
      out.write("\t\t\t\t\t<td>건(%)</td>\r\n");
      out.write("\t\t\t\t\t<td>누계</td>\r\n");
      out.write("\t\t\t\t\t<td>건(%)</td>\r\n");
      out.write("\t\t\t\t\t<td>누계</td>\r\n");
      out.write("\t\t\t\t\t<td>건(%)</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t<div align=\"left\"  style='overflow:scroll;padding-left:20px;' id=\"mytable_etc\">\r\n");
      out.write("\t\t<div class=\"table-responsive m-b-40\" style='overflow:scroll;width:700;' id='change_width'>\r\n");
      out.write("\t\t\t <table class=\"table table-bordered table-data3\" align=\"left\" id=\"mytable\">\r\n");
      out.write("\t\t      </table>\r\n");
      out.write("\t      </div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\t<br>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- 그래프 -->\r\n");
      out.write("\t<div style=\"width:100%;;height:500px;padding-left:40px;\" id=\"chartArea\">\r\n");
      out.write("\t    <h4 id=\"graphTitle\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[상담민원 일일 현황]</h4>\r\n");
      out.write(" \r\n");
      out.write("    \t<div id=\"Line_Controls_Chart\">\r\n");
      out.write("      \t\t<!-- 라인 차트 생성할 영역 -->\r\n");
      out.write("          <div id=\"lineChartArea\"></div>\r\n");
      out.write("      \t\t<!-- 컨트롤바를 생성할 영역 -->\r\n");
      out.write("          <div id=\"controlsArea\"></div>\r\n");
      out.write("        </div>\r\n");
      out.write("\t</div>\r\n");
      out.write("<br>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<form id=\"commonForm\" name=\"commonForm\"></form>");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f0.setParent(null);
    // /WEB-INF/include/include-header.jspf(69,36) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f0.setValue("/js/jquery.min.js");
    int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
    if (_jspx_th_c_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f1 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f1.setParent(null);
    // /WEB-INF/include/include-header.jspf(70,36) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f1.setValue("/js/jquery-ui.js");
    int _jspx_eval_c_005furl_005f1 = _jspx_th_c_005furl_005f1.doStartTag();
    if (_jspx_th_c_005furl_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f1);
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f2 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f2.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f2.setParent(null);
    // /WEB-INF/include/include-header.jspf(71,36) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f2.setValue("/js/jquery.cookie.js");
    int _jspx_eval_c_005furl_005f2 = _jspx_th_c_005furl_005f2.doStartTag();
    if (_jspx_th_c_005furl_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f2);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f2);
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f3 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f3.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f3.setParent(null);
    // /WEB-INF/include/include-header.jspf(72,36) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f3.setValue("/js/jquery.form.js");
    int _jspx_eval_c_005furl_005f3 = _jspx_th_c_005furl_005f3.doStartTag();
    if (_jspx_th_c_005furl_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f3);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f3);
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f4 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f4.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f4.setParent(null);
    // /WEB-INF/include/include-header.jspf(73,13) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f4.setValue("/js/common.js");
    int _jspx_eval_c_005furl_005f4 = _jspx_th_c_005furl_005f4.doStartTag();
    if (_jspx_th_c_005furl_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f4);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f4);
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f5(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f5 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f5.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f5.setParent(null);
    // /WEB-INF/jsp/status/statusMiddleView.jsp(31,20) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f5.setValue("/status/statusTrackingView.do");
    int _jspx_eval_c_005furl_005f5 = _jspx_th_c_005furl_005f5.doStartTag();
    if (_jspx_th_c_005furl_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f5);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f5);
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f0.setParent(null);
    // /WEB-INF/jsp/status/statusMiddleView.jsp(61,4) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/jsp/status/statusMiddleView.jsp(61,4) '${consultStatisticList}'",_el_expressionfactory.createValueExpression(_jspx_page_context.getELContext(),"${consultStatisticList}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    // /WEB-INF/jsp/status/statusMiddleView.jsp(61,4) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setVar("info");
    int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
      if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t  \tvar CUR_TOTAL =parseInt(\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${info.CUR_TOTAL}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\");\r\n");
          out.write("\t  \tvar CUR_JU =parseInt(\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${info.CUR_JU}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\"); \r\n");
          out.write("\t  \tvar CUR_YA =parseInt(\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${info.CUR_YA}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\"); \r\n");
          out.write("\t  \t\t\r\n");
          out.write("\t  \tdataRow = [new Date(\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${info.ST_DAY}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\".substring(0,4), \"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${info.ST_DAY}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\".substring(4,6)-1, \"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${info.ST_DAY}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\".substring(6,8) ,'00' ),CUR_TOTAL, CUR_JU, CUR_JU];\r\n");
          out.write("\t\t    data.addRow(dataRow); \r\n");
          out.write("\t  \t");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f0.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f6(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f6 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f6.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f6.setParent(null);
    // /WEB-INF/jsp/status/statusMiddleView.jsp(147,18) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f6.setValue("/status/selectConsultMiddle.do");
    int _jspx_eval_c_005furl_005f6 = _jspx_th_c_005furl_005f6.doStartTag();
    if (_jspx_th_c_005furl_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f6);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f6);
    return false;
  }
}
