/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.24
 * Generated at: 2020-08-02 06:51:07 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.status;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class statusAccumMiddleView_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(6);
    _jspx_dependants.put("jar:file:/C:/dev/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp15/wtpwebapps/corona/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/C:/dev/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp15/wtpwebapps/corona/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/include/include-body.jspf", Long.valueOf(1595128796000L));
    _jspx_dependants.put("jar:file:/C:/dev/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp15/wtpwebapps/corona/WEB-INF/lib/jstl-1.2.jar!/META-INF/fn.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1595463255549L));
    _jspx_dependants.put("/WEB-INF/include/include-header.jspf", Long.valueOf(1595638909926L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("<!-- Fontfaces CSS-->\r\n");
      out.write("<link href=\"/corona/bootstrap/css/font-face.css\" rel=\"stylesheet\" media=\"all\">\r\n");
      out.write("<link href=\"/corona/bootstrap/vendor/font-awesome-4.7/css/font-awesome.min.css\" rel=\"stylesheet\" media=\"all\">\r\n");
      out.write("<link href=\"/corona/bootstrap/vendor/font-awesome-5/css/fontawesome-all.min.css\" rel=\"stylesheet\" media=\"all\">\r\n");
      out.write("<link href=\"/corona/bootstrap/vendor/mdi-font/css/material-design-iconic-font.min.css\" rel=\"stylesheet\" media=\"all\">\r\n");
      out.write("\r\n");
      out.write("<!-- Bootstrap CSS-->\r\n");
      out.write("<link href=\"/corona/bootstrap/vendor/bootstrap-4.1/bootstrap.min.css\" rel=\"stylesheet\" media=\"all\">\r\n");
      out.write("\r\n");
      out.write("<!-- Vendor CSS-->\r\n");
      out.write("<link href=\"/corona/bootstrap/vendor/animsition/animsition.min.css\" rel=\"stylesheet\" media=\"all\">\r\n");
      out.write("<link href=\"/corona/bootstrap/vendor/bootstrap-progressbar/bootstrap-progressbar-3.3.4.min.css\" rel=\"stylesheet\" media=\"all\">\r\n");
      out.write("<link href=\"/corona/bootstrap/vendor/wow/animate.css\" rel=\"stylesheet\" media=\"all\">\r\n");
      out.write("<link href=\"/corona/bootstrap/vendor/css-hamburgers/hamburgers.min.css\" rel=\"stylesheet\" media=\"all\">\r\n");
      out.write("<link href=\"/corona/bootstrap/vendor/slick/slick.css\" rel=\"stylesheet\" media=\"all\">\r\n");
      out.write("<link href=\"/corona/bootstrap/vendor/select2/select2.min.css\" rel=\"stylesheet\" media=\"all\">\r\n");
      out.write("<link href=\"/corona/bootstrap/vendor/perfect-scrollbar/perfect-scrollbar.css\" rel=\"stylesheet\" media=\"all\">\r\n");
      out.write("\r\n");
      out.write("<!-- Main CSS-->\r\n");
      out.write("<link href=\"/corona/bootstrap/css/theme.css\" rel=\"stylesheet\" media=\"all\">\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Jquery JS-->\r\n");
      out.write("<script src=\"/corona/bootstrap/vendor/jquery-3.2.1.min.js\"></script>\r\n");
      out.write("<!-- Bootstrap JS-->\r\n");
      out.write("<script src=\"/corona/bootstrap/vendor/bootstrap-4.1/popper.min.js\"></script>\r\n");
      out.write("<script src=\"/corona/bootstrap/vendor/bootstrap-4.1/bootstrap.min.js\"></script>\r\n");
      out.write("<!-- Vendor JS       -->\r\n");
      out.write("<script src=\"/corona/bootstrap/vendor/slick/slick.min.js\">\r\n");
      out.write("</script>\r\n");
      out.write("<script src=\"/corona/bootstrap/vendor/wow/wow.min.js\"></script>\r\n");
      out.write("<script src=\"/corona/bootstrap/vendor/animsition/animsition.min.js\"></script>\r\n");
      out.write("<script src=\"/corona/bootstrap/vendor/bootstrap-progressbar/bootstrap-progressbar.min.js\">\r\n");
      out.write("</script>\r\n");
      out.write("<script src=\"/corona/bootstrap/vendor/counter-up/jquery.waypoints.min.js\"></script>\r\n");
      out.write("<script src=\"/corona/bootstrap/vendor/counter-up/jquery.counterup.min.js\">\r\n");
      out.write("</script>\r\n");
      out.write("<script src=\"/corona/bootstrap/vendor/circle-progress/circle-progress.min.js\"></script>\r\n");
      out.write("<script src=\"/corona/bootstrap/vendor/perfect-scrollbar/perfect-scrollbar.js\"></script>\r\n");
      out.write("<script src=\"/corona/bootstrap/vendor/chartjs/Chart.bundle.min.js\"></script>\r\n");
      out.write("<script src=\"/corona/bootstrap/vendor/select2/select2.min.js\">\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<!-- Main JS-->\r\n");
      out.write("<script src=\"/corona/bootstrap/js/main.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- alert -->\r\n");
      out.write("<script src=\"/corona/jquery.modal-master/js/DesignAlert.js\"></script>\r\n");
      out.write("<script src=\"/corona/jquery.modal-master/js/jquery.modal.js\"></script>\r\n");
      out.write("<script src=\"/corona/jquery.modal-master/js/jquery.modal.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<link href=\"/corona/jquery.modal-master/css/jquery.modal.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"/corona/jquery.modal-master/css/jquery.modal.theme-atlant.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"/corona/jquery.modal-master/css/jquery.modal.theme-xenon.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- jQuery -->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/corona/css/jquery-ui.css\" />\r\n");
      out.write("<!-- <script src=\"http://code.jquery.com/jquery.min.js\"></script>-->\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      if (_jspx_meth_c_005furl_005f0(_jspx_page_context))
        return;
      out.write("\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      if (_jspx_meth_c_005furl_005f1(_jspx_page_context))
        return;
      out.write("\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      if (_jspx_meth_c_005furl_005f2(_jspx_page_context))
        return;
      out.write("\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      if (_jspx_meth_c_005furl_005f3(_jspx_page_context))
        return;
      out.write("\"></script>\r\n");
      out.write("<script src=\"");
      if (_jspx_meth_c_005furl_005f4(_jspx_page_context))
        return;
      out.write("\" charset=\"utf-8\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- \r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/corona/css/common.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/corona/css/import.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/corona/css/skin01.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/corona/css/corona.css\" />\r\n");
      out.write(" -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tvar user_right = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.userinfo.userright}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\r\n");
      out.write("\r\n");
      out.write("\t$(document).ready(function() {\r\n");
      out.write("\t\t//공통\r\n");
      out.write("\t\tvar WRITE_DATE=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${WRITE_DATE}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\r\n");
      out.write("\r\n");
      out.write("\t\t//확진자\r\n");
      out.write("\t\tvar INFECT_GUBUN=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${INFECT_GUBUN}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\r\n");
      out.write("\t\tvar INFECT_DAE=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${INFECT_DAE}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\r\n");
      out.write("\t\tvar INFECT_SO=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${INFECT_SO}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(INFECT_GUBUN !=''){\r\n");
      out.write("\t\t\tfn_selectConfirmMiddleOversea(INFECT_GUBUN,INFECT_DAE,WRITE_DATE);\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(INFECT_GUBUN =='' && INFECT_DAE !=''){\r\n");
      out.write("\t\t\tfn_selectConfirmMiddle(INFECT_GUBUN,INFECT_DAE,WRITE_DATE);\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tfn_selectConfirmMiddleHospital(INFECT_GUBUN,INFECT_DAE,WRITE_DATE);\r\n");
      out.write("\t\t\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t//확진자 요약 상세\r\n");
      out.write("\tfunction go_confirmDtl(INFECT_GUBUN,INFECT_DAE,INFECT_SO,WRITE_DATE,ETC_GUBUN,ETC_GUBUN_CONDITION){\r\n");
      out.write(" \t\tvar comSubmit = new ComSubmit();\r\n");
      out.write("\t\tcomSubmit.setUrl(\"");
      if (_jspx_meth_c_005furl_005f5(_jspx_page_context))
        return;
      out.write("\");\r\n");
      out.write("\t\tcomSubmit.addParam(\"INFECT_GUBUN\", INFECT_GUBUN);\r\n");
      out.write("\t\tcomSubmit.addParam(\"INFECT_DAE\", INFECT_DAE);\r\n");
      out.write("\t\tcomSubmit.addParam(\"INFECT_SO\", INFECT_SO);\r\n");
      out.write("\t\tcomSubmit.addParam(\"WRITE_DATE\", WRITE_DATE);\r\n");
      out.write("\t\tcomSubmit.addParam(\"ETC_GUBUN\", ETC_GUBUN);\r\n");
      out.write("\t\tcomSubmit.addParam(\"ETC_GUBUN_CONDITION\", ETC_GUBUN_CONDITION);\r\n");
      out.write("\t\tcomSubmit.submit();\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t//확진자 해외 중간 요약\r\n");
      out.write("\tfunction fn_selectConfirmMiddleOversea(INFECT_GUBUN,INFECT_DAE,WRITE_DATE){\r\n");
      out.write("\t\tvar comAjax = new ComAjax();\r\n");
      out.write("\t\tcomAjax.setUrl(\"");
      if (_jspx_meth_c_005furl_005f6(_jspx_page_context))
        return;
      out.write("\");\r\n");
      out.write("\t\tcomAjax.addParam(\"INFECT_GUBUN\",INFECT_GUBUN);\r\n");
      out.write("\t\tcomAjax.addParam(\"INFECT_DAE\",INFECT_DAE);\r\n");
      out.write("\t\tcomAjax.addParam(\"WRITE_DATE\", WRITE_DATE);\t\t\t\r\n");
      out.write("\t\tcomAjax.setCallback(\"fn_selectConfirmMiddleOverseaCallback\");\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tcomAjax.ajax();\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction fn_selectConfirmMiddleOverseaCallback(data){\r\n");
      out.write("\t\tvar total = data.total;\t\t\t\r\n");
      out.write("\t\tvar body = $(\"#mytable\");\r\n");
      out.write("\t\tvar recordcnt = $(\"#RECORD_COUNT\").val();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"#tcnt\").text(comma(total));\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tbody.empty();\r\n");
      out.write("\t\tif(total == 0){\r\n");
      out.write("\t\t\tvar str = \"<tr>\" + \r\n");
      out.write("\t\t\t\t  \"<td colspan='14' style='text-align:center;'>조회된 결과가 없습니다.</td>\" +\r\n");
      out.write("\t\t\t\t  \"</tr>\";\r\n");
      out.write("\t\t\tbody.append(str);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\telse{\r\n");
      out.write("\t\t\tvar params = {\r\n");
      out.write("\t\t\t\tdivId : \"PAGE_NAVI\",\r\n");
      out.write("\t\t\t\tpageIndex : \"PAGE_INDEX\",\r\n");
      out.write("\t\t\t\ttotalCount : total,\r\n");
      out.write("\t\t\t\trecordCount : recordcnt,\r\n");
      out.write("\t\t\t\teventName : \"fn_selectConfirmMiddleOversea\"\r\n");
      out.write("\t\t\t};\r\n");
      out.write("\t\t\tgfn_renderPaging(params);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar str = \"\";\r\n");
      out.write("\t\t\tvar t_str = \"\";\r\n");
      out.write("\t\t\tvar tr_class = \"\";\r\n");
      out.write("\t\t\tvar jsonData = null;\r\n");
      out.write("\t\t\tvar jsonStr = null;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar before_so = \"\";\r\n");
      out.write("\r\n");
      out.write("\t\t    \t   \r\n");
      out.write("\t\t    \t   \r\n");
      out.write("\t\t\t$.each(data.list, function(key, value){\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tif(typeof value.INFECT_DAE =='undefined' && typeof value.INFECT_SO =='undefined'){\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t  str += \r\n");
      out.write("\t\t\t\t\t\t     \"<thead style='background-color:#0B2161;'>  \"+\r\n");
      out.write("\t\t\t\t\t\t     \"   <tr align='center'>                     \"+\r\n");
      out.write("\t\t\t\t\t\t        \"<tr align='center'>                      \"+\r\n");
      out.write("\t\t\t\t\t\t\t\t\"<th colspan='2' style='color:#ff0000;CURSOR:hand;font-weight:bold;' onclick='go_confirmDtl(\\\"\"+value.INFECT_GUBUN+\"\\\",\\\"\\\",\\\"\\\",\\\"\"+value.WRITE_DATE+\"\\\", \\\"\\\", \\\"\\\")'>해외(\"+value.INFECT_SO_CNT+\")</th>              \"+\r\n");
      out.write("\t\t\t\t\t\t\t\t\"</tr>                                    \"+\r\n");
      out.write("\t\t\t\t\t\t        \"<tr align='center'>                      \"+\r\n");
      out.write("\t\t\t\t\t\t\t\t\"\t<th>대분류</th>                           \"+\r\n");
      out.write("\t\t\t\t\t\t\t\t\"\t<th>상세</th>                           \"+\r\n");
      out.write("\t\t\t\t\t\t\t\t\"</tr>                                    \"+\r\n");
      out.write("\t\t\t\t\t\t      \"</thead>                                  \"+\r\n");
      out.write("\t\t\t\t    \t   \"<tbody>\";\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tif(typeof value.INFECT_DAE !='undefined' && typeof value.INFECT_SO !='undefined'){\r\n");
      out.write("\t\t\t\t\tbefore_so += \"<a href='#this'  onclick='go_confirmDtl(\\\"\"+value.INFECT_GUBUN+\"\\\",\\\"\"+value.INFECT_DAE+\"\\\", \\\"\"+value.INFECT_SO+\"\\\",\\\"\"+value.WRITE_DATE+\"\\\", \\\"\\\", \\\"\\\")'>\" + value.INFECT_SO +\"(\"+value.INFECT_SO_CNT+\")</a><br>\";\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tif(typeof value.INFECT_DAE !='undefined' && typeof value.INFECT_SO =='undefined'){\r\n");
      out.write("\t\t\t\t\tstr += \r\n");
      out.write("\t\t\t\t\t\t\"<tr>                                    \" +\r\n");
      out.write("\t\t\t\t\t\t\"\t<td style='color:#a014a0;CURSOR:hand;' onclick='go_confirmDtl(\\\"\"+value.INFECT_GUBUN+\"\\\",\\\"\"+value.INFECT_DAE+\"\\\", \\\"\\\",\\\"\"+value.WRITE_DATE+\"\\\"), \\\"\\\", \\\"\\\"'>\"+value.INFECT_DAE+\"(\"+value.INFECT_SO_CNT+\")</td>                       \" +\r\n");
      out.write("\t\t\t\t\t\t\"\t<td>\"+before_so+\"</td>  \" +\r\n");
      out.write("\t\t\t\t\t\t\"</tr>                                   \"; \r\n");
      out.write("\t\t\t\t\tbefore_so = \"\";\t\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}); \r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tstr += \"</tbody>\";\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tbody.append(str);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t//확진자 중간 요약\r\n");
      out.write("\tfunction fn_selectConfirmMiddle(INFECT_GUBUN,INFECT_DAE,WRITE_DATE){\r\n");
      out.write("\t\tvar comAjax = new ComAjax();\r\n");
      out.write("\t\tcomAjax.setUrl(\"");
      if (_jspx_meth_c_005furl_005f7(_jspx_page_context))
        return;
      out.write("\");\r\n");
      out.write("\t\tcomAjax.addParam(\"INFECT_GUBUN\",INFECT_GUBUN);\r\n");
      out.write("\t\tcomAjax.addParam(\"INFECT_DAE\",INFECT_DAE);\r\n");
      out.write("\t\tcomAjax.addParam(\"WRITE_DATE\", WRITE_DATE);\t\t\t\r\n");
      out.write("\t\tcomAjax.setCallback(\"fn_selectConfirmMiddleCallback\");\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tcomAjax.ajax();\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction fn_selectConfirmMiddleCallback(data){\r\n");
      out.write("\t\tvar total = data.total;\t\t\t\r\n");
      out.write("\t\tvar body = $(\"#mytable\");\r\n");
      out.write("\t\tvar recordcnt = $(\"#RECORD_COUNT\").val();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"#tcnt\").text(comma(total));\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tbody.empty();\r\n");
      out.write("\t\tif(total == 0){\r\n");
      out.write("\t\t\tvar str = \"<tr>\" + \r\n");
      out.write("\t\t\t\t  \"<td colspan='14' style='text-align:center;'>조회된 결과가 없습니다.</td>\" +\r\n");
      out.write("\t\t\t\t  \"</tr>\";\r\n");
      out.write("\t\t\tbody.append(str);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\telse{\r\n");
      out.write("\t\t\tvar params = {\r\n");
      out.write("\t\t\t\tdivId : \"PAGE_NAVI\",\r\n");
      out.write("\t\t\t\tpageIndex : \"PAGE_INDEX\",\r\n");
      out.write("\t\t\t\ttotalCount : total,\r\n");
      out.write("\t\t\t\trecordCount : recordcnt,\r\n");
      out.write("\t\t\t\teventName : \"fn_selectConfirmMiddle\"\r\n");
      out.write("\t\t\t};\r\n");
      out.write("\t\t\tgfn_renderPaging(params);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar str = \"\";\r\n");
      out.write("\t\t\tvar t_str = \"\";\r\n");
      out.write("\t\t\tvar tr_class = \"\";\r\n");
      out.write("\t\t\tvar jsonData = null;\r\n");
      out.write("\t\t\tvar jsonStr = null;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar before_so = \"\";\r\n");
      out.write("\r\n");
      out.write("\t\t    \t   \r\n");
      out.write("\t\t    \t   \r\n");
      out.write("\t\t\t$.each(data.list, function(key, value){\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tif(typeof value.INFECT_DAE !='undefined' && typeof value.INFECT_SO =='undefined'){\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t  str += \r\n");
      out.write("\t\t\t\t\t\t     \"<thead style='background-color:#0B2161;'>  \"+\r\n");
      out.write("\t\t\t\t\t\t     \"   <tr align='center'>                     \"+\r\n");
      out.write("\t\t\t\t\t\t        \"<tr align='center'>                      \"+\r\n");
      out.write("\t\t\t\t\t\t\t\t\"<th colspan='2' style='color:#ff0000;CURSOR:hand;font-weight:bold;' onclick='go_confirmDtl(\\\"\"+value.INFECT_GUBUN+\"\\\",\\\"\"+value.INFECT_DAE+\"\\\",\\\"\\\",\\\"\"+value.WRITE_DATE+\"\\\", \\\"\\\", \\\"\\\")'>\"+value.INFECT_DAE+\"(\"+value.INFECT_SO_CNT+\")</th>              \"+\r\n");
      out.write("\t\t\t\t\t\t\t\t\"</tr>                                    \"+\r\n");
      out.write("\t\t\t\t\t\t        \"<tr align='center'>                      \"+\r\n");
      out.write("\t\t\t\t\t\t\t\t\"\t<th>대분류</th>                           \"+\r\n");
      out.write("\t\t\t\t\t\t\t\t\"\t<th>상세</th>                           \"+\r\n");
      out.write("\t\t\t\t\t\t\t\t\"</tr>                                    \"+\r\n");
      out.write("\t\t\t\t\t\t      \"</thead>                                  \"+\r\n");
      out.write("\t\t\t\t    \t   \"<tbody>\";\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tif(typeof value.INFECT_DAE !='undefined' && typeof value.INFECT_SO !='undefined'){\r\n");
      out.write("\t\t\t\t\tstr += \r\n");
      out.write("\t\t\t\t\t\t\"<tr>                                    \" +\r\n");
      out.write("\t\t\t\t\t\t\"\t<td>\"+value.INFECT_SO+\"</td>                       \" +\r\n");
      out.write("\t\t\t\t\t\t\"\t<td style='color:#0099FF;CURSOR:hand;' onclick='go_confirmDtl(\\\"\"+value.INFECT_GUBUN+\"\\\",\\\"\"+value.INFECT_DAE+\"\\\", \\\"\"+value.INFECT_SO+\"\\\",\\\"\"+value.WRITE_DATE+\"\\\"), \\\"\\\", \\\"\\\"'>\"+value.INFECT_SO_CNT+\"</td>                       \" +\r\n");
      out.write("\t\t\t\t\t\t\"</tr>                                   \"; \r\n");
      out.write("\t\t\t\t\tbefore_so = \"\";\t\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}); \r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tstr += \"</tbody>\";\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tbody.append(str);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t//확진자 병원정보 요약\r\n");
      out.write("\tfunction fn_selectConfirmMiddleHospital(INFECT_GUBUN,INFECT_DAE,WRITE_DATE){\r\n");
      out.write("\t\tvar comAjax = new ComAjax();\r\n");
      out.write("\t\tcomAjax.setUrl(\"");
      if (_jspx_meth_c_005furl_005f8(_jspx_page_context))
        return;
      out.write("\");\r\n");
      out.write("\t\tcomAjax.addParam(\"INFECT_GUBUN\",INFECT_GUBUN);\r\n");
      out.write("\t\tcomAjax.addParam(\"INFECT_DAE\",INFECT_DAE);\r\n");
      out.write("\t\tcomAjax.addParam(\"WRITE_DATE\", WRITE_DATE);\t\t\t\r\n");
      out.write("\t\tcomAjax.setCallback(\"fn_selectConfirmMiddleHospitalCallback\");\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tcomAjax.ajax();\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction fn_selectConfirmMiddleHospitalCallback(data){\r\n");
      out.write("\t\tvar total = data.total;\t\t\t\r\n");
      out.write("\t\tvar body = $(\"#mytable_hos\");\r\n");
      out.write("\t\tvar recordcnt = $(\"#RECORD_COUNT\").val();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"#tcnt\").text(comma(total));\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tbody.empty();\r\n");
      out.write("\t\tif(total == 0){\r\n");
      out.write("\t\t\tvar str = \"<tr>\" + \r\n");
      out.write("\t\t\t\t  \"<td colspan='14' style='text-align:center;'>조회된 결과가 없습니다.</td>\" +\r\n");
      out.write("\t\t\t\t  \"</tr>\";\r\n");
      out.write("\t\t\tbody.append(str);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\telse{\r\n");
      out.write("\t\t\tvar params = {\r\n");
      out.write("\t\t\t\tdivId : \"PAGE_NAVI\",\r\n");
      out.write("\t\t\t\tpageIndex : \"PAGE_INDEX\",\r\n");
      out.write("\t\t\t\ttotalCount : total,\r\n");
      out.write("\t\t\t\trecordCount : recordcnt,\r\n");
      out.write("\t\t\t\teventName : \"fn_selectConfirmMiddleHospital\"\r\n");
      out.write("\t\t\t};\r\n");
      out.write("\t\t\tgfn_renderPaging(params);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar str = \"\";\r\n");
      out.write("\t\t\tvar t_str = \"\";\r\n");
      out.write("\t\t\tvar tr_class = \"\";\r\n");
      out.write("\t\t\tvar jsonData = null;\r\n");
      out.write("\t\t\tvar jsonStr = null;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar before_so = \"\";\r\n");
      out.write("\r\n");
      out.write("\t\t    \t   \r\n");
      out.write("\t\t    \t   \r\n");
      out.write("\t\t\t$.each(data.list, function(key, value){\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tif(typeof value.HOSPITAL =='undefined'){\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t  str += \r\n");
      out.write("\t\t\t\t\t\t     \"<thead style='background-color:#0B2161;'>  \"+\r\n");
      out.write("\t\t\t\t\t\t     \"   <tr align='center'>                     \"+\r\n");
      out.write("\t\t\t\t\t\t        \"<tr align='center'>                      \"+\r\n");
      out.write("\t\t\t\t\t\t\t\t\"<th colspan='2' style='color:#ff0000;CURSOR:hand;font-weight:bold;' onclick='go_confirmDtl(\\\"\"+value.INFECT_GUBUN+\"\\\",\\\"\"+value.INFECT_DAE+\"\\\",\\\"\\\",\\\"\"+value.WRITE_DATE+\"\\\",\\\"\\\", \\\"\\\")'>입원병원(\"+value.HOSPITAL_CNT+\")</th>              \"+\r\n");
      out.write("\t\t\t\t\t\t\t\t\"</tr>                                    \"+\r\n");
      out.write("\t\t\t\t\t\t        \"<tr align='center'>                      \"+\r\n");
      out.write("\t\t\t\t\t\t\t\t\"\t<th>병원명</th>                           \"+\r\n");
      out.write("\t\t\t\t\t\t\t\t\"\t<th>입원자수</th>                           \"+\r\n");
      out.write("\t\t\t\t\t\t\t\t\"</tr>                                    \"+\r\n");
      out.write("\t\t\t\t\t\t      \"</thead>                                  \"+\r\n");
      out.write("\t\t\t\t    \t   \"<tbody>\";\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tif(typeof value.HOSPITAL !='undefined'){\r\n");
      out.write("\t\t\t\t\tstr += \r\n");
      out.write("\t\t\t\t\t\t\"<tr>                                    \" +\r\n");
      out.write("\t\t\t\t\t\t\"\t<td>\"+value.HOSPITAL+\"</td>                       \" +\r\n");
      out.write("\t\t\t\t\t\t\"\t<td style='color:#0099FF;CURSOR:hand;' onclick='go_confirmDtl(\\\"\"+value.INFECT_GUBUN+\"\\\",\\\"\"+value.INFECT_DAE+\"\\\", \\\"\\\",\\\"\"+value.WRITE_DATE+\"\\\", \\\"병원\\\", \\\"\"+value.HOSPITAL+\"\\\")'>\"+value.HOSPITAL_CNT+\"</td>  \" +\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\"</tr>                                   \"; \r\n");
      out.write("\t\t\t\t\tbefore_so = \"\";\t\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}); \r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tstr += \"</tbody>\";\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tbody.append(str);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write(" u {\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("    border-bottom: 10px solid black;\r\n");
      out.write("  }​\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div style=\"background-color:#170B3B;color:white; margin-bottom:10px; width: 100%;\">\r\n");
      out.write("\t<a href=\"#this\" class=\"btn\" id=\"logout\">\r\n");
      out.write("\t\t<img src=\"/corona/images/popup_title.gif\" align=\"absmiddle\">\r\n");
      out.write("\t</a>현황 요약 정보\r\n");
      out.write("\t\r\n");
      out.write("\t<div style=\"padding-right:10px;padding-top:7px;float:right;\">\r\n");
      out.write("\t\t<a href=\"/corona/status/mainStatusView.do\" class=\"btn btn-success\" id=\"statistics\"><i class=\"fa fa-reply\"></i> 코로나19 현황</a>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\t<div align=\"center\" style=\"width:400;margin-left:15px;float:left;\">\r\n");
      out.write("\t\t<div class=\"table-responsive m-b-40\">\r\n");
      out.write("\t\t\t <table class=\"table table-bordered table-data3\" style=\"text-align:center;\" id=\"mytable\">\r\n");
      out.write("\t\t      </table>\r\n");
      out.write("\t      </div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div align=\"center\" style=\"width:400;margin-left:15px;float:left;\">\r\n");
      out.write("\t\t<div class=\"table-responsive m-b-40\">\r\n");
      out.write("\t\t\t <table class=\"table table-bordered table-data3\" style=\"text-align:center;\" id=\"mytable_hos\">\r\n");
      out.write("\t\t      </table>\r\n");
      out.write("\t      </div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<table style=\"width:100%;height:500px;font-size:40px;vertical-align:middle;margin-top:30px;margin-bottom:30px;border:2px solid gray;\">\r\n");
      out.write("<tr>\r\n");
      out.write("<td align=\"center\">\r\n");
      out.write("지도영역\r\n");
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("</div>\t\r\n");
      out.write("\r\n");
      out.write("<form id=\"commonForm\" name=\"commonForm\"></form>");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f0.setParent(null);
    // /WEB-INF/include/include-header.jspf(71,36) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f0.setValue("/js/jquery.min.js");
    int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
    if (_jspx_th_c_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f1 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f1.setParent(null);
    // /WEB-INF/include/include-header.jspf(72,36) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f1.setValue("/js/jquery-ui.js");
    int _jspx_eval_c_005furl_005f1 = _jspx_th_c_005furl_005f1.doStartTag();
    if (_jspx_th_c_005furl_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f1);
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f2 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f2.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f2.setParent(null);
    // /WEB-INF/include/include-header.jspf(73,36) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f2.setValue("/js/jquery.cookie.js");
    int _jspx_eval_c_005furl_005f2 = _jspx_th_c_005furl_005f2.doStartTag();
    if (_jspx_th_c_005furl_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f2);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f2);
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f3 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f3.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f3.setParent(null);
    // /WEB-INF/include/include-header.jspf(74,36) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f3.setValue("/js/jquery.form.js");
    int _jspx_eval_c_005furl_005f3 = _jspx_th_c_005furl_005f3.doStartTag();
    if (_jspx_th_c_005furl_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f3);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f3);
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f4 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f4.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f4.setParent(null);
    // /WEB-INF/include/include-header.jspf(75,13) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f4.setValue("/js/common.js");
    int _jspx_eval_c_005furl_005f4 = _jspx_th_c_005furl_005f4.doStartTag();
    if (_jspx_th_c_005furl_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f4);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f4);
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f5(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f5 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f5.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f5.setParent(null);
    // /WEB-INF/jsp/status/statusAccumMiddleView.jsp(34,20) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f5.setValue("/status/statusTrackingView.do");
    int _jspx_eval_c_005furl_005f5 = _jspx_th_c_005furl_005f5.doStartTag();
    if (_jspx_th_c_005furl_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f5);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f5);
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f6(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f6 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f6.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f6.setParent(null);
    // /WEB-INF/jsp/status/statusAccumMiddleView.jsp(48,18) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f6.setValue("/status/selectConfirmMiddleOversea.do");
    int _jspx_eval_c_005furl_005f6 = _jspx_th_c_005furl_005f6.doStartTag();
    if (_jspx_th_c_005furl_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f6);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f6);
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f7(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f7 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f7.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f7.setParent(null);
    // /WEB-INF/jsp/status/statusAccumMiddleView.jsp(133,18) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f7.setValue("/status/selectConfirmMiddleOversea.do");
    int _jspx_eval_c_005furl_005f7 = _jspx_th_c_005furl_005f7.doStartTag();
    if (_jspx_th_c_005furl_005f7.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f7);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f7);
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f8(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f8 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f8.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f8.setParent(null);
    // /WEB-INF/jsp/status/statusAccumMiddleView.jsp(215,18) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f8.setValue("/status/selectConfirmMiddleHospital.do");
    int _jspx_eval_c_005furl_005f8 = _jspx_th_c_005furl_005f8.doStartTag();
    if (_jspx_th_c_005furl_005f8.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f8);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f8);
    return false;
  }
}
