/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.24
 * Generated at: 2020-10-05 23:56:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.status;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class statusMiddleTotalView_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(6);
    _jspx_dependants.put("jar:file:/C:/dev/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp15/wtpwebapps/corona/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/C:/dev/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp15/wtpwebapps/corona/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/include/include-body.jspf", Long.valueOf(1595128796000L));
    _jspx_dependants.put("jar:file:/C:/dev/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp15/wtpwebapps/corona/WEB-INF/lib/jstl-1.2.jar!/META-INF/fn.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1595463255549L));
    _jspx_dependants.put("/WEB-INF/include/include-header.jspf", Long.valueOf(1599786548129L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Fontfaces CSS-->\r\n");
      out.write("<link href=\"/corona/bootstrap/css/font-face.css\" rel=\"stylesheet\" media=\"all\">\r\n");
      out.write("<link href=\"/corona/bootstrap/vendor/font-awesome-4.7/css/font-awesome.min.css\" rel=\"stylesheet\" media=\"all\">\r\n");
      out.write("<link href=\"/corona/bootstrap/vendor/font-awesome-5/css/fontawesome-all.min.css\" rel=\"stylesheet\" media=\"all\">\r\n");
      out.write("<link href=\"/corona/bootstrap/vendor/mdi-font/css/material-design-iconic-font.min.css\" rel=\"stylesheet\" media=\"all\">\r\n");
      out.write("\r\n");
      out.write("<!-- Bootstrap CSS-->\r\n");
      out.write("<link href=\"/corona/bootstrap/vendor/bootstrap-4.1/bootstrap.min.css\" rel=\"stylesheet\" media=\"all\">\r\n");
      out.write("\r\n");
      out.write("<!-- Vendor CSS-->\r\n");
      out.write("<link href=\"/corona/bootstrap/vendor/animsition/animsition.min.css\" rel=\"stylesheet\" media=\"all\">\r\n");
      out.write("<link href=\"/corona/bootstrap/vendor/bootstrap-progressbar/bootstrap-progressbar-3.3.4.min.css\" rel=\"stylesheet\" media=\"all\">\r\n");
      out.write("<link href=\"/corona/bootstrap/vendor/wow/animate.css\" rel=\"stylesheet\" media=\"all\">\r\n");
      out.write("<link href=\"/corona/bootstrap/vendor/css-hamburgers/hamburgers.min.css\" rel=\"stylesheet\" media=\"all\">\r\n");
      out.write("<link href=\"/corona/bootstrap/vendor/slick/slick.css\" rel=\"stylesheet\" media=\"all\">\r\n");
      out.write("<link href=\"/corona/bootstrap/vendor/select2/select2.min.css\" rel=\"stylesheet\" media=\"all\">\r\n");
      out.write("<link href=\"/corona/bootstrap/vendor/perfect-scrollbar/perfect-scrollbar.css\" rel=\"stylesheet\" media=\"all\">\r\n");
      out.write("\r\n");
      out.write("<!-- Main CSS-->\r\n");
      out.write("<link href=\"/corona/bootstrap/css/theme.css\" rel=\"stylesheet\" media=\"all\">\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Jquery JS-->\r\n");
      out.write("<script src=\"/corona/bootstrap/vendor/jquery-3.2.1.min.js\"></script>\r\n");
      out.write("<!-- Bootstrap JS-->\r\n");
      out.write("<script src=\"/corona/bootstrap/vendor/bootstrap-4.1/popper.min.js\"></script>\r\n");
      out.write("<script src=\"/corona/bootstrap/vendor/bootstrap-4.1/bootstrap.min.js\"></script>\r\n");
      out.write("<!-- Vendor JS       -->\r\n");
      out.write("<script src=\"/corona/bootstrap/vendor/slick/slick.min.js\">\r\n");
      out.write("</script>\r\n");
      out.write("<script src=\"/corona/bootstrap/vendor/wow/wow.min.js\"></script>\r\n");
      out.write("<script src=\"/corona/bootstrap/vendor/animsition/animsition.min.js\"></script>\r\n");
      out.write("<script src=\"/corona/bootstrap/vendor/bootstrap-progressbar/bootstrap-progressbar.min.js\">\r\n");
      out.write("</script>\r\n");
      out.write("<script src=\"/corona/bootstrap/vendor/counter-up/jquery.waypoints.min.js\"></script>\r\n");
      out.write("<script src=\"/corona/bootstrap/vendor/counter-up/jquery.counterup.min.js\">\r\n");
      out.write("</script>\r\n");
      out.write("<script src=\"/corona/bootstrap/vendor/circle-progress/circle-progress.min.js\"></script>\r\n");
      out.write("<script src=\"/corona/bootstrap/vendor/perfect-scrollbar/perfect-scrollbar.js\"></script>\r\n");
      out.write("<script src=\"/corona/bootstrap/vendor/chartjs/Chart.bundle.min.js\"></script>\r\n");
      out.write("<script src=\"/corona/bootstrap/vendor/select2/select2.min.js\">\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<!-- Main JS-->\r\n");
      out.write("<script src=\"/corona/bootstrap/js/main.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- alert -->\r\n");
      out.write("<script src=\"/corona/jquery.modal-master/js/DesignAlert.js\"></script>\r\n");
      out.write("<script src=\"/corona/jquery.modal-master/js/jquery.modal.js\"></script>\r\n");
      out.write("<script src=\"/corona/jquery.modal-master/js/jquery.modal.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<link href=\"/corona/jquery.modal-master/css/jquery.modal.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"/corona/jquery.modal-master/css/jquery.modal.theme-atlant.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"/corona/jquery.modal-master/css/jquery.modal.theme-xenon.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- jQuery -->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/corona/css/jquery-ui.css\" />\r\n");
      out.write("<!-- <script src=\"http://code.jquery.com/jquery.min.js\"></script>-->\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      if (_jspx_meth_c_005furl_005f0(_jspx_page_context))
        return;
      out.write("\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      if (_jspx_meth_c_005furl_005f1(_jspx_page_context))
        return;
      out.write("\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      if (_jspx_meth_c_005furl_005f2(_jspx_page_context))
        return;
      out.write("\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      if (_jspx_meth_c_005furl_005f3(_jspx_page_context))
        return;
      out.write("\"></script>\r\n");
      out.write("<script src=\"");
      if (_jspx_meth_c_005furl_005f4(_jspx_page_context))
        return;
      out.write("\" charset=\"utf-8\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- \r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/corona/css/common.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/corona/css/import.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/corona/css/skin01.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/corona/css/corona.css\" />\r\n");
      out.write(" -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"https://www.gstatic.com/charts/loader.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tvar user_right = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.userinfo.userright}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\r\n");
      out.write("\r\n");
      out.write("\t$(document).ready(function() {\r\n");
      out.write("\t\t//총괄\r\n");
      out.write("\t\tvar totalStatisticList=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${totalStatisticList}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//구글차트 그리기\r\n");
      out.write("\t\tgoogle.charts.load('current', {'packages':['line','controls']});\r\n");
      out.write("\t\tchartTotalDrow(totalStatisticList); //chartDrow() 실행\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tchartTotalIchupDrow(totalStatisticList); //chartDrow() 실행\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tchartTasiguTotalDrow(totalStatisticList); //chartDrow() 실행\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t//총괄차트 그리기\r\n");
      out.write("  function chartTotalDrow(totalStatisticList){\r\n");
      out.write("    var chartData = '';\r\n");
      out.write("\r\n");
      out.write("    //날짜형식 변경하고 싶으시면 이 부분 수정하세요.\r\n");
      out.write("    var chartDateformat     = 'yyyy년MM월dd일';\r\n");
      out.write("    //라인차트의 라인 수\r\n");
      out.write("    var chartLineCount    = 15;\r\n");
      out.write("    //컨트롤러 바 차트의 라인 수\r\n");
      out.write("    var controlLineCount    = 10;\r\n");
      out.write("\r\n");
      out.write("    function drawDashboard() {\r\n");
      out.write("      var data = new google.visualization.DataTable();\r\n");
      out.write("      //그래프에 표시할 컬럼 추가\r\n");
      out.write("      data.addColumn('datetime' , '날짜');\r\n");
      out.write("      data.addColumn('number'   , '누적 확진자');\r\n");
      out.write("      data.addColumn('number'   , '누적 완치자');\r\n");
      out.write("      data.addColumn('number'   , '치료중인자');\r\n");
      out.write("      data.addColumn('number'   , '사망자');\r\n");
      out.write("      //그래프에 표시할 데이터\r\n");
      out.write("      var dataRow = [];\r\n");
      out.write("  \t\r\n");
      out.write("  \t");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("  \t\r\n");
      out.write("\r\n");
      out.write("        var chart = new google.visualization.ChartWrapper({\r\n");
      out.write("          chartType   : 'LineChart',\r\n");
      out.write("          containerId : 'lineChartArea', //라인 차트 생성할 영역\r\n");
      out.write("          options     : {\r\n");
      out.write("                          isStacked   : 'percent',\r\n");
      out.write("                          focusTarget : 'category',\r\n");
      out.write("                          height          : 300,\r\n");
      out.write("                          width              : '100%',\r\n");
      out.write("                          legend          : { position: \"top\", textStyle: {fontSize: 13}},\r\n");
      out.write("                          pointSize        : 5,\r\n");
      out.write("                          tooltip          : {textStyle : {fontSize:12}, showColorCode : true,trigger: 'both'},\r\n");
      out.write("                          hAxis              : {format: chartDateformat, gridlines:{count:chartLineCount,units: {\r\n");
      out.write("                                                              years : {format: ['yyyy년']},\r\n");
      out.write("                                                              months: {format: ['MM월']},\r\n");
      out.write("                                                              days  : {format: ['dd일']},\r\n");
      out.write("                                                              hours : {format: ['HH시']}}\r\n");
      out.write("                                                            },textStyle: {fontSize:12}},\r\n");
      out.write("\t\t\t\t\t\tvAxis              : {\r\n");
      out.write("                                   \t             \t\t\t\tminValue: 1,\r\n");
      out.write("                                   \t             \t\t\t\tviewWindow:{min:0},\r\n");
      out.write("                                   \t             \t\t\t\tgridlines:{count:8},\r\n");
      out.write("                                   \t             \t\t\t\ttextStyle:{fontSize:12}\r\n");
      out.write("                                   \t             \t\t\t\t},\r\n");
      out.write("            animation        : {startup: true,duration: 1000,easing: 'in' },\r\n");
      out.write("            annotations    : {pattern: chartDateformat,\r\n");
      out.write("                            textStyle: {\r\n");
      out.write("                            fontSize: 15,\r\n");
      out.write("                            bold: true,\r\n");
      out.write("                            italic: true,\r\n");
      out.write("                            color: '#871b47',\r\n");
      out.write("                            auraColor: '#d799ae',\r\n");
      out.write("                            opacity: 0.8,\r\n");
      out.write("                            pattern: chartDateformat\r\n");
      out.write("                          }\r\n");
      out.write("                        }\r\n");
      out.write("          }\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        var control = new google.visualization.ControlWrapper({\r\n");
      out.write("          controlType: 'ChartRangeFilter',\r\n");
      out.write("          containerId: 'controlsArea',  //control bar를 생성할 영역\r\n");
      out.write("          options: {\r\n");
      out.write("              ui:{\r\n");
      out.write("                    chartType: 'LineChart',\r\n");
      out.write("                    chartOptions: {\r\n");
      out.write("                    chartArea: {'width': '60%','height' : 40},\r\n");
      out.write("                      hAxis: {'baselineColor': 'none', format: chartDateformat, textStyle: {fontSize:12},\r\n");
      out.write("                        gridlines:{count:controlLineCount,units: {\r\n");
      out.write("                              years : {format: ['yyyy년']},\r\n");
      out.write("                              months: {format: ['MM월']},\r\n");
      out.write("                              days  : {format: ['dd일']},\r\n");
      out.write("                              hours : {format: ['HH시']}}\r\n");
      out.write("                        }}\r\n");
      out.write("                    }\r\n");
      out.write("              },\r\n");
      out.write("                filterColumnIndex: 0\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        var date_formatter = new google.visualization.DateFormat({ pattern: chartDateformat});\r\n");
      out.write("        date_formatter.format(data, 0);\r\n");
      out.write("\r\n");
      out.write("        var dashboard = new google.visualization.Dashboard(document.getElementById('Line_Controls_Chart'));\r\n");
      out.write("        window.addEventListener('resize', function() { dashboard.draw(data); }, false); //화면 크기에 따라 그래프 크기 변경\r\n");
      out.write("        dashboard.bind([control], [chart]);\r\n");
      out.write("        dashboard.draw(data);\r\n");
      out.write("\r\n");
      out.write("    }\r\n");
      out.write("      google.charts.setOnLoadCallback(drawDashboard);\r\n");
      out.write("\r\n");
      out.write("  }\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t//총괄 이첩 차트 그리기\r\n");
      out.write("  function chartTotalIchupDrow(totalStatisticList){\r\n");
      out.write("    var chartData = '';\r\n");
      out.write("\r\n");
      out.write("    //날짜형식 변경하고 싶으시면 이 부분 수정하세요.\r\n");
      out.write("    var chartDateformat     = 'yyyy년MM월dd일';\r\n");
      out.write("    //라인차트의 라인 수\r\n");
      out.write("    var chartLineCount    = 15;\r\n");
      out.write("    //컨트롤러 바 차트의 라인 수\r\n");
      out.write("    var controlLineCount    = 10;\r\n");
      out.write("\r\n");
      out.write("    function drawDashboard() {\r\n");
      out.write("      var data = new google.visualization.DataTable();\r\n");
      out.write("      //그래프에 표시할 컬럼 추가\r\n");
      out.write("      data.addColumn('datetime' , '날짜');\r\n");
      out.write("      data.addColumn('number'   , '누적 확진자');\r\n");
      out.write("      data.addColumn('number'   , '누적 완치자');\r\n");
      out.write("      data.addColumn('number'   , '치료중인자');\r\n");
      out.write("      data.addColumn('number'   , '사망자');\r\n");
      out.write("      //그래프에 표시할 데이터\r\n");
      out.write("      var dataRow = [];\r\n");
      out.write("  \t\r\n");
      out.write("  \t");
      if (_jspx_meth_c_005fforEach_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("  \t\r\n");
      out.write("\r\n");
      out.write("        var chart = new google.visualization.ChartWrapper({\r\n");
      out.write("          chartType   : 'LineChart',\r\n");
      out.write("          containerId : 'lineChartIchupArea', //라인 차트 생성할 영역\r\n");
      out.write("          options     : {\r\n");
      out.write("                          isStacked   : 'percent',\r\n");
      out.write("                          focusTarget : 'category',\r\n");
      out.write("                          height          : 300,\r\n");
      out.write("                          width              : '100%',\r\n");
      out.write("                          legend          : { position: \"top\", textStyle: {fontSize: 13}},\r\n");
      out.write("                          pointSize        : 5,\r\n");
      out.write("                          tooltip          : {textStyle : {fontSize:12}, showColorCode : true,trigger: 'both'},\r\n");
      out.write("                          hAxis              : {format: chartDateformat, gridlines:{count:chartLineCount,units: {\r\n");
      out.write("                                                              years : {format: ['yyyy년']},\r\n");
      out.write("                                                              months: {format: ['MM월']},\r\n");
      out.write("                                                              days  : {format: ['dd일']},\r\n");
      out.write("                                                              hours : {format: ['HH시']}}\r\n");
      out.write("                                                            },textStyle: {fontSize:12}},\r\n");
      out.write("\t\t\t\t\t\tvAxis              : {\r\n");
      out.write("                                   \t             \t\t\t\tminValue: 1,\r\n");
      out.write("                                   \t             \t\t\t\tviewWindow:{min:0},\r\n");
      out.write("                                   \t             \t\t\t\tgridlines:{count:8},\r\n");
      out.write("                                   \t             \t\t\t\ttextStyle:{fontSize:12}\r\n");
      out.write("                                   \t             \t\t\t\t},\r\n");
      out.write("            animation        : {startup: true,duration: 1000,easing: 'in' },\r\n");
      out.write("            annotations    : {pattern: chartDateformat,\r\n");
      out.write("                            textStyle: {\r\n");
      out.write("                            fontSize: 15,\r\n");
      out.write("                            bold: true,\r\n");
      out.write("                            italic: true,\r\n");
      out.write("                            color: '#871b47',\r\n");
      out.write("                            auraColor: '#d799ae',\r\n");
      out.write("                            opacity: 0.8,\r\n");
      out.write("                            pattern: chartDateformat\r\n");
      out.write("                          }\r\n");
      out.write("                        }\r\n");
      out.write("          }\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        var control = new google.visualization.ControlWrapper({\r\n");
      out.write("          controlType: 'ChartRangeFilter',\r\n");
      out.write("          containerId: 'controlsIchupArea',  //control bar를 생성할 영역\r\n");
      out.write("          options: {\r\n");
      out.write("              ui:{\r\n");
      out.write("                    chartType: 'LineChart',\r\n");
      out.write("                    chartOptions: {\r\n");
      out.write("                    chartArea: {'width': '60%','height' : 40},\r\n");
      out.write("                      hAxis: {'baselineColor': 'none', format: chartDateformat, textStyle: {fontSize:12},\r\n");
      out.write("                        gridlines:{count:controlLineCount,units: {\r\n");
      out.write("                              years : {format: ['yyyy년']},\r\n");
      out.write("                              months: {format: ['MM월']},\r\n");
      out.write("                              days  : {format: ['dd일']},\r\n");
      out.write("                              hours : {format: ['HH시']}}\r\n");
      out.write("                        }}\r\n");
      out.write("                    }\r\n");
      out.write("              },\r\n");
      out.write("                filterColumnIndex: 0\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        var date_formatter = new google.visualization.DateFormat({ pattern: chartDateformat});\r\n");
      out.write("        date_formatter.format(data, 0);\r\n");
      out.write("\r\n");
      out.write("        var dashboard = new google.visualization.Dashboard(document.getElementById('Line_Controls_Ichup_Chart'));\r\n");
      out.write("        window.addEventListener('resize', function() { dashboard.draw(data); }, false); //화면 크기에 따라 그래프 크기 변경\r\n");
      out.write("        dashboard.bind([control], [chart]);\r\n");
      out.write("        dashboard.draw(data);\r\n");
      out.write("\r\n");
      out.write("    }\r\n");
      out.write("      google.charts.setOnLoadCallback(drawDashboard);\r\n");
      out.write("\r\n");
      out.write("  }\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("//타시구 총괄차트 그리기\r\n");
      out.write("  function chartTasiguTotalDrow(totalStatisticList){\r\n");
      out.write("    var chartData = '';\r\n");
      out.write("\r\n");
      out.write("    //날짜형식 변경하고 싶으시면 이 부분 수정하세요.\r\n");
      out.write("    var chartDateformat     = 'yyyy년MM월dd일';\r\n");
      out.write("    //라인차트의 라인 수\r\n");
      out.write("    var chartLineCount    = 15;\r\n");
      out.write("    //컨트롤러 바 차트의 라인 수\r\n");
      out.write("    var controlLineCount    = 10;\r\n");
      out.write("\r\n");
      out.write("    function drawDashboard() {\r\n");
      out.write("      var data = new google.visualization.DataTable();\r\n");
      out.write("      //그래프에 표시할 컬럼 추가\r\n");
      out.write("      data.addColumn('datetime' , '날짜');\r\n");
      out.write("      data.addColumn('number'   , '누적 확진자');\r\n");
      out.write("      //그래프에 표시할 데이터\r\n");
      out.write("      var dataRow = [];\r\n");
      out.write("  \t\r\n");
      out.write("  \t");
      if (_jspx_meth_c_005fforEach_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("  \t\r\n");
      out.write("\r\n");
      out.write("        var chart = new google.visualization.ChartWrapper({\r\n");
      out.write("          chartType   : 'LineChart',\r\n");
      out.write("          containerId : 'lineChartTasiguArea', //라인 차트 생성할 영역\r\n");
      out.write("          options     : {\r\n");
      out.write("                          isStacked   : 'percent',\r\n");
      out.write("                          focusTarget : 'category',\r\n");
      out.write("                          height          : 300,\r\n");
      out.write("                          width              : '100%',\r\n");
      out.write("                          legend          : { position: \"top\", textStyle: {fontSize: 13}},\r\n");
      out.write("                          pointSize        : 5,\r\n");
      out.write("                          tooltip          : {textStyle : {fontSize:12}, showColorCode : true,trigger: 'both'},\r\n");
      out.write("                          hAxis              : {format: chartDateformat, gridlines:{count:chartLineCount,units: {\r\n");
      out.write("                                                              years : {format: ['yyyy년']},\r\n");
      out.write("                                                              months: {format: ['MM월']},\r\n");
      out.write("                                                              days  : {format: ['dd일']},\r\n");
      out.write("                                                              hours : {format: ['HH시']}}\r\n");
      out.write("                                                            },textStyle: {fontSize:12}},\r\n");
      out.write("\t\t\t\t\t\tvAxis              : {\r\n");
      out.write("                                   \t             \t\t\t\tminValue: 1,\r\n");
      out.write("                                   \t             \t\t\t\tviewWindow:{min:0},\r\n");
      out.write("                                   \t             \t\t\t\tgridlines:{count:8},\r\n");
      out.write("                                   \t             \t\t\t\ttextStyle:{fontSize:12}\r\n");
      out.write("                                   \t             \t\t\t\t},\r\n");
      out.write("            animation        : {startup: true,duration: 1000,easing: 'in' },\r\n");
      out.write("            annotations    : {pattern: chartDateformat,\r\n");
      out.write("                            textStyle: {\r\n");
      out.write("                            fontSize: 15,\r\n");
      out.write("                            bold: true,\r\n");
      out.write("                            italic: true,\r\n");
      out.write("                            color: '#871b47',\r\n");
      out.write("                            auraColor: '#d799ae',\r\n");
      out.write("                            opacity: 0.8,\r\n");
      out.write("                            pattern: chartDateformat\r\n");
      out.write("                          }\r\n");
      out.write("                        }\r\n");
      out.write("          }\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        var control = new google.visualization.ControlWrapper({\r\n");
      out.write("          controlType: 'ChartRangeFilter',\r\n");
      out.write("          containerId: 'controlsTasiguArea',  //control bar를 생성할 영역\r\n");
      out.write("          options: {\r\n");
      out.write("              ui:{\r\n");
      out.write("                    chartType: 'LineChart',\r\n");
      out.write("                    chartOptions: {\r\n");
      out.write("                    chartArea: {'width': '60%','height' : 40},\r\n");
      out.write("                      hAxis: {'baselineColor': 'none', format: chartDateformat, textStyle: {fontSize:12},\r\n");
      out.write("                        gridlines:{count:controlLineCount,units: {\r\n");
      out.write("                              years : {format: ['yyyy년']},\r\n");
      out.write("                              months: {format: ['MM월']},\r\n");
      out.write("                              days  : {format: ['dd일']},\r\n");
      out.write("                              hours : {format: ['HH시']}}\r\n");
      out.write("                        }}\r\n");
      out.write("                    }\r\n");
      out.write("              },\r\n");
      out.write("                filterColumnIndex: 0\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        var date_formatter = new google.visualization.DateFormat({ pattern: chartDateformat});\r\n");
      out.write("        date_formatter.format(data, 0);\r\n");
      out.write("\r\n");
      out.write("        var dashboard = new google.visualization.Dashboard(document.getElementById('Line_Controls_Tasigu_Chart'));\r\n");
      out.write("        window.addEventListener('resize', function() { dashboard.draw(data); }, false); //화면 크기에 따라 그래프 크기 변경\r\n");
      out.write("        dashboard.bind([control], [chart]);\r\n");
      out.write("        dashboard.draw(data);\r\n");
      out.write("\r\n");
      out.write("    }\r\n");
      out.write("      google.charts.setOnLoadCallback(drawDashboard);\r\n");
      out.write("\r\n");
      out.write("  }\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t//확진자 요약 상세\r\n");
      out.write("\tfunction go_confirmTotalDtl(TOTAL_GUBUN,TOTAL_CONDITION,TOTAL_ICHUP,TOTAL_DONG_GUBUN,WRITE_DATE){\r\n");
      out.write(" \t\tvar comSubmit = new ComSubmit();\r\n");
      out.write("\t\tcomSubmit.setUrl(\"");
      if (_jspx_meth_c_005furl_005f5(_jspx_page_context))
        return;
      out.write("\");\r\n");
      out.write("\t\tcomSubmit.addParam(\"TOTAL_GUBUN\", TOTAL_GUBUN);\r\n");
      out.write("\t\tcomSubmit.addParam(\"TOTAL_CONDITION\", TOTAL_CONDITION);\r\n");
      out.write("\t\tcomSubmit.addParam(\"TOTAL_ICHUP\", TOTAL_ICHUP);\r\n");
      out.write("\t\tcomSubmit.addParam(\"TOTAL_DONG_GUBUN\", TOTAL_DONG_GUBUN);\r\n");
      out.write("\t\tcomSubmit.addParam(\"WRITE_DATE\", WRITE_DATE);\r\n");
      out.write("\t\tcomSubmit.submit();\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write(" u {\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("    border-bottom: 10px solid black;\r\n");
      out.write("  }​\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div style=\"background-color:#170B3B;color:white; margin-bottom:10px; width: 100%;\">\r\n");
      out.write("\t<a href=\"#this\" class=\"btn\" id=\"logout\">\r\n");
      out.write("\t\t<img src=\"/corona/images/popup_title.gif\" align=\"absmiddle\">\r\n");
      out.write("\t</a>현황 요약 정보\r\n");
      out.write("\t\r\n");
      out.write("\t<div style=\"padding-right:10px;padding-top:7px;float:right;\">\r\n");
      out.write("\t\t<a href=\"/corona/status/mainStatusView.do\" class=\"btn btn-success\" id=\"statistics\"><i class=\"fa fa-reply\"></i> 코로나19 현황</a>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t<div align=\"left\"  style='padding-left:20px;' id=\"total_table\">\r\n");
      out.write("\t\t<!-- 당일 테이블 -->\r\n");
      out.write("\t\t<div class=\"table-responsive m-b-40\">\r\n");
      out.write("\t\t\t<table class=\"table table-bordered table-data3\" style='width: 400;float:left;'>\r\n");
      out.write("\t\t\t\t<thead style='background-color:#0B2161;'>\r\n");
      out.write("\t\t\t\t\t<tr align='center' style='background-color:#088A85;'>\r\n");
      out.write("\t\t\t\t\t\t<th colspan='4'>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${WRITE_DATE}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write('(');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${totalSum.TODAY_CNT}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(")</th>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr align='center'>\r\n");
      out.write("\t\t\t\t\t\t<th colspan='4' style='CURSOR:hand;font-weight:bold;' onclick=\"go_confirmTotalDtl('강남구','','','','");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${WRITE_DATE}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("')\">강남구거주자수(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${totalSum.TODAY_GANGNAM_CNT}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(")</th>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr align='center'>\r\n");
      out.write("\t\t\t\t\t\t<th>강남구동</th>\r\n");
      out.write("\t\t\t\t\t\t<th>완치자수(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${totalSum.TODAY_GANGNAM_CURED_CNT}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(")</th>\r\n");
      out.write("\t\t\t\t\t\t<th>치료자수(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${totalSum.TODAY_GANGNAM_CURING_CNT}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(")</th>\r\n");
      out.write("\t\t\t\t\t\t<th>사망자수(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${totalSum.TODAY_GANGNAM_DEATH_CNT}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(")</th>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t");
      if (_jspx_meth_c_005fforEach_005f3(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t\t<table class=\"table table-bordered table-data3\" style='width: 300;float:left;'>\r\n");
      out.write("\t\t\t\t<thead style='background-color:#0B2161;'>\r\n");
      out.write("\t\t\t\t\t<tr align='center' style='background-color:white;'>\r\n");
      out.write("\t\t\t\t\t\t<th colspan='2'>높이</th>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr align='center'>\r\n");
      out.write("\t\t\t\t\t\t<th colspan='2' style='CURSOR:hand;font-weight:bold;background-color:#22741C;' onclick=\"go_confirmTotalDtl('타지역','','','','");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${WRITE_DATE}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("')\">타구거주자수(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${totalSum.TODAY_TASIGU_CNT}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(")</th>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr align='center'>\r\n");
      out.write("\t\t\t\t\t\t<th style='background-color:#22741C;'>타시구</th>\r\n");
      out.write("\t\t\t\t\t\t<th style='background-color:#22741C;'>확진자수</th>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t");
      if (_jspx_meth_c_005fforEach_005f4(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!-- 누적   -->\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!-- 강남구민 -->\r\n");
      out.write("\t\t<div class=\"table-responsive m-b-40\">\r\n");
      out.write("\t\t\t<table class=\"table table-bordered table-data3\" style='width: 400;float:left;'>\r\n");
      out.write("\t\t\t\t<thead style='background-color:#0B2161;'>\r\n");
      out.write("\t\t\t\t\t<tr align='center' style='background-color:#ffc314;'>\r\n");
      out.write("\t\t\t\t\t\t<th colspan='4' style='color:#ff0000;font-weight:bold;' onclick=\"go_confirmTotalDtl('','','','','')\">누적(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${totalSum.ACCUM_CNT}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(")</th>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr align='center'>\r\n");
      out.write("\t\t\t\t\t\t<th colspan='4' style='CURSOR:hand;font-weight:bold;'  onclick=\"go_confirmTotalDtl('강남구','','N','','')\">강남구확진판정자수(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${totalSum.ACCUM_GANGNAM_CNT}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(")</th>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr align='center'>\r\n");
      out.write("\t\t\t\t\t\t<th>강남구동</th>\r\n");
      out.write("\t\t\t\t\t\t<th>완치자수(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${totalSum.ACCUM_GANGNAM_CURED_CNT}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(")</th>\r\n");
      out.write("\t\t\t\t\t\t<th>치료자수(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${totalSum.ACCUM_GANGNAM_CURING_CNT}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(")</th>\r\n");
      out.write("\t\t\t\t\t\t<th>사망자수(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${totalSum.ACCUM_GANGNAM_DEATH_CNT}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(")</th>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t");
      if (_jspx_meth_c_005fforEach_005f5(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<!-- 이첩 -->\r\n");
      out.write("\t\t\t<table class=\"table table-bordered table-data3\" style='width: 400;float:left;'>\r\n");
      out.write("\t\t\t\t<thead style='background-color:#0B2161;'>\r\n");
      out.write("\t\t\t\t\t<tr align='center' style='background-color:white;'>\r\n");
      out.write("\t\t\t\t\t\t<th colspan='4'>높이</th>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr align='center'>\r\n");
      out.write("\t\t\t\t\t\t<th colspan='4' style='CURSOR:hand;font-weight:bold;'  onclick=\"go_confirmTotalDtl('강남구','','Y','','')\">타시구에서 이첩자수(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${totalSum.ACCUM_GANGNAM_ICHUP_CNT}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(")</th>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr align='center'>\r\n");
      out.write("\t\t\t\t\t\t<th>강남구동</th>\r\n");
      out.write("\t\t\t\t\t\t<th>완치자수(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${totalSum.ACCUM_GANGNAM_ICHUP_CURED_CNT}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(")</th>\r\n");
      out.write("\t\t\t\t\t\t<th>치료자수(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${totalSum.ACCUM_GANGNAM_ICHUP_CURING_CNT}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(")</th>\r\n");
      out.write("\t\t\t\t\t\t<th>사망자수(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${totalSum.ACCUM_GANGNAM_ICHUP_DEATH_CNT}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(")</th>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t");
      if (_jspx_meth_c_005fforEach_005f6(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<!-- 타시구민 -->\r\n");
      out.write("\t\t\t<table class=\"table table-bordered table-data3\" style='width: 300;float:left;'>\r\n");
      out.write("\t\t\t\t<thead style='background-color:#0B2161;'>\r\n");
      out.write("\t\t\t\t\t<tr align='center' style='background-color:white;'>\r\n");
      out.write("\t\t\t\t\t\t<th colspan='2'>높이</th>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr align='center'>\r\n");
      out.write("\t\t\t\t\t\t<th colspan='2' style='CURSOR:hand;font-weight:bold;background-color:#22741C;'  onclick=\"go_confirmTotalDtl('타지역','','','','')\">타시구거주자수(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${totalSum.ACCUM_TASIGU_CNT}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(")</th>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr align='center'>\r\n");
      out.write("\t\t\t\t\t\t<th style='background-color:#22741C;'>타시구</th>\r\n");
      out.write("\t\t\t\t\t\t<th style='background-color:#22741C;'>확진자수</th>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t");
      if (_jspx_meth_c_005fforEach_005f7(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\t<br>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- 그래프 -->\r\n");
      out.write("\t<div style=\"width:100%;height:450px;padding-left:40px;\" id=\"chartArea\">\r\n");
      out.write("\t    <h4 id=\"graphTitle\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[강남구민 확진판정자 변동 현황]</h4>\r\n");
      out.write(" \r\n");
      out.write("    \t<div id=\"Line_Controls_Chart\">\r\n");
      out.write("      \t\t<!-- 라인 차트 생성할 영역 -->\r\n");
      out.write("          <div id=\"lineChartArea\"></div>\r\n");
      out.write("      \t\t<!-- 컨트롤바를 생성할 영역 -->\r\n");
      out.write("          <div id=\"controlsArea\" style=\"height:100px;\"></div>\r\n");
      out.write("        </div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- 그래프 -->\r\n");
      out.write("\t<div style=\"width:100%;height:450px;padding-left:40px;\" id=\"chartIchupArea\">\r\n");
      out.write("\t    <h4 id=\"graphTitle\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[타시구 이첩자 변동 현황]</h4>\r\n");
      out.write(" \r\n");
      out.write("    \t<div id=\"Line_Controls_Ichup_Chart\">\r\n");
      out.write("      \t\t<!-- 라인 차트 생성할 영역 -->\r\n");
      out.write("          <div id=\"lineChartIchupArea\"></div>\r\n");
      out.write("      \t\t<!-- 컨트롤바를 생성할 영역 -->\r\n");
      out.write("          <div id=\"controlsIchupArea\" style=\"height:100px;\"></div>\r\n");
      out.write("        </div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- 그래프 -->\r\n");
      out.write("\t<div style=\"width:100%;height:450px;padding-left:40px;\" id=\"chartTasiguArea\">\r\n");
      out.write("\t    <h4 id=\"graphTitle\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[타시구민 확진자 변동 현황]</h4>\r\n");
      out.write(" \r\n");
      out.write("    \t<div id=\"Line_Controls_Tasigu_Chart\">\r\n");
      out.write("      \t\t<!-- 라인 차트 생성할 영역 -->\r\n");
      out.write("          <div id=\"lineChartTasiguArea\"></div>\r\n");
      out.write("      \t\t<!-- 컨트롤바를 생성할 영역 -->\r\n");
      out.write("          <div id=\"controlsTasiguArea\" style=\"height:100px;\"></div>\r\n");
      out.write("        </div>\r\n");
      out.write("\t</div>\r\n");
      out.write("<br>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<form id=\"commonForm\" name=\"commonForm\"></form>");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f0.setParent(null);
    // /WEB-INF/include/include-header.jspf(69,36) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f0.setValue("/js/jquery.min.js");
    int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
    if (_jspx_th_c_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f1 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f1.setParent(null);
    // /WEB-INF/include/include-header.jspf(70,36) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f1.setValue("/js/jquery-ui.js");
    int _jspx_eval_c_005furl_005f1 = _jspx_th_c_005furl_005f1.doStartTag();
    if (_jspx_th_c_005furl_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f1);
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f2 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f2.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f2.setParent(null);
    // /WEB-INF/include/include-header.jspf(71,36) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f2.setValue("/js/jquery.cookie.js");
    int _jspx_eval_c_005furl_005f2 = _jspx_th_c_005furl_005f2.doStartTag();
    if (_jspx_th_c_005furl_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f2);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f2);
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f3 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f3.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f3.setParent(null);
    // /WEB-INF/include/include-header.jspf(72,36) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f3.setValue("/js/jquery.form.js");
    int _jspx_eval_c_005furl_005f3 = _jspx_th_c_005furl_005f3.doStartTag();
    if (_jspx_th_c_005furl_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f3);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f3);
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f4 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f4.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f4.setParent(null);
    // /WEB-INF/include/include-header.jspf(73,13) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f4.setValue("/js/common.js");
    int _jspx_eval_c_005furl_005f4 = _jspx_th_c_005furl_005f4.doStartTag();
    if (_jspx_th_c_005furl_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f4);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f4);
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f0.setParent(null);
    // /WEB-INF/jsp/status/statusMiddleTotalView.jsp(44,3) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/jsp/status/statusMiddleTotalView.jsp(44,3) '${totalStatisticList}'",_el_expressionfactory.createValueExpression(_jspx_page_context.getELContext(),"${totalStatisticList}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    // /WEB-INF/jsp/status/statusMiddleTotalView.jsp(44,3) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setVar("info");
    int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
      if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("  \tvar ACCUM_GANGNAM_P =parseInt(\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${info.ACCUM_GANGNAM_P}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\");\r\n");
          out.write("  \tvar ACCUM_GANGNAM_CURED_P =parseInt(\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${info.ACCUM_GANGNAM_CURED_P}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\"); \r\n");
          out.write("  \tvar ACCUM_GANGNAM_CURING_P =parseInt(\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${info.ACCUM_GANGNAM_CURING_P}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\"); \r\n");
          out.write("  \tvar ACCUM_GANGNAM_DEATH_P =parseInt(\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${info.ACCUM_GANGNAM_DEATH_P}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\"); \r\n");
          out.write("  \t\t\r\n");
          out.write("  \tdataRow = [new Date(\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${info.ST_DAY}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\".substring(0,4), \"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${info.ST_DAY}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\".substring(4,6)-1, \"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${info.ST_DAY}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\".substring(6,8) ,'00' ),ACCUM_GANGNAM_P, ACCUM_GANGNAM_CURED_P, ACCUM_GANGNAM_CURING_P,ACCUM_GANGNAM_DEATH_P];\r\n");
          out.write("\t    data.addRow(dataRow); \r\n");
          out.write("  \t");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f0.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f1.setParent(null);
    // /WEB-INF/jsp/status/statusMiddleTotalView.jsp(150,3) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f1.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/jsp/status/statusMiddleTotalView.jsp(150,3) '${totalStatisticList}'",_el_expressionfactory.createValueExpression(_jspx_page_context.getELContext(),"${totalStatisticList}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    // /WEB-INF/jsp/status/statusMiddleTotalView.jsp(150,3) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f1.setVar("info");
    int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
      if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("  \tvar ACCUM_GANGNAM_ICHUP_P =parseInt(\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${info.ACCUM_GANGNAM_ICHUP_P}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\");\r\n");
          out.write("  \tvar ACCUM_GANGNAM_ICHUP_CURED_P =parseInt(\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${info.ACCUM_GANGNAM_ICHUP_CURED_P}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\"); \r\n");
          out.write("  \tvar ACCUM_GANGNAM_ICHUP_CURING_P =parseInt(\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${info.ACCUM_GANGNAM_ICHUP_CURING_P}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\");\r\n");
          out.write("  \tvar ACCUM_GANGNAM_ICHUP_DEATH_P =parseInt(\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${info.ACCUM_GANGNAM_ICHUP_DEATH_P}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\"); \r\n");
          out.write("  \t\t\r\n");
          out.write("  \tdataRow = [new Date(\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${info.ST_DAY}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\".substring(0,4), \"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${info.ST_DAY}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\".substring(4,6)-1, \"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${info.ST_DAY}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\".substring(6,8) ,'00' ),ACCUM_GANGNAM_ICHUP_P, ACCUM_GANGNAM_ICHUP_CURED_P, ACCUM_GANGNAM_ICHUP_CURING_P,ACCUM_GANGNAM_ICHUP_DEATH_P];\r\n");
          out.write("\t    data.addRow(dataRow); \r\n");
          out.write("  \t");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f1.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f1);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f2 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f2.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f2.setParent(null);
    // /WEB-INF/jsp/status/statusMiddleTotalView.jsp(253,3) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f2.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/jsp/status/statusMiddleTotalView.jsp(253,3) '${totalStatisticList}'",_el_expressionfactory.createValueExpression(_jspx_page_context.getELContext(),"${totalStatisticList}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    // /WEB-INF/jsp/status/statusMiddleTotalView.jsp(253,3) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f2.setVar("info");
    int[] _jspx_push_body_count_c_005fforEach_005f2 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f2 = _jspx_th_c_005fforEach_005f2.doStartTag();
      if (_jspx_eval_c_005fforEach_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("  \tvar ACCUM_TASIGU_P =parseInt(\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${info.ACCUM_TASIGU_P}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\"); \r\n");
          out.write("  \t\t\r\n");
          out.write("  \tdataRow = [new Date(\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${info.ST_DAY}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\".substring(0,4), \"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${info.ST_DAY}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\".substring(4,6)-1, \"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${info.ST_DAY}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\".substring(6,8) ,'00' ), ACCUM_TASIGU_P];\r\n");
          out.write("\t    data.addRow(dataRow); \r\n");
          out.write("  \t");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f2[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f2.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f2.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f2);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f5(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f5 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f5.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f5.setParent(null);
    // /WEB-INF/jsp/status/statusMiddleTotalView.jsp(337,20) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f5.setValue("/status/statusTrackingView.do");
    int _jspx_eval_c_005furl_005f5 = _jspx_th_c_005furl_005f5.doStartTag();
    if (_jspx_th_c_005furl_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f5);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f5);
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f3 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f3.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f3.setParent(null);
    // /WEB-INF/jsp/status/statusMiddleTotalView.jsp(389,5) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f3.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/jsp/status/statusMiddleTotalView.jsp(389,5) '${selectTotalMiddle}'",_el_expressionfactory.createValueExpression(_jspx_page_context.getELContext(),"${selectTotalMiddle}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    // /WEB-INF/jsp/status/statusMiddleTotalView.jsp(389,5) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f3.setVar("item");
    // /WEB-INF/jsp/status/statusMiddleTotalView.jsp(389,5) name = varStatus type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f3.setVarStatus("i");
    int[] _jspx_push_body_count_c_005fforEach_005f3 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f3 = _jspx_th_c_005fforEach_005f3.doStartTag();
      if (_jspx_eval_c_005fforEach_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t\t<tr>\r\n");
          out.write("\t\t\t\t\t\t\t<td style='CURSOR:hand;color:#a014a0' onclick='go_confirmTotalDtl(\"강남구\",\"\",\"\",\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.ORG_DONG}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write('"');
          out.write(',');
          out.write('"');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${WRITE_DATE}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\")'>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.ORG_DONG}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write('(');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.ORG_DONG_TOT}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write(")</td>\r\n");
          out.write("\t\t\t\t\t\t\t<td style='CURSOR:hand;color:#0099FF;text-align:center;' onclick='go_confirmTotalDtl(\"강남구\",\"Y\",\"\",\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.ORG_DONG}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write('"');
          out.write(',');
          out.write('"');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${WRITE_DATE}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\")'>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.CURE_Y_CNT}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</td>\r\n");
          out.write("\t\t\t\t\t\t\t<td style='CURSOR:hand;color:#0099FF;text-align:center;' onclick='go_confirmTotalDtl(\"강남구\",\"N\",\"\",\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.ORG_DONG}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write('"');
          out.write(',');
          out.write('"');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${WRITE_DATE}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\")'>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.CURE_N_CNT}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</td>\r\n");
          out.write("\t\t\t\t\t\t\t<td style='CURSOR:hand;color:#0099FF;text-align:center;' onclick='go_confirmTotalDtl(\"강남구\",\"DEATH\",\"\",\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.ORG_DONG}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write('"');
          out.write(',');
          out.write('"');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${WRITE_DATE}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\")'>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.DEATH_CNT}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</td>\r\n");
          out.write("\t\t\t\t\t\t</tr>\r\n");
          out.write("\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f3.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f3[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f3.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f3.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f3);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f4 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f4.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f4.setParent(null);
    // /WEB-INF/jsp/status/statusMiddleTotalView.jsp(413,5) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f4.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/jsp/status/statusMiddleTotalView.jsp(413,5) '${selectTotalExMiddle}'",_el_expressionfactory.createValueExpression(_jspx_page_context.getELContext(),"${selectTotalExMiddle}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    // /WEB-INF/jsp/status/statusMiddleTotalView.jsp(413,5) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f4.setVar("item");
    // /WEB-INF/jsp/status/statusMiddleTotalView.jsp(413,5) name = varStatus type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f4.setVarStatus("i");
    int[] _jspx_push_body_count_c_005fforEach_005f4 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f4 = _jspx_th_c_005fforEach_005f4.doStartTag();
      if (_jspx_eval_c_005fforEach_005f4 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t\t<tr>\r\n");
          out.write("\t\t\t\t\t\t\t<td>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.ORG_DONG}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</td>\r\n");
          out.write("\t\t\t\t\t\t\t<td style='CURSOR:hand;color:#0099FF;text-align:center;' onclick='go_confirmTotalDtl(\"타지역\",\"\",\"\",\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.ORG_DONG}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write('"');
          out.write(',');
          out.write('"');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${WRITE_DATE}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\")'>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.ORG_DONG_CNT}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</td> \r\n");
          out.write("\t\t\t\t\t\t</tr>\r\n");
          out.write("\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f4.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f4[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f4.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f4.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f4);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f5(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f5 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f5.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f5.setParent(null);
    // /WEB-INF/jsp/status/statusMiddleTotalView.jsp(443,5) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f5.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/jsp/status/statusMiddleTotalView.jsp(443,5) '${selectAccumTotalMiddle}'",_el_expressionfactory.createValueExpression(_jspx_page_context.getELContext(),"${selectAccumTotalMiddle}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    // /WEB-INF/jsp/status/statusMiddleTotalView.jsp(443,5) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f5.setVar("item");
    // /WEB-INF/jsp/status/statusMiddleTotalView.jsp(443,5) name = varStatus type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f5.setVarStatus("i");
    int[] _jspx_push_body_count_c_005fforEach_005f5 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f5 = _jspx_th_c_005fforEach_005f5.doStartTag();
      if (_jspx_eval_c_005fforEach_005f5 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t\t<tr>\r\n");
          out.write("\t\t\t\t\t\t\t<td style='CURSOR:hand;color:#a014a0' onclick='go_confirmTotalDtl(\"강남구\",\"\",\"N\",\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.ORG_DONG}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\",\"\")'>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.ORG_DONG}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write('(');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.ORG_DONG_TOT}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write(")</td>\r\n");
          out.write("\t\t\t\t\t\t\t<td style='CURSOR:hand;color:#0099FF;text-align:center;' onclick='go_confirmTotalDtl(\"강남구\",\"Y\",\"N\",\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.ORG_DONG}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\",\"\")'>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.CURE_Y_CNT}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</td>\r\n");
          out.write("\t\t\t\t\t\t\t<td style='CURSOR:hand;color:#0099FF;text-align:center;' onclick='go_confirmTotalDtl(\"강남구\",\"N\",\"N\",\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.ORG_DONG}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\",\"\")'>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.CURE_N_CNT}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</td>\r\n");
          out.write("\t\t\t\t\t\t\t<td style='CURSOR:hand;color:#0099FF;text-align:center;' onclick='go_confirmTotalDtl(\"강남구\",\"DEATH\",\"N\",\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.ORG_DONG}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\",\"\")'>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.DEATH_CNT}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</td>\r\n");
          out.write("\t\t\t\t\t\t</tr>\r\n");
          out.write("\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f5.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f5[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f5.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f5.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f5);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f6(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f6 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f6.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f6.setParent(null);
    // /WEB-INF/jsp/status/statusMiddleTotalView.jsp(471,5) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f6.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/jsp/status/statusMiddleTotalView.jsp(471,5) '${selectAccumTotalIchupMiddle}'",_el_expressionfactory.createValueExpression(_jspx_page_context.getELContext(),"${selectAccumTotalIchupMiddle}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    // /WEB-INF/jsp/status/statusMiddleTotalView.jsp(471,5) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f6.setVar("item");
    // /WEB-INF/jsp/status/statusMiddleTotalView.jsp(471,5) name = varStatus type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f6.setVarStatus("i");
    int[] _jspx_push_body_count_c_005fforEach_005f6 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f6 = _jspx_th_c_005fforEach_005f6.doStartTag();
      if (_jspx_eval_c_005fforEach_005f6 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t\t<tr>\r\n");
          out.write("\t\t\t\t\t\t\t<td style='CURSOR:hand;color:#a014a0' onclick='go_confirmTotalDtl(\"강남구\",\"\",\"Y\",\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.ORG_DONG}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\",\"\")'>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.ORG_DONG}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write('(');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.ORG_DONG_TOT}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write(")</td>\r\n");
          out.write("\t\t\t\t\t\t\t<td style='CURSOR:hand;color:#0099FF;text-align:center;' onclick='go_confirmTotalDtl(\"강남구\",\"Y\",\"Y\",\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.ORG_DONG}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\",\"\")'>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.CURE_Y_CNT}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</td>\r\n");
          out.write("\t\t\t\t\t\t\t<td style='CURSOR:hand;color:#0099FF;text-align:center;' onclick='go_confirmTotalDtl(\"강남구\",\"N\",\"Y\",\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.ORG_DONG}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\",\"\")'>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.CURE_N_CNT}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</td>\r\n");
          out.write("\t\t\t\t\t\t\t<td style='CURSOR:hand;color:#0099FF;text-align:center;' onclick='go_confirmTotalDtl(\"강남구\",\"DEATH\",\"Y\",\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.ORG_DONG}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\",\"\")'>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.DEATH_CNT}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</td>\r\n");
          out.write("\t\t\t\t\t\t</tr>\r\n");
          out.write("\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f6.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f6[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f6.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f6.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f6);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f7(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f7 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f7.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f7.setParent(null);
    // /WEB-INF/jsp/status/statusMiddleTotalView.jsp(497,5) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f7.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/jsp/status/statusMiddleTotalView.jsp(497,5) '${selectAccumTotalExMiddle}'",_el_expressionfactory.createValueExpression(_jspx_page_context.getELContext(),"${selectAccumTotalExMiddle}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    // /WEB-INF/jsp/status/statusMiddleTotalView.jsp(497,5) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f7.setVar("item");
    // /WEB-INF/jsp/status/statusMiddleTotalView.jsp(497,5) name = varStatus type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f7.setVarStatus("i");
    int[] _jspx_push_body_count_c_005fforEach_005f7 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f7 = _jspx_th_c_005fforEach_005f7.doStartTag();
      if (_jspx_eval_c_005fforEach_005f7 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t\t<tr>\r\n");
          out.write("\t\t\t\t\t\t\t<td>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.ORG_DONG}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</td>\r\n");
          out.write("\t\t\t\t\t\t\t<td style='CURSOR:hand;color:#0099FF;text-align:center;' onclick='go_confirmTotalDtl(\"타지역\",\"\",\"\",\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.ORG_DONG}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\",\"\")'>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.ORG_DONG_CNT}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</td> \r\n");
          out.write("\t\t\t\t\t\t</tr>\r\n");
          out.write("\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f7.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f7.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f7[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f7.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f7.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f7);
    }
    return false;
  }
}
