/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.24
 * Generated at: 2020-09-01 01:31:34 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.daejang;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class prvCnrtBoardWrite_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(6);
    _jspx_dependants.put("/WEB-INF/include/include-body.jspf", Long.valueOf(1561017636000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1595463255549L));
    _jspx_dependants.put("jar:file:/C:/dev/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/scms/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/C:/dev/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/scms/WEB-INF/lib/jstl-1.2.jar!/META-INF/fn.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/C:/dev/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/scms/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/include/include-header.jspf", Long.valueOf(1548234426000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>수의계약 관리시스템</title>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/scms/css/common.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/scms/css/skin01.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/scms/css/import.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/scms/css/scms.css\" />\r\n");
      out.write("\r\n");
      out.write("<!-- jQuery -->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/scms/css/jquery-ui.css\" />\r\n");
      out.write("<!-- <script src=\"http://code.jquery.com/jquery.min.js\"></script>-->\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      if (_jspx_meth_c_005furl_005f0(_jspx_page_context))
        return;
      out.write("\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      if (_jspx_meth_c_005furl_005f1(_jspx_page_context))
        return;
      out.write("\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      if (_jspx_meth_c_005furl_005f2(_jspx_page_context))
        return;
      out.write("\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      if (_jspx_meth_c_005furl_005f3(_jspx_page_context))
        return;
      out.write("\"></script>\r\n");
      out.write("<script src=\"");
      if (_jspx_meth_c_005furl_005f4(_jspx_page_context))
        return;
      out.write("\" charset=\"utf-8\"></script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"/scms/se2/js/service/HuskyEZCreator.js\" charset=\"utf-8\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t\tvar gfv_count = 1;\r\n");
      out.write("\t\tvar tmp2 = \"\";\r\n");
      out.write("\t\tvar i = 1;\r\n");
      out.write("\t\t$(document).ready(function(){\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t$(\"#list\").on(\"click\", function(e){ //목록으로 버튼\r\n");
      out.write("\t\t\t\te.preventDefault();\r\n");
      out.write("\t\t\t\tfn_prvCnrtBoardList();\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$(\"#write\").on(\"click\", function(e){ //등록하기 버튼\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\te.preventDefault();\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tif( $('#USER_RIGHT').val() == 'A')\r\n");
      out.write("\t\t\t\t{\r\n");
      out.write("\t\t\t\t\tfn_insertPrvCnrtBoard();\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\telse{\r\n");
      out.write("\t\t\t\t\talert('권한이 없습니다.');\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t$('#close1').click(function() {\r\n");
      out.write("\t\t        $('#pop').hide();\r\n");
      out.write("\t\t    });\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$('#close2').click(function() {\r\n");
      out.write("\t\t        $('#pop').hide();\r\n");
      out.write("\t\t    });\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$('#open').click(function() {\r\n");
      out.write("\t\t        \r\n");
      out.write("\t\t\t\tif($(\"#USER_NAME\").val().length < 1){\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\talert('찾으시려는 이름을 입력하세요');\r\n");
      out.write("\t\t\t\t\t$(\"#USER_NAME\").focus();\r\n");
      out.write("\t\t\t\t\treturn;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t$('#pop').show();\r\n");
      out.write("\t\t        fn_jikwonlist();\r\n");
      out.write("\t\t    });\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$('#clear').click(function() {\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t$('#SAUP_PERSON_ID').val(\"\");\t\t\t\r\n");
      out.write("\t\t    });\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$(\"#addFile\").on(\"click\", function(e){ //파일 추가 버튼\r\n");
      out.write("\t\t\t\te.preventDefault();\r\n");
      out.write("\t\t\t\tfn_addFile();\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$(\"a[name='delete']\").on(\"click\", function(e){ //삭제 버튼\r\n");
      out.write("\t\t\t\te.preventDefault();\r\n");
      out.write("\t\t\t\tfn_deleteFile($(this));\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$(\"#SAUP_BUDGET_AMT\").bind('keyup keydown',function(){\r\n");
      out.write("\t\t        inputNumberFormat(this);\r\n");
      out.write("\t\t    });\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$(document).keydown(function(e){\r\n");
      out.write("\t\t\t\tif(e.target.nodeName != \"INPUT\" && e.target.nodeName != \"TEXTAREA\"){\r\n");
      out.write("\t\t\t        if(e.keyCode == 8){\t\t        \r\n");
      out.write("\t\t\t        \treturn false;\r\n");
      out.write("\t\t\t        }\r\n");
      out.write("\t\t\t    }\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tif(e.target.readOnly){ // readonly일 경우 true\r\n");
      out.write("\t\t            if(e.keyCode == 8){\r\n");
      out.write("\t\t                return false;\r\n");
      out.write("\t\t           }\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//입력한 문자열 전달\r\n");
      out.write("\t    function inputNumberFormat(obj) {\r\n");
      out.write("\t        obj.value = comma(uncomma(obj.value));\r\n");
      out.write("\t    }\r\n");
      out.write("\t       \r\n");
      out.write("\t    //콤마찍기\r\n");
      out.write("\t    function comma(str) {\r\n");
      out.write("\t        str = String(str);\r\n");
      out.write("\t        return str.replace(/(\\d)(?=(?:\\d{3})+(?!\\d))/g, '$1,');\r\n");
      out.write("\t    }\r\n");
      out.write("\t \r\n");
      out.write("\t    //콤마풀기\r\n");
      out.write("\t    function uncomma(str) {\r\n");
      out.write("\t        str = String(str);\r\n");
      out.write("\t        return str.replace(/[^\\d]+/g, '');\r\n");
      out.write("\t    }\r\n");
      out.write("\t \r\n");
      out.write("\t    //숫자만 리턴(저장할때)\r\n");
      out.write("\t    //alert(cf_getNumberOnly('1,2./3g')); -> 123 return\r\n");
      out.write("\t    function cf_getNumberOnly (str) {\r\n");
      out.write("\t        var len      = str.length;\r\n");
      out.write("\t        var sReturn  = \"\";\r\n");
      out.write("\t \r\n");
      out.write("\t        for (var i=0; i<len; i++){\r\n");
      out.write("\t            if ( (str.charAt(i) >= \"0\") && (str.charAt(i) <= \"9\") ){\r\n");
      out.write("\t                sReturn += str.charAt(i);\r\n");
      out.write("\t            }\r\n");
      out.write("\t        }\r\n");
      out.write("\t        return sReturn;\r\n");
      out.write("\t    }\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction fn_prvCnrtBoardList(){\r\n");
      out.write("\t\t\tvar comSubmit = new ComSubmit();\r\n");
      out.write("\t\t\tcomSubmit.setUrl(\"");
      if (_jspx_meth_c_005furl_005f5(_jspx_page_context))
        return;
      out.write("\");\t\t\r\n");
      out.write("\t\t\tcomSubmit.submit();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction fn_insertPrvCnrtBoard(){\r\n");
      out.write("\t\t\tvar comSubmit = new ComSubmit(\"form1\");\r\n");
      out.write("\t\t\tvar tmp = \"\";\t\t\t\t\r\n");
      out.write("\t\t\toEditors.getById[\"CONTENTS\"].exec(\"UPDATE_CONTENTS_FIELD\", []);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif($('#TITLE').val() == \"\")\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\talert('제목을  입력하세요!!');\r\n");
      out.write("\t\t\t\t$('#TITLE').focus();\r\n");
      out.write("\t\t\t\treturn false();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\tif($('#CONTENT').val() == \"\")\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\talert('내용을  입력하세요!!');\r\n");
      out.write("\t\t\t\t$('#CONTENT').focus();\r\n");
      out.write("\t\t\t\treturn false();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\tif(confirm('데이터를 등록하시겠습니까?'))\r\n");
      out.write("\t\t\t{\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\tcomSubmit.setUrl(\"");
      if (_jspx_meth_c_005furl_005f6(_jspx_page_context))
        return;
      out.write("\");\r\n");
      out.write("\t\t\t\tcomSubmit.addParam(\"BOARD_ID\", \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.BOARD_ID}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\");\r\n");
      out.write("\t\t\t\tcomSubmit.submit();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction fn_addFile(){\r\n");
      out.write("\t\t\tvar str = \"<p><input type='file' name='file_\"+(gfv_count++)+\"'> <a href='#this' class='btn' name='delete'>삭제</a></p>\";\r\n");
      out.write("\t\t\t$(\"#fileDiv\").append(str);\r\n");
      out.write("\t\t\t$(\"a[name='delete']\").on(\"click\", function(e){ //삭제 버튼\r\n");
      out.write("\t\t\t\te.preventDefault();\r\n");
      out.write("\t\t\t\tfn_deleteFile($(this));\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction fn_deleteFile(obj){\r\n");
      out.write("\t\t\tobj.parent().remove();\r\n");
      out.write("\t\t}\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction fn_amtCheck(){\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif(uncomma($('#SAUP_BUDGET_AMT').val()) <  3300000 || uncomma($('#SAUP_BUDGET_AMT').val()) > 22000000 )\r\n");
      out.write("\t\t\t{\t\t\t\t\r\n");
      out.write("\t\t\t\talert('수의계약 관리시스템 금액기준을 벗어났습니다.!!\\n한번 확인후 진행하시길 바랍니다.[330만원 ~ 2,200만원(예외있음)]');\r\n");
      out.write("\t\t\t\t$('#SAUP_BUDGET_AMT').focus();\r\n");
      out.write("\t\t\t\t$('#SAUP_BUDGET_AMT').select();\r\n");
      out.write("\t\t\t\t//return false();\r\n");
      out.write("\t\t\t}\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("input:read-only { \r\n");
      out.write("\tbackground-color:blue;\r\n");
      out.write("\t}\r\n");
      out.write("</style>\t\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("<form id=\"form1\" name=\"form1\" enctype=\"multipart/form-data\">\r\n");
      out.write("<input type=\"hidden\" id=\"INS_ID\" name=\"INS_ID\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.userinfo.userId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("<input type=\"hidden\" id=\"INS_DEPT\" name=\"INS_DEPT\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.userinfo.deptId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("<input type=\"hidden\" id=\"USER_RIGHT\" name=\"USER_RIGHT\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.userinfo.userright}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("<input type=\"hidden\" id=\"WRITE_ID\" name=\"WRITE_ID\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${map.INS_ID}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("<input type=\"hidden\" id=\"LOGIN_ID\" name=\"LOGIN_ID\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.userinfo.userId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("<input type=\"hidden\" id=\"BOARD_GB\" name=\"BOARD_GB\" value=\"7\"> \r\n");
      out.write("\r\n");
      out.write("<table  border=\"0\" cellspacing=\"0\" cellpadding=\"0\" class=\"bodyframe_full\">\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td class=\"bodyframe\">\r\n");
      out.write("    <!--페이지 타이틀 시작 -->\r\n");
      out.write("    <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("      <tr>\r\n");
      out.write("        <td class=\"pupup_title\"><img src=\"/scms/images/popup_title.png\" align=\"absmiddle\">공지사항 등록</td>\r\n");
      out.write("      </tr>\r\n");
      out.write("      <tr>\r\n");
      out.write("        <td class=\"margin_title\"></td>\r\n");
      out.write("      </tr>\r\n");
      out.write("    </table>\r\n");
      out.write("    <!--페이지 타이틀 끝 -->\r\n");
      out.write("    </td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  \r\n");
      out.write("  <tr>\r\n");
      out.write("    <td class=\"pupup_frame\" style=\"padding-right:12px\">\r\n");
      out.write("\r\n");
      out.write("    <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("      <tr>\r\n");
      out.write("        <td height=\"15\">\r\n");
      out.write("                                \r\n");
      out.write(" \r\n");
      out.write("        <!--리스트 시작 -->\r\n");
      out.write("\t      <table width=\"100%\" border=\"0\" cellspacing=\"1\" cellpadding=\"0\" class=\"tbl\" id=\"divMemoMainBody\" style=\"display:block;\">\t      \t \t         \t       \r\n");
      out.write("\t          <tr>\r\n");
      out.write("\t            <td width=\"120\" class=\"tbl_field\">제목</td>\r\n");
      out.write("\t            <td width=\"710\" colspan=\"3\" class=\"tbl_list_left\"><input type=\"text\" id=\"TITLE\" name=\"TITLE\" class=\"input\" style=\"width:400;\"></td>\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t          </tr>\t         \t         \t          \r\n");
      out.write("\t          <tr>\r\n");
      out.write("\t            <td width=\"120\" class=\"tbl_field\">내용</td>\r\n");
      out.write("\t            <td width=\"710\" colspan=\"3\" class=\"tbl_list_left\">\r\n");
      out.write("\t             <textarea rows=\"10\" cols=\"100\" id=\"CONTENTS\" name=\"CONTENTS\" class=\"input\" style=\"width:700px; height:400px; display:none;\"></textarea>\r\n");
      out.write("\t            </td>\r\n");
      out.write("\t          </tr>\r\n");
      out.write("\t          <tr>\r\n");
      out.write("\t            <td width=\"120\" class=\"tbl_field\">첨부파일</td>\r\n");
      out.write("\t            <td colspan=\"3\" width=\"710\" class=\"tbl_list_left\">\r\n");
      out.write("\t                <div id=\"fileDiv\">\r\n");
      out.write("\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"file\" id=\"file\" name=\"file_0\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#this\" class=\"btn\" id=\"delete\" name=\"delete\">삭제</a> (<b>10M이하</b>)\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<a href=\"#this\" class=\"btn\" id=\"addFile\">파일 추가</a> (<b>10M이하</b>)           \r\n");
      out.write("\t            </td>\r\n");
      out.write("\t          </tr>\t        \t       \r\n");
      out.write("\t      </table>\r\n");
      out.write("\t      \t      \r\n");
      out.write("        <!-- -------------- 버튼 시작 --------------  -->\r\n");
      out.write("        <table width=\"100%\" height=\"40\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("          <tr>\r\n");
      out.write("            <td></td>\r\n");
      out.write("            <td align=\"right\">\r\n");
      out.write("            <table border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("              <tr>\r\n");
      out.write("               <td>\r\n");
      out.write("                <table border=\"0\" cellspacing=\"0\" cellpadding=\"0\" class=\"btn\" id=\"changebtn2\" style=\"display:block;\">\r\n");
      out.write("                  <tr>\r\n");
      out.write("                    <td><img src=\"/scms/images/btn_type0_head.gif\"></td>\r\n");
      out.write("                    <td background=\"/scms/images/btn_type0_bg.gif\" class=\"btn_type1\" nowrap><a href=\"#this\" class=\"btn\" id=\"write\"><font color=\"white\">등록</font></a></td>\r\n");
      out.write("                    <td><img src=\"/scms/images/btn_type0_end.gif\"></td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                </table>\r\n");
      out.write("                </td>                               \t\r\n");
      out.write("                <td>\r\n");
      out.write("                <table border=\"0\" cellspacing=\"0\" cellpadding=\"0\" class=\"btn\" id=\"tblAddMemoTempSave21\" style=\"filter:none;\">\r\n");
      out.write("                  <tr>\r\n");
      out.write("                    <td><img src=\"/scms/images/btn_type1_head.gif\"></td>\r\n");
      out.write("                    <td background=\"/scms/images/btn_type1_bg.gif\" class=\"btn_type1\" nowrap><a href=\"#this\" class=\"btn\" id=\"list\">목록</a></td>\r\n");
      out.write("                    <td><img src=\"/scms/images/btn_type1_end.gif\"></td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                </table>                \r\n");
      out.write("                </td>                               \r\n");
      out.write("              </tr>\r\n");
      out.write("            </table>\r\n");
      out.write("            </td>\r\n");
      out.write("          </tr>\r\n");
      out.write("          <tr>\r\n");
      out.write("            <td class=\"margin_btn\" colspan=\"2\"></td>\r\n");
      out.write("          </tr>\r\n");
      out.write("        </table>\r\n");
      out.write("        <!-- -------------- 버튼 끝 --------------  -->        \r\n");
      out.write("        </td>\r\n");
      out.write("      </tr>\r\n");
      out.write("    </table>\r\n");
      out.write("    </td>    \r\n");
      out.write("  </tr>\r\n");
      out.write("</table>\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("<form id=\"commonForm\" name=\"commonForm\"></form>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("var oEditors = [];\r\n");
      out.write("\r\n");
      out.write("var sLang = \"ko_KR\";\t// 언어 (ko_KR/ en_US/ ja_JP/ zh_CN/ zh_TW), default = ko_KR\r\n");
      out.write("\r\n");
      out.write("// 추가 글꼴 목록\r\n");
      out.write("//var aAdditionalFontSet = [[\"MS UI Gothic\", \"MS UI Gothic\"], [\"Comic Sans MS\", \"Comic Sans MS\"],[\"TEST\",\"TEST\"]];\r\n");
      out.write("\r\n");
      out.write("nhn.husky.EZCreator.createInIFrame({\r\n");
      out.write("\toAppRef: oEditors,\r\n");
      out.write("\telPlaceHolder: \"CONTENTS\",\r\n");
      out.write("\tsSkinURI: \"/scms/se2/SmartEditor2Skin.html\",\t\r\n");
      out.write("\thtParams : {\r\n");
      out.write("\t\tbUseToolbar : true,\t\t\t\t// 툴바 사용 여부 (true:사용/ false:사용하지 않음)\r\n");
      out.write("\t\tbUseVerticalResizer : true,\t\t// 입력창 크기 조절바 사용 여부 (true:사용/ false:사용하지 않음)\r\n");
      out.write("\t\tbUseModeChanger : true,\t\t\t// 모드 탭(Editor | HTML | TEXT) 사용 여부 (true:사용/ false:사용하지 않음)\r\n");
      out.write("\t\t//bSkipXssFilter : true,\t\t// client-side xss filter 무시 여부 (true:사용하지 않음 / 그외:사용)\r\n");
      out.write("\t\t//aAdditionalFontList : aAdditionalFontSet,\t\t// 추가 글꼴 목록\r\n");
      out.write("\t\tfOnBeforeUnload : function(){\r\n");
      out.write("\t\t\t//alert(\"완료!\");\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\tI18N_LOCALE : sLang\r\n");
      out.write("\t}, //boolean\r\n");
      out.write("\tfOnAppLoad : function(){\r\n");
      out.write("\t\t//예제 코드\r\n");
      out.write("\t\t//oEditors.getById[\"SAUP_PUSH_CONTENT\"].exec(\"PASTE_HTML\", [\"로딩이 완료된 후에 본문에 삽입되는 text입니다.\"]);\r\n");
      out.write("\t},\r\n");
      out.write("\tfCreator: \"createSEditor2\"\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f0.setParent(null);
    // /WEB-INF/include/include-header.jspf(13,36) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f0.setValue("/js/jquery.min.js");
    int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
    if (_jspx_th_c_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f1 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f1.setParent(null);
    // /WEB-INF/include/include-header.jspf(14,36) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f1.setValue("/js/jquery-ui.js");
    int _jspx_eval_c_005furl_005f1 = _jspx_th_c_005furl_005f1.doStartTag();
    if (_jspx_th_c_005furl_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f1);
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f2 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f2.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f2.setParent(null);
    // /WEB-INF/include/include-header.jspf(15,36) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f2.setValue("/js/jquery.cookie.js");
    int _jspx_eval_c_005furl_005f2 = _jspx_th_c_005furl_005f2.doStartTag();
    if (_jspx_th_c_005furl_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f2);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f2);
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f3 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f3.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f3.setParent(null);
    // /WEB-INF/include/include-header.jspf(16,36) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f3.setValue("/js/jquery.form.js");
    int _jspx_eval_c_005furl_005f3 = _jspx_th_c_005furl_005f3.doStartTag();
    if (_jspx_th_c_005furl_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f3);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f3);
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f4 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f4.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f4.setParent(null);
    // /WEB-INF/include/include-header.jspf(17,13) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f4.setValue("/js/common.js");
    int _jspx_eval_c_005furl_005f4 = _jspx_th_c_005furl_005f4.doStartTag();
    if (_jspx_th_c_005furl_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f4);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f4);
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f5(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f5 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f5.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f5.setParent(null);
    // /WEB-INF/jsp/daejang/prvCnrtBoardWrite.jsp(128,21) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f5.setValue("/daejang/prvCnrtBoardList.do");
    int _jspx_eval_c_005furl_005f5 = _jspx_th_c_005furl_005f5.doStartTag();
    if (_jspx_th_c_005furl_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f5);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f5);
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f6(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f6 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f6.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f6.setParent(null);
    // /WEB-INF/jsp/daejang/prvCnrtBoardWrite.jsp(157,22) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f6.setValue("/daejang/insertPrvCnrtBoard.do");
    int _jspx_eval_c_005furl_005f6 = _jspx_th_c_005furl_005f6.doStartTag();
    if (_jspx_th_c_005furl_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f6);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f6);
    return false;
  }
}
