/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.24
 * Generated at: 2020-08-27 23:47:24 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.daejang;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class mainSaupUpdate_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(6);
    _jspx_dependants.put("jar:file:/C:/dev/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp14/wtpwebapps/bims/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/include/include-body.jspf", Long.valueOf(1433227700000L));
    _jspx_dependants.put("jar:file:/C:/dev/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp14/wtpwebapps/bims/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1595463255549L));
    _jspx_dependants.put("/WEB-INF/include/include-header.jspf", Long.valueOf(1548650484000L));
    _jspx_dependants.put("jar:file:/C:/dev/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp14/wtpwebapps/bims/WEB-INF/lib/jstl-1.2.jar!/META-INF/fn.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fpattern_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ffmt_005fparseDate_0026_005fvar_005fvalue_005fpattern_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fpattern_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ffmt_005fparseDate_0026_005fvar_005fvalue_005fpattern_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fpattern_005fnobody.release();
    _005fjspx_005ftagPool_005ffmt_005fparseDate_0026_005fvar_005fvalue_005fpattern_005fnobody.release();
    _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>주요사업관리시스템</title>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/bims/css/common.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/bims/css/skin01.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/bims/css/import.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/bims/css/bims.css\" />\r\n");
      out.write("\r\n");
      out.write("<!-- jQuery -->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/bims/css/jquery-ui.css\" />\r\n");
      out.write("<!-- <script src=\"http://code.jquery.com/jquery.min.js\"></script>-->\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      if (_jspx_meth_c_005furl_005f0(_jspx_page_context))
        return;
      out.write("\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      if (_jspx_meth_c_005furl_005f1(_jspx_page_context))
        return;
      out.write("\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      if (_jspx_meth_c_005furl_005f2(_jspx_page_context))
        return;
      out.write("\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      if (_jspx_meth_c_005furl_005f3(_jspx_page_context))
        return;
      out.write("\"></script>\r\n");
      out.write("<script src=\"");
      if (_jspx_meth_c_005furl_005f4(_jspx_page_context))
        return;
      out.write("\" charset=\"utf-8\"></script>\r\n");
      out.write("\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write(" #pop{\r\n");
      out.write("  width:300px; height:250px; background:#3d3d3d; color:#fff; \r\n");
      out.write("  position:absolute; top:10px; left:100px; text-align:center; \r\n");
      out.write("  border:1px solid #000;\r\n");
      out.write("   }\r\n");
      out.write("</style>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t\tvar gfv_count = 1;\r\n");
      out.write("\t\r\n");
      out.write("\t\t$(document).ready(function(){\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$(\"#list\").on(\"click\", function(e){ //목록으로 버튼\r\n");
      out.write("\t\t\t\t//alert('aa');\r\n");
      out.write("\t\t\t\te.preventDefault();\t\t\t\t\r\n");
      out.write("\t\t\t\tfn_mainSaupList();\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$(\"#update\").on(\"click\", function(e){ //수정하기 버튼\r\n");
      out.write("\t\t\t\tif( $('#USER_RIGHT').val() == 'A' || $('#WRITE_DEPT').val() == $('#LOGIN_DEPT').val())\r\n");
      out.write("\t\t\t\t{\t\t\t\t\r\n");
      out.write("\t\t\t\t\te.preventDefault();\r\n");
      out.write("\t\t\t\t\tfn_updateMainSaupData();\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\telse{\r\n");
      out.write("\t\t\t\t\talert('권한이 없습니다.');\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$(\"#del\").on(\"click\", function(e){ //수정하기 버튼\r\n");
      out.write("\t\t\t\tif( $('#USER_RIGHT').val() == 'A' || $('#WRITE_DEPT').val() == $('#LOGIN_DEPT').val())\r\n");
      out.write("\t\t\t\t{\t\t\t\t\r\n");
      out.write("\t\t\t\t\te.preventDefault();\r\n");
      out.write("\t\t\t\t\tfn_deleteMainSaupData();\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\telse{\r\n");
      out.write("\t\t\t\t\talert('권한이 없습니다.');\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$(\"#msaup\").on(\"click\", function(e){ //목록으로 버튼\r\n");
      out.write("\t\t\t\t//alert('aa');\r\n");
      out.write("\t\t\t\te.preventDefault();\r\n");
      out.write("\t\t\t\t$('#pop2').show();\t\t        \r\n");
      out.write("\t\t\t\tfn_mSaupList();\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$('#close1').click(function() {\r\n");
      out.write("\t\t        $('#pop').hide();\r\n");
      out.write("\t\t    });\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$('#close2').click(function() {\r\n");
      out.write("\t\t        $('#pop').hide();\r\n");
      out.write("\t\t    });\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$('#close3').click(function() {\r\n");
      out.write("\t\t        $('#pop2').hide();\r\n");
      out.write("\t\t    });\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$('#close4').click(function() {\r\n");
      out.write("\t\t        $('#pop2').hide();\r\n");
      out.write("\t\t    });\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$('#open').click(function() {\r\n");
      out.write("\t\t        \r\n");
      out.write("\t\t\t\tif($(\"#USER_NAME\").val().length < 1){\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\talert('찾으시려는 이름을 입력하세요');\r\n");
      out.write("\t\t\t\t\t$(\"#USER_NAME\").focus();\r\n");
      out.write("\t\t\t\t\treturn;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t$('#pop').show();\r\n");
      out.write("\t\t        fn_jikwonlist();\r\n");
      out.write("\t\t    });\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$(\"#USER_NAME\").keydown(function (key) {\r\n");
      out.write("\r\n");
      out.write("\t\t\t\tif(key.keyCode == 13){//키가 13이면 실행 (엔터는 13)\r\n");
      out.write("\t\t\t\t\t$('#pop').show();\r\n");
      out.write("\t\t\t\t\tfn_jikwonlist();\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$(\"#SAUP_BUDGET_AMT\").bind('keyup keydown',function(){\r\n");
      out.write("\t\t        inputNumberFormat(this);\r\n");
      out.write("\t\t    });\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$(\"#SAUP_OPEN_DATE\").datepicker({\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tdateFormat: 'yy-mm-dd',\r\n");
      out.write("\t\t\t\tmonthNamesShort: ['1월','2월','3월','4월','5월','6월','7월','8월','9월','10월','11월','12월'],\r\n");
      out.write("\t\t\t    dayNamesMin: ['일','월','화','수','목','금','토'],\r\n");
      out.write("\t\t\t\tchangeMonth: true, //월변경가능\r\n");
      out.write("\t\t\t    changeYear: true, //년변경가능\r\n");
      out.write("\t\t\t\tshowMonthAfterYear: true //년 뒤에 월 표시\t\t\t\t\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$('#clear').click(function() {\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t$('#SAUP_DAMDANG_ID').val(\"\");\r\n");
      out.write("\t\t\t\t$('#SAUP_DAMDANG_NM').val(\"\");\r\n");
      out.write("\t\t\t\t$('#SAUP_DAMDANG_TEL').val(\"\");\r\n");
      out.write("\t\t\t\t$('#SAUP_DEPT_CD').val(\"\");\r\n");
      out.write("\t\t\t\t$('#SAUP_DEPT_NM').val(\"\");\t\t\t\t\t\t\t\r\n");
      out.write("\t\t    });\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//입력한 문자열 전달\r\n");
      out.write("\t    function inputNumberFormat(obj) {\r\n");
      out.write("\t        obj.value = comma(uncomma(obj.value));\r\n");
      out.write("\t    }\r\n");
      out.write("\t       \r\n");
      out.write("\t    //콤마찍기\r\n");
      out.write("\t    function comma(str) {\r\n");
      out.write("\t        str = String(str);\r\n");
      out.write("\t        return str.replace(/(\\d)(?=(?:\\d{3})+(?!\\d))/g, '$1,');\r\n");
      out.write("\t    }\r\n");
      out.write("\t \r\n");
      out.write("\t    //콤마풀기\r\n");
      out.write("\t    function uncomma(str) {\r\n");
      out.write("\t        str = String(str);\r\n");
      out.write("\t        return str.replace(/[^\\d]+/g, '');\r\n");
      out.write("\t    }\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction fn_jikwonlist(){\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar comAjax = new ComAjax();\r\n");
      out.write("\t\t\tcomAjax.setUrl(\"");
      if (_jspx_meth_c_005furl_005f5(_jspx_page_context))
        return;
      out.write("\");\r\n");
      out.write("\t\t\tcomAjax.setCallback(\"fn_popJikWonListCallback\");\r\n");
      out.write("\t\t\tcomAjax.addParam(\"PAGE_INDEX\",$(\"#PAGE_INDEX\").val());\r\n");
      out.write("\t\t\tcomAjax.addParam(\"PAGE_ROW\", $(\"#RECORD_COUNT\").val());\r\n");
      out.write("\t\t\tcomAjax.addParam(\"USER_NAME\",$(\"#USER_NAME\").val());\r\n");
      out.write("\t\t\tcomAjax.addParam(\"GUBUN\",$(\"#GUBUN\").val());\r\n");
      out.write("\t\t\tcomAjax.ajax();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction fn_popJikWonListCallback(data){\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t//data = $.parseJSON(data);\r\n");
      out.write("\t\t\tvar str = \"\";\r\n");
      out.write("\t\t\tvar i = 1;\t\t\t\r\n");
      out.write("\t\t\tvar body = $(\"#mytable\");\r\n");
      out.write("\t\t\tvar total = data.TOTAL;\r\n");
      out.write("\t\t\tvar recordcnt = $(\"#RECORD_COUNT\").val();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tbody.empty();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar params = {\r\n");
      out.write("\t\t\t\t\tdivId : \"PAGE_NAVI\",\r\n");
      out.write("\t\t\t\t\tpageIndex : \"PAGE_INDEX\",\r\n");
      out.write("\t\t\t\t\ttotalCount : total,\r\n");
      out.write("\t\t\t\t\trecordCount : recordcnt,\r\n");
      out.write("\t\t\t\t\teventName : \"fn_jikwonlist\"\r\n");
      out.write("\t\t\t};\r\n");
      out.write("\t\t\tgfn_renderPaging(params);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$.each(data.list, function(key, value){\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tstr += \"<tr class=\\\"list1\\\" onmouseover=\\\"this.className='list_over'\\\" onmouseout=\\\"this.className='list1'\\\">\" +\r\n");
      out.write("\t\t\t\t\t   \"<td class=\\\"list_center\\\" nowrap>\" + value.RNUM + \"</td>\" +\r\n");
      out.write("\t                   \"<td class=\\\"list_center\\\" nowrap>\" +      \t                 \r\n");
      out.write("\t                   \"<a href='#this' name='title' >\" + NvlStr(value.NDU_USER_NAME)  + \"</a>\" + \t\t\t\t\t\r\n");
      out.write("\t                   \"<input type='hidden' name='JDID' id='JDID' value=\" + NvlStr(value.NDU_DEPT_ID) + \">\" +\r\n");
      out.write("\t\t\t\t\t   \"<input type='hidden' name='JDEPT' id='JDEPT' value=\" + NvlStr(value.NDU_DEPT_NAME) + \">\" +\r\n");
      out.write("\t\t\t\t\t   \"<input type='hidden' name='JID' id='JID' value=\" + NvlStr(value.NDU_USER_ID) + \">\" +\r\n");
      out.write("\t\t\t\t\t   \"<input type='hidden' name='JNAME' id='JNAME' value=\" + NvlStr(value.NDU_USER_NAME) + \">\" +\r\n");
      out.write("\t\t\t\t\t   \"<input type='hidden' name='JTEL' id='JTEL' value=\" + NvlStr(value.NAESUN) + \">\" +\r\n");
      out.write("\t\t\t\t\t   \"</td>\" +\t                   \r\n");
      out.write("\t                   \"<td class=\\\"list_center\\\" nowrap>\" + NvlStr(value.NDU_DEPT_NAME) + \"</td>\" + \r\n");
      out.write("\t                   \"<td class=\\\"list_center\\\" nowrap>\" + NvlStr(value.NDU_CLSS_NM) + \"</td>\" +\t            \t                   \r\n");
      out.write("\t                   \"<td class=\\\"list_center\\\" nowrap>\" + \r\n");
      out.write("\t                   \"<a href='#this' name='title2' >\" + NvlStr(value.NDU_POSIT_NM) + \"</a>\" + \r\n");
      out.write("\t                   \"<input type='hidden' name='JNAME' id='JNAME' value=\" + NvlStr(value.NDU_USER_NAME) + \">\" +\r\n");
      out.write("\t\t\t\t\t   \"<input type='hidden' name='JTEL' id='JTEL' value=\" + NvlStr(value.NAESUN) + \">\" +\r\n");
      out.write("\t\t\t\t\t   \"<input type='hidden' name='JPOS' id='JPOS' value=\" + NvlStr(value.NDU_POSIT_NM) + \">\" +\r\n");
      out.write("\t                   \"</td>\" +\r\n");
      out.write("\t                   \"<td class=\\\"list_center\\\">\" + NvlStr(value.NAESUN) + \"</td>\" +\r\n");
      out.write("\t\t\t\t\t   \"</tr>\" +\r\n");
      out.write("\t\t\t\t\t   \"<tr>\" + \r\n");
      out.write("\t\t\t\t       \"<td colspan=\\\"6\\\" class=\\\"list_line\\\"></td>\" + \r\n");
      out.write("\t\t\t\t\t   \"</tr>\";\r\n");
      out.write("\t\t\t\t\ti++;\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tbody.append(str);\r\n");
      out.write("\t\t\t//alert(str);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$(\"a[name='title']\").on(\"click\", function(e){ //제목 \r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\te.preventDefault();\t\t\t\r\n");
      out.write("\t\t\t\tfn_set_user_info($(this));\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$(\"a[name='title2']\").on(\"click\", function(e){ //직급 \r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\te.preventDefault();\t\t\t\r\n");
      out.write("\t\t\t\tfn_set_user_info2($(this));\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction fn_set_user_info(obj){\r\n");
      out.write("\t\t\tvar tmp1 = \"\";\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\ttmp1 = obj.parent().find(\"#JID\").val();\t\t\t\r\n");
      out.write("\t\t\t$(\"#SAUP_DAMDANG_ID\").val(tmp1);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\ttmp1 = \"\";\r\n");
      out.write("\t\t\ttmp1 = obj.parent().find(\"#JNAME\").val();\r\n");
      out.write("\t\t\t$(\"#SAUP_DAMDANG_NM\").val(tmp1);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\ttmp1 = \"\";\r\n");
      out.write("\t\t\ttmp1 = obj.parent().find(\"#JTEL\").val();\t\t\t\r\n");
      out.write("\t\t\t$(\"#SAUP_DAMDANG_TEL\").val(tmp1);\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\ttmp1 = \"\";\r\n");
      out.write("\t\t\ttmp1 = obj.parent().find(\"#JDID\").val();\t\t\t\r\n");
      out.write("\t\t\t$(\"#SAUP_DEPT_CD\").val(tmp1);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\ttmp1 = \"\";\r\n");
      out.write("\t\t\ttmp1 = obj.parent().find(\"#JDEPT\").val();\t\t\t\r\n");
      out.write("\t\t\t$(\"#SAUP_DEPT_NM\").val(tmp1);\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t$('#pop').hide();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction fn_set_user_info2(obj){\r\n");
      out.write("\t\t\tvar tmp1 = \"\";\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\ttmp1 = obj.parent().find(\"#JPOS\").val();\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif(tmp1 == '팀장')\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\ttmp1 = \"\";\r\n");
      out.write("\t\t\t\ttmp1 = obj.parent().find(\"#JNAME\").val();\t\t\t\r\n");
      out.write("\t\t\t\t$(\"#SAUP_DEPT_TEAMJANG\").val(tmp1);\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\ttmp1 = \"\";\r\n");
      out.write("\t\t\t\ttmp1 = obj.parent().find(\"#JTEL\").val();\r\n");
      out.write("\t\t\t\t$(\"#SAUP_TEAMJANG_TEL\").val(tmp1);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\telse{\r\n");
      out.write("\t\t\t\ttmp1 = \"\";\r\n");
      out.write("\t\t\t\ttmp1 = obj.parent().find(\"#JNAME\").val();\t\t\t\r\n");
      out.write("\t\t\t\t$(\"#SAUP_DEPT_GWAJANG\").val(tmp1);\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\ttmp1 = \"\";\r\n");
      out.write("\t\t\t\ttmp1 = obj.parent().find(\"#JTEL\").val();\r\n");
      out.write("\t\t\t\t$(\"#SAUP_GWAJANG_TEL\").val(tmp1);\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$('#pop').hide();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction fn_mSaupList(pageNo){\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar comAjax = new ComAjax();\r\n");
      out.write("\t\t\tcomAjax.setUrl(\"");
      if (_jspx_meth_c_005furl_005f6(_jspx_page_context))
        return;
      out.write("\");\r\n");
      out.write("\t\t\tcomAjax.setCallback(\"fn_mSaupListCallback\");\r\n");
      out.write("\t\t\tcomAjax.addParam(\"PAGE_INDEX\",$(\"#PAGE_INDEX2\").val());\r\n");
      out.write("\t\t\tcomAjax.addParam(\"PAGE_ROW\", $(\"#RECORD_COUNT2\").val());\r\n");
      out.write("\t\t\tcomAjax.ajax();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction fn_mSaupListCallback(data){\r\n");
      out.write("\t\t\t//data = $.parseJSON(data);\r\n");
      out.write("\t\t\tvar str = \"\";\r\n");
      out.write("\t\t\tvar i = 1;\t\t\t\r\n");
      out.write("\t\t\tvar body = $(\"#mytable2\");\r\n");
      out.write("\t\t\tvar total = data.TOTAL;\r\n");
      out.write("\t\t\tvar recordcnt = $(\"#RECORD_COUNT2\").val();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tbody.empty();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar params = {\r\n");
      out.write("\t\t\t\t\tdivId : \"PAGE_NAVI2\",\r\n");
      out.write("\t\t\t\t\tpageIndex : \"PAGE_INDEX2\",\r\n");
      out.write("\t\t\t\t\ttotalCount : total,\r\n");
      out.write("\t\t\t\t\trecordCount : recordcnt,\r\n");
      out.write("\t\t\t\t\teventName : \"fn_mSaupList\"\r\n");
      out.write("\t\t\t};\r\n");
      out.write("\t\t\tgfn_renderPaging(params);\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t$.each(data.list, function(key, value){\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tstr += \"<tr class=\\\"list1\\\" onmouseover=\\\"this.className='list_over'\\\" onmouseout=\\\"this.className='list1'\\\">\" +\r\n");
      out.write("\t\t\t\t\t   \"<td class=\\\"list_center\\\" nowrap>\" + value.ID + \"</td>\" +\r\n");
      out.write("\t\t\t\t\t   \"<td class=\\\"list\\\"'>\" + NvlStr(value.DEPT_NM) + \"</td>\" +\r\n");
      out.write("\t                   \"<td class=\\\"list_center\\\" nowrap>\" +      \t                 \r\n");
      out.write("\t                   \"<a href=\\\"#this\\\" name=\\\"title\\\" >\" + NvlStr(value.SAUP_NM)  + \"</a>\" + \t\t\t\t\t\r\n");
      out.write("\t                   \"<input type=\\\"hidden\\\" name=\\\"JID\\\" id=\\\"JID\\\" value=\" + NvlStr(value.ID) + \">\" +\t\r\n");
      out.write("\t                   \"<input type=\\\"hidden\\\" name=\\\"JSNM\\\" id=\\\"JSNM\\\" value=\\\"\" + NvlStr(value.SAUP_NM) + \"\\\">\" +\r\n");
      out.write("\t                   \"<input type=\\\"hidden\\\" name=\\\"JDEPT\\\" id=\\\"JDEPT\\\" value=\\\"\" + NvlStr(value.DEPT_NM) + \"\\\">\" +\r\n");
      out.write("\t\t\t\t\t   \"</td>\" +\t                   \r\n");
      out.write("\t\t\t\t\t   \"</tr>\" +\r\n");
      out.write("\t\t\t\t\t   \"<tr>\" + \r\n");
      out.write("\t\t\t\t       \"<td colspan=\\\"3\\\" class=\\\"list_line\\\"></td>\" + \r\n");
      out.write("\t\t\t\t\t   \"</tr>\";\r\n");
      out.write("\t\t\t\t\ti++;\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tbody.append(str);\r\n");
      out.write("\t\t\t//alert(str);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$(\"a[name='title']\").on(\"click\", function(e){ //제목 \r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\te.preventDefault();\t\t\t\r\n");
      out.write("\t\t\t\tfn_saup_info($(this));\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction fn_saup_info(obj, i){\r\n");
      out.write("\t\t\tvar tmp1 = \"\";\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\ttmp1 = obj.parent().find(\"#JID\").val();\t\t\t\r\n");
      out.write("\t\t\t$(\"#SID\").val(tmp1);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\ttmp1 = \"\";\r\n");
      out.write("\t\t\ttmp1 = obj.parent().find(\"#JSNM\").val();\r\n");
      out.write("\t\t\t$(\"#SAUP_NM\").val(tmp1);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\ttmp1 = \"\";\r\n");
      out.write("\t\t\ttmp1 = obj.parent().find(\"#JDEPT\").val();\r\n");
      out.write("\t\t\t$(\"#USER_NAME\").val(tmp1);\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t$('#pop2').hide();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction fn_mainSaupList(){\r\n");
      out.write("\t\t\tvar comSubmit = new ComSubmit();\r\n");
      out.write("\t\t\tcomSubmit.setUrl(\"");
      if (_jspx_meth_c_005furl_005f7(_jspx_page_context))
        return;
      out.write("\");\r\n");
      out.write("\t\t\tcomSubmit.submit();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction fn_updateMainSaupData(){\r\n");
      out.write("\t\t\tvar comSubmit = new ComSubmit(\"form1\");\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif($('#SAUP_BUDGET_AMT').val() == \"\")\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\talert('예산금액을 입력하세요.');\r\n");
      out.write("\t\t\t\t$('#SAUP_BUDGET_AMT').focus();\r\n");
      out.write("\t\t\t\treturn false();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif($('#SAUP_OPEN_DATE').val().replace(/-/gi, \"\").length < 8)\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\talert('목표시기를 8자리로 입력하세요.');\r\n");
      out.write("\t\t\t\t$('#SAUP_OPEN_DATE').focus();\r\n");
      out.write("\t\t\t\treturn false();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif($('#SAUP_DEPT_NM').val() == \"\")\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\talert('담당부서를 입력하세요.');\r\n");
      out.write("\t\t\t\t$('#SAUP_DEPT_NM').focus();\r\n");
      out.write("\t\t\t\treturn false();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif($('#SAUP_DAMDANG_NM').val() == \"\")\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\talert('담당자를 입력하세요.');\r\n");
      out.write("\t\t\t\t$('#SAUP_DAMDANG_NM').focus();\r\n");
      out.write("\t\t\t\treturn false();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif($('#SAUP_DEPT_TEAMJANG').val() == \"\")\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\talert('팀장을 입력하세요.');\r\n");
      out.write("\t\t\t\t$('#SAUP_DEPT_TEAMJANG').focus();\r\n");
      out.write("\t\t\t\treturn false();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif($('#SAUP_DEPT_GWAJANG').val() == \"\")\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\talert('과장을 입력하세요.');\r\n");
      out.write("\t\t\t\t$('#SAUP_DEPT_GWAJANG').focus();\r\n");
      out.write("\t\t\t\treturn false();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif($('#YEAR').val() == 2019)\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\talert('2019년도는 더이상 입력/수정 되지 않습니다.\\n 2020 년도로 입력/수정 하시길 바랍니다.');\r\n");
      out.write("\t\t\t\treturn false();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif(confirm('데이터를 수정하시겠습니까?'))\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\tcomSubmit.setUrl(\"");
      if (_jspx_meth_c_005furl_005f8(_jspx_page_context))
        return;
      out.write("\");\r\n");
      out.write("\t\t\t\tcomSubmit.submit();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction fn_deleteMainSaupData(){\r\n");
      out.write("\t\t\tvar comSubmit = new ComSubmit(\"form1\");\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif($('#YEAR').val() == 2019)\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\talert('2019년도는 더이상 입력/수정 되지 않습니다.\\n 2020 년도로 입력/수정 하시길 바랍니다.');\r\n");
      out.write("\t\t\t\treturn false();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif(confirm('데이터를 삭제하시겠습니까?'))\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\tcomSubmit.setUrl(\"");
      if (_jspx_meth_c_005furl_005f9(_jspx_page_context))
        return;
      out.write("\");\r\n");
      out.write("\t\t\t\tcomSubmit.submit();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t</script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("<form id=\"form1\" name=\"form1\" enctype=\"multipart/form-data\">\r\n");
      out.write("<input type=\"hidden\" id=\"MOD_ID\" name=\"MOD_ID\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.userinfo.userId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("<input type=\"hidden\" id=\"MOD_DEPT\" name=\"MOD_DEPT\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.userinfo.deptId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("<input type=\"hidden\" id=\"USER_RIGHT\" name=\"USER_RIGHT\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.userinfo.userright}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("<input type=\"hidden\" id=\"WRITE_DEPT\" name=\"WRITE_DEPT\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${map.INS_DEPT}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("<input type=\"hidden\" id=\"LOGIN_DEPT\" name=\"LOGIN_DEPT\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.userinfo.deptId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("<input type=\"hidden\" id=\"SAUP_FIELD1_GB\" name=\"SAUP_FIELD1_GB\" value=\"\">\r\n");
      out.write("<input type=\"hidden\" id=\"SAUP_START_DATE\" name=\"SAUP_START_DATE\" value=\"\">\r\n");
      out.write("<input type=\"hidden\" id=\"SAUP_END_DATE\" name=\"SAUP_END_DATE\" value=\"\">\r\n");
      out.write("<input type=\"hidden\" id=\"SAUP_NM\" name=\"SAUP_NM\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.SAUP_NM}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("<input type=\"hidden\" id=\"SAUP_DEPT_CD\" name=\"SAUP_DEPT_CD\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${map.SAUP_DEPT_CD}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("<input type=\"hidden\" id=\"SAUP_DAMDANG_ID\" name=\"SAUP_DAMDANG_ID\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${map.SAUP_DAMDANG_ID}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("<input type=\"hidden\" id=\"SID\" name=\"SID\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${map.ID}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("<input type=\"hidden\" id=\"YEAR\" name=\"YEAR\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.year}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\r\n");
      out.write("<table  border=\"0\" cellspacing=\"0\" cellpadding=\"0\" class=\"bodyframe_full\">\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td class=\"bodyframe\">\r\n");
      out.write("    <!--페이지 타이틀 시작 -->\r\n");
      out.write("    <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("      <tr>\r\n");
      out.write("        <td class=\"pupup_title\"><img src=\"/bims/images/popup_title.gif\" align=\"absmiddle\">주요사업 데이터 등록</td>\r\n");
      out.write("      </tr>\r\n");
      out.write("      <tr>\r\n");
      out.write("        <td class=\"margin_title\"></td>\r\n");
      out.write("      </tr>\r\n");
      out.write("    </table>\r\n");
      out.write("    <!--페이지 타이틀 끝 -->\r\n");
      out.write("    \r\n");
      out.write("     <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("\t <tr>\r\n");
      out.write("\t\t<td width=\"100%\">\r\n");
      out.write("\t\t<table border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"title\"><img src=\"/bims/images/title_ico.gif\" align=\"absmiddle\">기본정보수정</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\t</td>\t\t\t\t\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("\t\r\n");
      out.write("    </td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  \r\n");
      out.write("  <tr>\r\n");
      out.write("    <td class=\"pupup_frame\" style=\"padding-right:12px\">\r\n");
      out.write("\r\n");
      out.write("    <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("      <tr>\r\n");
      out.write("        <td height=\"15\">\r\n");
      out.write("                \r\n");
      out.write("        <!--리스트 시작 -->\r\n");
      out.write("\t      <table width=\"100%\" border=\"0\" cellspacing=\"1\" cellpadding=\"0\" class=\"tbl\" id=\"divMemoMainBody\" style=\"display:block;\">\r\n");
      out.write("\t          <tr>\r\n");
      out.write("\t            <td width=\"120\" class=\"tbl_field\">사업명</td>\r\n");
      out.write("\t            <td width=\"612\" colspan=\"3\" class=\"tbl_list_left\">\r\n");
      out.write("\t            ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${map.SAUP_NM}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\t                \r\n");
      out.write("\t            </td>\r\n");
      out.write("\t          </tr>\r\n");
      out.write("\t          <tr>\r\n");
      out.write("\t            <td width=\"120\" class=\"tbl_field\">사업설명(요약)</td>\r\n");
      out.write("\t            <td width=\"612\" colspan=\"3\" class=\"tbl_list_left\">\r\n");
      out.write("\t                <textarea id=\"SAUP_DETAIL\" name=\"SAUP_DETAIL\" class=\"input\" rows=\"10\" cols=\"150\" style=\"width:800px; height:50px;\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${map.SAUP_DETAIL}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</textarea>\t                \r\n");
      out.write("\t            </td>\r\n");
      out.write("\t          </tr>\r\n");
      out.write("\t          <tr>\r\n");
      out.write("\t            <td width=\"120\" class=\"tbl_field\">예산금액</td>\r\n");
      out.write("\t            <td width=\"612\" colspan=\"3\" class=\"tbl_list_left\">\r\n");
      out.write("\t                <input type=\"text\" id=\"SAUP_BUDGET_AMT\" name=\"SAUP_BUDGET_AMT\" value=\"");
      if (_jspx_meth_fmt_005fformatNumber_005f0(_jspx_page_context))
        return;
      out.write("\" class=\"input\" style=\"width:400;\">\t                \r\n");
      out.write("\t            </td>\r\n");
      out.write("\t          </tr>\t          \r\n");
      out.write("\t          <tr>\r\n");
      out.write("\t            <td width=\"120\" class=\"tbl_field\">목표시기</td>\r\n");
      out.write("\t            <td width=\"612\" colspan=\"3\" class=\"tbl_list_left\">\t                \r\n");
      out.write("\t                <input type=\"text\" id=\"SAUP_OPEN_DATE\" name=\"SAUP_OPEN_DATE\" value=\"");
      if (_jspx_meth_fmt_005fparseDate_005f0(_jspx_page_context))
        return;
      if (_jspx_meth_fmt_005fformatDate_005f0(_jspx_page_context))
        return;
      out.write("\" class=\"input\" style=\"width:174;\">\t                \r\n");
      out.write("\t            </td>\r\n");
      out.write("\t          </tr>\r\n");
      out.write("\t          <tr>\r\n");
      out.write("\t            <td width=\"120\" class=\"tbl_field\">담당부서</td>\r\n");
      out.write("\t            <td width=\"612\" colspan=\"3\" class=\"tbl_list_left\"><input type=\"text\" id=\"SAUP_DEPT_NM\" name=\"SAUP_DEPT_NM\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${map.SAUP_DEPT_NM}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" class=\"input\" style=\"width:174;\" readonly></td>\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t          </tr>\t   \t          \r\n");
      out.write("\t          <tr>\r\n");
      out.write("\t            <td width=\"120\" class=\"tbl_field\">담당자</td>\r\n");
      out.write("\t            <td width=\"246\" class=\"tbl_list_left\"><input type=\"text\" id=\"SAUP_DAMDANG_NM\" name=\"SAUP_DAMDANG_NM\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${map.SAUP_DAMDANG_NM}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" class=\"input\" style=\"width:174;\" readonly>\t            \r\n");
      out.write("\t            <select id=\"GUBUN\" name=\"GUBUN\" class=\"input\">\r\n");
      out.write("\t            <option value=\"2\">부서명</option>\r\n");
      out.write("\t            <option value=\"1\">직원명</option>\r\n");
      out.write("\t            </select> <input type=\"text\" id=\"USER_NAME\" name=\"USER_NAME\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${map.SAUP_DEPT_NM}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" class=\"input\" style=\"width:80;\"> <a href=\"#this\" id=\"open\" class=\"bk\">찾기</a> <a href=\"#this\" id=\"clear\" class=\"bk\">지우기</a>\r\n");
      out.write("\t            </td>\r\n");
      out.write("\t            <td width=\"120\" class=\"tbl_field\">전화번호</td>\r\n");
      out.write("\t            <td width=\"246\" class=\"tbl_list_left\">\r\n");
      out.write("\t                <input type=\"text\" id=\"SAUP_DAMDANG_TEL\" name=\"SAUP_DAMDANG_TEL\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${map.SAUP_DAMDANG_TEL}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" class=\"input\" style=\"width:100;\">\t                \r\n");
      out.write("\t            </td>\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t          </tr>\t                \t      \t       \r\n");
      out.write("\t          <tr>\r\n");
      out.write("\t            <td width=\"120\" class=\"tbl_field\">담당팀장</td>\r\n");
      out.write("\t            <td width=\"246\" class=\"tbl_list_left\">\r\n");
      out.write("\t                <input type=\"text\" id=\"SAUP_DEPT_TEAMJANG\" name=\"SAUP_DEPT_TEAMJANG\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${map.SAUP_DEPT_TEAMJANG}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" class=\"input\" style=\"width:174;\">\t                \r\n");
      out.write("\t            </td>\r\n");
      out.write("\t            <td width=\"120\" class=\"tbl_field\">전화번호</td>\r\n");
      out.write("\t            <td width=\"246\" class=\"tbl_list_left\">\r\n");
      out.write("\t                <input type=\"text\" id=\"SAUP_TEAMJANG_TEL\" name=\"SAUP_TEAMJANG_TEL\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${map.SAUP_TEAMJANG_TEL}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" class=\"input\" style=\"width:100;\">\t                \r\n");
      out.write("\t            </td>\r\n");
      out.write("\t          </tr>\r\n");
      out.write("\t          <tr>\r\n");
      out.write("\t            <td width=\"120\" class=\"tbl_field\">담당과장</td>\r\n");
      out.write("\t            <td width=\"246\" class=\"tbl_list_left\">\r\n");
      out.write("\t                <input type=\"text\" id=\"SAUP_DEPT_GWAJANG\" name=\"SAUP_DEPT_GWAJANG\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${map.SAUP_DEPT_GWAJANG}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" class=\"input\" style=\"width:174;\">\t                \r\n");
      out.write("\t            </td>\r\n");
      out.write("\t            <td width=\"120\" class=\"tbl_field\">전화번호</td>\r\n");
      out.write("\t            <td width=\"246\" class=\"tbl_list_left\">\r\n");
      out.write("\t                <input type=\"text\" id=\"SAUP_GWAJANG_TEL\" name=\"SAUP_GWAJANG_TEL\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${map.SAUP_GWAJANG_TEL}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" class=\"input\" style=\"width:100;\">\t                \r\n");
      out.write("\t            </td>\r\n");
      out.write("\t          </tr>\t          \t\t  \t \r\n");
      out.write("\t      </table>\r\n");
      out.write("\t      \r\n");
      out.write("        <!-- -------------- 버튼 시작 --------------  -->\r\n");
      out.write("        <table width=\"100%\" height=\"40\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("          <tr>\r\n");
      out.write("            <td></td>\r\n");
      out.write("            <td align=\"right\">\r\n");
      out.write("            <table border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("              <tr>\r\n");
      out.write("                <td>\r\n");
      out.write("                <table border=\"0\" cellspacing=\"0\" cellpadding=\"0\" class=\"btn\" id=\"tblAddMemo21\" style=\"filter:none;\">\r\n");
      out.write("                  <tr>\r\n");
      out.write("                    <td><img src=\"/bims/images/btn_type0_head.gif\"></td>\r\n");
      out.write("                    <td background=\"/bims/images/btn_type0_bg.gif\" class=\"btn_type1\" nowrap><a href=\"#this\" class=\"btn\" id=\"update\"><font color=\"white\">수정</font></a></td>\r\n");
      out.write("                    <td><img src=\"/bims/images/btn_type0_end.gif\"></td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                </table>                \r\n");
      out.write("                </td>\r\n");
      out.write("                <td>\r\n");
      out.write("                <table border=\"0\" cellspacing=\"0\" cellpadding=\"0\" class=\"btn\" id=\"tblAddMemo21\" style=\"filter:none;\">\r\n");
      out.write("                  <tr>\r\n");
      out.write("                    <td><img src=\"/bims/images/btn_type0_head.gif\"></td>\r\n");
      out.write("                    <td background=\"/bims/images/btn_type0_bg.gif\" class=\"btn_type1\" nowrap><a href=\"#this\" class=\"btn\" id=\"del\"><font color=\"white\">삭제</font></a></td>\r\n");
      out.write("                    <td><img src=\"/bims/images/btn_type0_end.gif\"></td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                </table>                \r\n");
      out.write("                </td>\t\t\t\t               \r\n");
      out.write("                <td>\r\n");
      out.write("                <table border=\"0\" cellspacing=\"0\" cellpadding=\"0\" class=\"btn\" id=\"tblAddMemoTempSave21\" style=\"filter:none;\">\r\n");
      out.write("                  <tr>\r\n");
      out.write("                    <td><img src=\"/bims/images/btn_type1_head.gif\"></td>\r\n");
      out.write("                    <td background=\"/bims/images/btn_type1_bg.gif\" class=\"btn_type1\" nowrap><a href=\"#this\" class=\"btn\" id=\"list\">목록</a></td>\r\n");
      out.write("                    <td><img src=\"/bims/images/btn_type1_end.gif\"></td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                </table>   \r\n");
      out.write("                </td>                               \r\n");
      out.write("              </tr>\r\n");
      out.write("            </table>\r\n");
      out.write("            </td>\r\n");
      out.write("          </tr>\r\n");
      out.write("          <tr>\r\n");
      out.write("            <td class=\"margin_btn\" colspan=\"2\"></td>\r\n");
      out.write("          </tr>\r\n");
      out.write("        </table>\r\n");
      out.write("        <!-- -------------- 버튼 끝 --------------  -->\r\n");
      out.write("        </td>\r\n");
      out.write("      </tr>\r\n");
      out.write("    </table>\r\n");
      out.write("    \r\n");
      out.write("    </td>\r\n");
      out.write("    \r\n");
      out.write("  </tr>\r\n");
      out.write("</table>\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("<form id=\"commonForm\" name=\"commonForm\"></form>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- POPUP --> \r\n");
      out.write("<div id=\"pop\" style=\"position:absolute;left:395px;top:90;z-index:200;display:none;\"> \r\n");
      out.write("<table width=560 height=250 cellpadding=2 cellspacing=0>\r\n");
      out.write("<tr>        \r\n");
      out.write("    <td align=right bgcolor=white>      \r\n");
      out.write("        <a href=\"#\" id=\"close1\"><B>[닫기]</B></a> \r\n");
      out.write("    </td> \r\n");
      out.write("</tr>\r\n");
      out.write("<tr> \r\n");
      out.write("    <td style=\"border:1px #666666 solid\" height=230 align=center bgcolor=white> \r\n");
      out.write("     <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" style=\"TABLE-layout: fixed\">\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"list_tit_line_s\" width=\"40\"></td>\r\n");
      out.write("\t\t\t\t<td class=\"list_tit_line_s\" width=\"80\"></td>\r\n");
      out.write("\t\t\t\t<td class=\"list_tit_line_s\" width=\"80\"></td>\r\n");
      out.write("\t\t\t\t<td class=\"list_tit_line_s\" width=\"100%\"></td>\r\n");
      out.write("\t\t\t\t<td class=\"list_tit_line_s\" width=\"60\"></td>\r\n");
      out.write("\t\t\t\t<td class=\"list_tit_line_s\" width=\"100\"></td>\t\t\t\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr class=\"list_tit_tr\">\r\n");
      out.write("\t\t\t\t<td nowrap class=\"list_tit\"></td>\r\n");
      out.write("\t\t\t\t<td nowrap class=\"list_tit_bar\">이름</td>\r\n");
      out.write("\t\t\t\t<td nowrap class=\"list_tit_bar\">부서</td>\r\n");
      out.write("\t\t\t\t<td nowrap class=\"list_tit_bar\">직급</td>\r\n");
      out.write("\t\t\t\t<td nowrap class=\"list_tit_bar\">직위</td>\r\n");
      out.write("\t\t\t\t<td nowrap class=\"list_tit_bar\">내선</td>\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td colspan=\"6\" class=\"list_tit_line_e\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tbody id='mytable'>\t\t\t\r\n");
      out.write("\t\t\t</tbody>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td colspan=\"6\" height=\"20\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td colspan=\"6\">\r\n");
      out.write("\t\t\t\t<div id=\"PAGE_NAVI\" align='center'></div>\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" id=\"PAGE_INDEX\" name=\"PAGE_INDEX\"/>\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" id=\"RECORD_COUNT\" name=\"RECORD_COUNT\" value=\"20\"/>\r\n");
      out.write("\t\t\t\t");
      out.write("\r\n");
      out.write("<form id=\"commonForm\" name=\"commonForm\"></form>");
      out.write("\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("    </td> \r\n");
      out.write("</tr> \r\n");
      out.write("<tr>        \r\n");
      out.write("    <td align=right bgcolor=white>      \r\n");
      out.write("        <a href=\"#\" id=\"close2\"><B>[닫기]</B></a> \r\n");
      out.write("    </td> \r\n");
      out.write("</tr> \r\n");
      out.write("      \r\n");
      out.write("</table> \r\n");
      out.write("</div>  \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- POPUP2 --> \r\n");
      out.write("<div id=\"pop2\" style=\"position:absolute;left:395px;top:50;z-index:200;display:none;\"> \r\n");
      out.write("<table width=500 height=250 cellpadding=2 cellspacing=0>\r\n");
      out.write("<tr>        \r\n");
      out.write("    <td align=right bgcolor=white>      \r\n");
      out.write("        <a href=\"#\" id=\"close3\"><B>[닫기]</B></a> \r\n");
      out.write("    </td> \r\n");
      out.write("</tr>\r\n");
      out.write("<tr> \r\n");
      out.write("    <td style=\"border:1px #666666 solid\" height=230 align=center bgcolor=white> \r\n");
      out.write("     <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" style=\"TABLE-layout: fixed\">\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"list_tit_line_s\" width=\"40\"></td>\r\n");
      out.write("\t\t\t\t<td class=\"list_tit_line_s\" width=\"80\"></td>\t\t\t\t\r\n");
      out.write("\t\t\t\t<td class=\"list_tit_line_s\" width=\"100%\"></td>\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr class=\"list_tit_tr\">\r\n");
      out.write("\t\t\t\t<td nowrap class=\"list_tit\"></td>\r\n");
      out.write("\t\t\t\t<td nowrap class=\"list_tit_bar\">추진부서</td>\r\n");
      out.write("\t\t\t\t<td nowrap class=\"list_tit_bar\">사업명</td>\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td colspan=\"3\" class=\"list_tit_line_e\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tbody id='mytable2'>\t\t\t\r\n");
      out.write("\t\t\t</tbody>\t\t\t\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td colspan=\"3\" height=\"20\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td colspan=\"3\">\r\n");
      out.write("\t\t\t\t<div id=\"PAGE_NAVI2\" align='center'></div>\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" id=\"PAGE_INDEX2\" name=\"PAGE_INDEX2\"/>\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" id=\"RECORD_COUNT2\" name=\"RECORD_COUNT2\" value=\"20\"/>\r\n");
      out.write("\t\t\t\t");
      out.write("\r\n");
      out.write("<form id=\"commonForm\" name=\"commonForm\"></form>");
      out.write("\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\t\t\t\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("    </td> \r\n");
      out.write("</tr> \r\n");
      out.write("<tr>        \r\n");
      out.write("    <td align=right bgcolor=white>      \r\n");
      out.write("        <a href=\"#\" id=\"close4\"><B>[닫기]</B></a> \r\n");
      out.write("    </td> \r\n");
      out.write("</tr> \r\n");
      out.write("      \r\n");
      out.write("</table> \r\n");
      out.write("</div>  \r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f0.setParent(null);
    // /WEB-INF/include/include-header.jspf(13,36) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f0.setValue("/js/jquery.min.js");
    int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
    if (_jspx_th_c_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f1 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f1.setParent(null);
    // /WEB-INF/include/include-header.jspf(14,36) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f1.setValue("/js/jquery-ui.js");
    int _jspx_eval_c_005furl_005f1 = _jspx_th_c_005furl_005f1.doStartTag();
    if (_jspx_th_c_005furl_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f1);
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f2 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f2.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f2.setParent(null);
    // /WEB-INF/include/include-header.jspf(15,36) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f2.setValue("/js/jquery.cookie.js");
    int _jspx_eval_c_005furl_005f2 = _jspx_th_c_005furl_005f2.doStartTag();
    if (_jspx_th_c_005furl_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f2);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f2);
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f3 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f3.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f3.setParent(null);
    // /WEB-INF/include/include-header.jspf(16,36) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f3.setValue("/js/jquery.form.js");
    int _jspx_eval_c_005furl_005f3 = _jspx_th_c_005furl_005f3.doStartTag();
    if (_jspx_th_c_005furl_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f3);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f3);
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f4 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f4.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f4.setParent(null);
    // /WEB-INF/include/include-header.jspf(17,13) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f4.setValue("/js/common.js");
    int _jspx_eval_c_005furl_005f4 = _jspx_th_c_005furl_005f4.doStartTag();
    if (_jspx_th_c_005furl_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f4);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f4);
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f5(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f5 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f5.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f5.setParent(null);
    // /WEB-INF/jsp/daejang/mainSaupUpdate.jsp(143,19) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f5.setValue("/common/popJikWonList.do");
    int _jspx_eval_c_005furl_005f5 = _jspx_th_c_005furl_005f5.doStartTag();
    if (_jspx_th_c_005furl_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f5);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f5);
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f6(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f6 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f6.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f6.setParent(null);
    // /WEB-INF/jsp/daejang/mainSaupUpdate.jsp(278,19) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f6.setValue("/daejang/mSaupList.do");
    int _jspx_eval_c_005furl_005f6 = _jspx_th_c_005furl_005f6.doStartTag();
    if (_jspx_th_c_005furl_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f6);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f6);
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f7(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f7 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f7.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f7.setParent(null);
    // /WEB-INF/jsp/daejang/mainSaupUpdate.jsp(359,21) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f7.setValue((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("/daejang/mainSaupList.do?year=${param.year}&sgb=${param.sgb}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
    int _jspx_eval_c_005furl_005f7 = _jspx_th_c_005furl_005f7.doStartTag();
    if (_jspx_th_c_005furl_005f7.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f7);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f7);
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f8(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f8 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f8.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f8.setParent(null);
    // /WEB-INF/jsp/daejang/mainSaupUpdate.jsp(419,22) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f8.setValue("/daejang/updateMainSaup.do");
    int _jspx_eval_c_005furl_005f8 = _jspx_th_c_005furl_005f8.doStartTag();
    if (_jspx_th_c_005furl_005f8.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f8);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f8);
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f9(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f9 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f9.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f9.setParent(null);
    // /WEB-INF/jsp/daejang/mainSaupUpdate.jsp(437,22) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f9.setValue("/daejang/deleteMainSaup.do");
    int _jspx_eval_c_005furl_005f9 = _jspx_th_c_005furl_005f9.doStartTag();
    if (_jspx_th_c_005furl_005f9.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f9);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f9);
    return false;
  }

  private boolean _jspx_meth_fmt_005fformatNumber_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:formatNumber
    org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag _jspx_th_fmt_005fformatNumber_005f0 = (org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag) _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fpattern_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag.class);
    _jspx_th_fmt_005fformatNumber_005f0.setPageContext(_jspx_page_context);
    _jspx_th_fmt_005fformatNumber_005f0.setParent(null);
    // /WEB-INF/jsp/daejang/mainSaupUpdate.jsp(516,87) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_fmt_005fformatNumber_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${map.SAUP_BUDGET_AMT}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
    // /WEB-INF/jsp/daejang/mainSaupUpdate.jsp(516,87) name = pattern type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_fmt_005fformatNumber_005f0.setPattern("###,###,###");
    int _jspx_eval_fmt_005fformatNumber_005f0 = _jspx_th_fmt_005fformatNumber_005f0.doStartTag();
    if (_jspx_th_fmt_005fformatNumber_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fpattern_005fnobody.reuse(_jspx_th_fmt_005fformatNumber_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fpattern_005fnobody.reuse(_jspx_th_fmt_005fformatNumber_005f0);
    return false;
  }

  private boolean _jspx_meth_fmt_005fparseDate_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:parseDate
    org.apache.taglibs.standard.tag.rt.fmt.ParseDateTag _jspx_th_fmt_005fparseDate_005f0 = (org.apache.taglibs.standard.tag.rt.fmt.ParseDateTag) _005fjspx_005ftagPool_005ffmt_005fparseDate_0026_005fvar_005fvalue_005fpattern_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.ParseDateTag.class);
    _jspx_th_fmt_005fparseDate_005f0.setPageContext(_jspx_page_context);
    _jspx_th_fmt_005fparseDate_005f0.setParent(null);
    // /WEB-INF/jsp/daejang/mainSaupUpdate.jsp(522,85) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_fmt_005fparseDate_005f0.setValue((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${map.SAUP_OPEN_DATE}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
    // /WEB-INF/jsp/daejang/mainSaupUpdate.jsp(522,85) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_fmt_005fparseDate_005f0.setVar("dateFmt1");
    // /WEB-INF/jsp/daejang/mainSaupUpdate.jsp(522,85) name = pattern type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_fmt_005fparseDate_005f0.setPattern("yyyyMMdd");
    int _jspx_eval_fmt_005fparseDate_005f0 = _jspx_th_fmt_005fparseDate_005f0.doStartTag();
    if (_jspx_th_fmt_005fparseDate_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005ffmt_005fparseDate_0026_005fvar_005fvalue_005fpattern_005fnobody.reuse(_jspx_th_fmt_005fparseDate_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005ffmt_005fparseDate_0026_005fvar_005fvalue_005fpattern_005fnobody.reuse(_jspx_th_fmt_005fparseDate_005f0);
    return false;
  }

  private boolean _jspx_meth_fmt_005fformatDate_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:formatDate
    org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag _jspx_th_fmt_005fformatDate_005f0 = (org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag) _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag.class);
    _jspx_th_fmt_005fformatDate_005f0.setPageContext(_jspx_page_context);
    _jspx_th_fmt_005fformatDate_005f0.setParent(null);
    // /WEB-INF/jsp/daejang/mainSaupUpdate.jsp(522,165) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_fmt_005fformatDate_005f0.setValue((java.util.Date) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dateFmt1}", java.util.Date.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
    // /WEB-INF/jsp/daejang/mainSaupUpdate.jsp(522,165) name = pattern type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_fmt_005fformatDate_005f0.setPattern("yyyy-MM-dd");
    int _jspx_eval_fmt_005fformatDate_005f0 = _jspx_th_fmt_005fformatDate_005f0.doStartTag();
    if (_jspx_th_fmt_005fformatDate_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.reuse(_jspx_th_fmt_005fformatDate_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.reuse(_jspx_th_fmt_005fformatDate_005f0);
    return false;
  }
}
