/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.24
 * Generated at: 2020-03-04 05:35:24 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.incident;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class incidentStatisticsList2_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(6);
    _jspx_dependants.put("jar:file:/C:/dev/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp4/wtpwebapps/sosong/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/include/include-body.jspf", Long.valueOf(1433227700000L));
    _jspx_dependants.put("jar:file:/C:/dev/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp4/wtpwebapps/sosong/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1459986096000L));
    _jspx_dependants.put("/WEB-INF/include/include-header.jspf", Long.valueOf(1531115670000L));
    _jspx_dependants.put("jar:file:/C:/dev/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp4/wtpwebapps/sosong/WEB-INF/lib/jstl-1.2.jar!/META-INF/fn.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/sosong/css/common.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/sosong/css/skin01.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/sosong/css/import.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/sosong/css/sosong.css\" />\r\n");
      out.write("\r\n");
      out.write("<!-- jQuery -->\r\n");
      out.write("<!--<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"http://code.jquery.com/ui/1.11.2/jquery-ui.js\"></script>\r\n");
      out.write("-->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/sosong/css/jquery-ui.css\" />\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      if (_jspx_meth_c_005furl_005f0(_jspx_page_context))
        return;
      out.write("\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      if (_jspx_meth_c_005furl_005f1(_jspx_page_context))
        return;
      out.write("\"></script>\r\n");
      out.write("<script src=\"/sosong/js/calendar.js\"></script>\r\n");
      out.write("<script src=\"");
      if (_jspx_meth_c_005furl_005f2(_jspx_page_context))
        return;
      out.write("\" charset=\"utf-8\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t\tvar chk_num = 0;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(document).ready(function(){\r\n");
      out.write("\t\t\tfn_incidentStatisticsList2(1);\r\n");
      out.write("\t\t\tfn_initial_setting();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$(\"#list\").on(\"click\", function(e){ //목록으로 버튼\r\n");
      out.write("\t\t\t\te.preventDefault();\r\n");
      out.write("\t\t\t\tfn_incidentStatisticsList2();\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$(\"#inquery\").on(\"click\", function(e){ //기본정보\r\n");
      out.write("\t\t\t\te.preventDefault();\r\n");
      out.write("\t\t\t\tfn_incidentStatisticsList2();\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$(\"input:radio[name=INCDNT_GB]\").click(function(){\t\t\t   \r\n");
      out.write("\t\t\t\t$(\"#PAGE_INDEX\").val(\"1\");\r\n");
      out.write("\t\t\t\tfn_incidentStatisticsList2();\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$(\"#print\").on(\"click\", function(e){ //프린트 버튼\r\n");
      out.write("\t\t\t\te.preventDefault();\r\n");
      out.write("\t\t\t\tfn_print();\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t});\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$(\"#excel\").on(\"click\", function(e){ //엑셀다운 버튼\r\n");
      out.write("\t\t\t\te.preventDefault();\r\n");
      out.write("\t\t\t\tfn_exceldown();\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$(\"#initial\").on(\"click\", function(e){ //초기화 버튼\r\n");
      out.write("\t\t\t\te.preventDefault();\t\t\t\t\r\n");
      out.write("\t\t\t\t$(\"#form1\").each(function() {\t\t\t\t \r\n");
      out.write("\t\t\t       this.reset();  \r\n");
      out.write("\t\t\t    });\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\tfn_initial_setting();\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction fn_initial_setting(){\t\t\t\r\n");
      out.write("\t\t\t$('input:radio[id=INCDNT_GB4]').prop(\"checked\", true);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction fn_print(){     \r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t$('#divMemoMainBody1').css(\"display\",\"none\");\r\n");
      out.write("\t\t\t$('#divMemoMainBody2').css(\"display\",\"none\");\r\n");
      out.write("\t\t\t \r\n");
      out.write("\t\t\tfactory.printing.portrait = false;                    //출력방향 설정: true-세로, false-가로\r\n");
      out.write("\t\t\tfactory.printing.leftMargin = 0.0;                //왼쪽 여백 설정 \r\n");
      out.write("\t\t\tfactory.printing.topMargin = 0.0;              //왼쪽 여백 설정 \r\n");
      out.write("\t\t\tfactory.printing.rightMargin = 0.0;              //왼쪽 여백 설정 \r\n");
      out.write("\t\t\tfactory.printing.bottomMargin = 0.0;            //왼쪽 여백 설정\t\t\t\r\n");
      out.write("\t\t\tfactory.printing.Print(false, window);\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t    function fn_incidentStatisticsList2(pageNo){\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar comAjax = new ComAjax();\r\n");
      out.write("\t\t\tvar user_right =  $(\"#USER_RIGHT\").val();\r\n");
      out.write("\t\t\tvar tmp = \"\";\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tcomAjax.setUrl(\"");
      if (_jspx_meth_c_005furl_005f3(_jspx_page_context))
        return;
      out.write("\");\r\n");
      out.write("\t\t\tcomAjax.setCallback(\"fn_selectIncidentStatisticsList2Callback\");\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif( $(\"input:radio[name='INCDNT_GB']\").is(\":checked\") == true){\t\t\t\t\r\n");
      out.write("\t\t\t\tcomAjax.addParam(\"INCDNT_GB\", $(\"input:radio[name='INCDNT_GB']:checked\").val());\r\n");
      out.write("\t\t\t}\t\r\n");
      out.write("\t\t\tcomAjax.addParam(\"DEPT_NAME\",$(\"#DEPT_NAME\").val());\t\r\n");
      out.write("\t\t\tcomAjax.addParam(\"STDATE\", $(\"#STDATE\").val());\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif($(\"#EDDATE\").val() == \"\" || $(\"#EDDATE\").val() == null)\r\n");
      out.write("\t\t\t\tcomAjax.addParam(\"EDDATE\", $.datepicker.formatDate($.datepicker.ATOM, new Date())); //오늘일자\r\n");
      out.write("\t\t\telse\r\n");
      out.write("\t\t\t\tcomAjax.addParam(\"EDDATE\", $(\"#EDDATE\").val());\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\tvar sel_layer = $(\"#SEL_LAWYER > option\");\r\n");
      out.write("\t\t    var len = sel_layer.length;\r\n");
      out.write("\t\t    var len2 = $(\"#SEL_LAWYER > option:selected\").length;\r\n");
      out.write("\t\t     \r\n");
      out.write("\t        for (var i = 0, j=0; i < len; i++){\r\n");
      out.write("\t            if(sel_layer[i].selected == true){\r\n");
      out.write("\t                tmp += \"'\" + sel_layer[i].value+ \"'\";\r\n");
      out.write("\t              \r\n");
      out.write("\t                if(j != len2-1)\r\n");
      out.write("\t                \ttmp = tmp + \", \";\r\n");
      out.write("\t              j++;\r\n");
      out.write("\t            }\r\n");
      out.write("\t        }\r\n");
      out.write("\t        \r\n");
      out.write("\t\t\tif(tmp.length > 0)\r\n");
      out.write("\t\t\t{\t\t\t\t\r\n");
      out.write("\t\t\t\tcomAjax.addParam(\"CHK_LAWYER\", \"11\");\t\t\t\t\r\n");
      out.write("\t\t\t\tcomAjax.addParam(\"LAWYER_LIST\", tmp);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\telse{\r\n");
      out.write("\t\t\t\tcomAjax.addParam(\"CHK_LAWYER\", \"\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tcomAjax.ajax();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction fn_selectIncidentStatisticsList2Callback(data){\t\t\t\r\n");
      out.write("\t\t\tvar total = data.TOTAL;\r\n");
      out.write("\t\t\tvar body = $(\"#mytable\");\r\n");
      out.write("\t\t\tvar recordcnt = $(\"#RECORD_COUNT\").val();\r\n");
      out.write("\t\t\tvar str = \"\";\r\n");
      out.write("\t\t\tvar str2 = \"\";\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\tbody.empty();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif(total == 0){\r\n");
      out.write("\t\t\t\t\tstr = \"<tr>\" + \r\n");
      out.write("\t\t\t\t\t\t\t\t\"<td colspan=\\\"4\\\">조회된 결과가 없습니다.</td>\" +\r\n");
      out.write("\t\t\t\t\t\t  \"</tr>\";\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\tbody.append(str);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\telse{\r\n");
      out.write("\t\t\t\tvar params = {\r\n");
      out.write("\t\t\t\t\tdivId : \"PAGE_NAVI\",\r\n");
      out.write("\t\t\t\t\tpageIndex : \"PAGE_INDEX\",\r\n");
      out.write("\t\t\t\t\ttotalCount : total,\r\n");
      out.write("\t\t\t\t\trecordCount : recordcnt,\r\n");
      out.write("\t\t\t\t\teventName : \"fn_selectIncidentStatisticsList2Callback\"\r\n");
      out.write("\t\t\t\t};\r\n");
      out.write("\t\t\t\tgfn_renderPaging(params);\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tstr = \"\";\r\n");
      out.write("\t\t\t\tstr2 = \"\";\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t$.each(data.list, function(key, value){\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tstr += \"<tr>\" +\r\n");
      out.write("\t\t\t\t\t   \"<td>\" + NvlStr(value.CHRG_LAWYER) +  \"</td>\" +\r\n");
      out.write("\t\t\t\t\t   \"<td>\" + comma(NvlStr(value.SUMN)) +  \"</td>\" +\r\n");
      out.write("\t\t\t\t\t   \"<td>\" + comma(NvlStr(value.NUM1)) +  \"</td>\" +\r\n");
      out.write("\t\t\t\t\t   \"<td>\" + comma(NvlStr(value.NUM2)) + \"</td>\" +\t\t\t\t\t\t\t\t   \r\n");
      out.write("\t\t\t\t   \"</tr>\";\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tif(NvlStr(value.CHRG_LAWYER) != \"계\" && NvlStr(value.CHRG_LAWYER) != \"기타변호사\"){\r\n");
      out.write("\t\t\t\t\t\tstr2 += \"<option value=\\\"\" + NvlStr(value.CHRG_LAWYER) + \"\\\">\" + NvlStr(value.CHRG_LAWYER) + \"</option>\";\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t   \r\n");
      out.write("\t\t\t\t});\t\t\t\t\r\n");
      out.write("\t\t\t\tbody.append(str);\r\n");
      out.write("\t\t\t\tif(chk_num == 0){\r\n");
      out.write("\t\t\t\t\t$(\"#SEL_LAWYER\").append(str2);\r\n");
      out.write("\t\t\t\t\tchk_num++;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction fn_exceldown(){\t\t\t\r\n");
      out.write("\t\t\tvar comSubmit = new ComSubmit();\t\t\t\r\n");
      out.write("\t\t\tvar tmp = \"\";\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tcomSubmit.setUrl(\"");
      if (_jspx_meth_c_005furl_005f4(_jspx_page_context))
        return;
      out.write("\");\t\t\r\n");
      out.write("\t\t\tcomSubmit.addParam(\"DEPT_NAME\",$(\"#DEPT_NAME\").val());\r\n");
      out.write("\t\t\tcomSubmit.addParam(\"STDATE\", $(\"#STDATE\").val());\r\n");
      out.write("\r\n");
      out.write("\t\t\tif($(\"#EDDATE\").val() == \"\" || $(\"#EDDATE\").val() == null)\r\n");
      out.write("\t\t\t\tcomSubmit.addParam(\"EDDATE\", $.datepicker.formatDate($.datepicker.ATOM, new Date())); //오늘일자\r\n");
      out.write("\t\t\telse\r\n");
      out.write("\t\t\t\tcomSubmit.addParam(\"EDDATE\", $(\"#EDDATE\").val());\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif( $(\"input:radio[name='INCDNT_GB']\").is(\":checked\") == true){\t\t\t\t\r\n");
      out.write("\t\t\t\tcomSubmit.addParam(\"INCDNT_GB\", $(\"input:radio[name='INCDNT_GB']:checked\").val());\t\t\t\r\n");
      out.write("\t\t\t}\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar sel_layer = $(\"#SEL_LAWYER > option\");\r\n");
      out.write("\t\t    var len = sel_layer.length;\r\n");
      out.write("\t\t    var len2 = $(\"#SEL_LAWYER > option:selected\").length;\r\n");
      out.write("\t\t     \r\n");
      out.write("\t        for (var i = 0, j=0; i < len; i++){\r\n");
      out.write("\t            if(sel_layer[i].selected == true){\r\n");
      out.write("\t                tmp += \"'\" + sel_layer[i].value+ \"'\";\r\n");
      out.write("\t              \r\n");
      out.write("\t                if(j != len2-1)\r\n");
      out.write("\t                \ttmp = tmp + \", \";\r\n");
      out.write("\t              j++;\r\n");
      out.write("\t            }\r\n");
      out.write("\t        }\r\n");
      out.write("\t        \r\n");
      out.write("\t\t\tif(tmp.length > 0)\r\n");
      out.write("\t\t\t{\t\t\t\t\r\n");
      out.write("\t\t\t\t//comSubmit.addParam(\"CHK_LAWYER\", \"11\");\t\t\t\t\r\n");
      out.write("\t\t\t\tcomSubmit.addParam(\"LAWYER_LIST\", tmp);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\telse{\r\n");
      out.write("\t\t\t\tcomSubmit.addParam(\"CHK_LAWYER\", \"\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tcomSubmit.submit();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body bgcolor=\"#FFFFFF\">\r\n");
      out.write("<object id=\"factory\" style=\"display:none\" classid=\"clsid:1663ed61-23eb-11d2-b92f-008048fdd814\" codebase=\"http://98.23.7.110:8099/sosong/common/smsx.cab#Version=7,7,0,20\"></object>\r\n");
      out.write("<form id=\"form1\" name=\"form1\">\r\n");
      out.write("<input type=\"hidden\" id=\"USER_ID\" name=\"USER_ID\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.userinfo.userId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("<input type=\"hidden\" id=\"DEPT_ID\" name=\"DEPT_ID\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.userinfo.deptId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("<input type=\"hidden\" id=\"USER_RIGHT\" name=\"USER_RIGHT\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.userinfo.userright}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("<input type=\"hidden\" id=\"BOARD_ID\" name=\"BOARD_ID\" value=\"1\">\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("<table  border=\"0\" cellspacing=\"0\" cellpadding=\"0\" class=\"bodyframe_full\">\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td class=\"bodyframe\">\r\n");
      out.write("    <!--페이지 타이틀 시작 -->\r\n");
      out.write("    <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("      <tr>\r\n");
      out.write("        <td class=\"pupup_title\"><img src=\"/sosong/images/popup_title.gif\" align=\"absmiddle\">변호사 수임료 지급현황</td>\r\n");
      out.write("      </tr>\r\n");
      out.write("      <tr>\r\n");
      out.write("        <td class=\"margin_title\"></td>\r\n");
      out.write("      </tr>\r\n");
      out.write("    </table>\r\n");
      out.write("    <!--페이지 타이틀 끝 -->\r\n");
      out.write("    </td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td class=\"pupup_frame\" style=\"padding-right:12px\">\t\r\n");
      out.write("    \r\n");
      out.write("   \r\n");
      out.write("      <table width=\"720\" border=\"0\" cellspacing=\"1\" cellpadding=\"0\" class=\"tbl\" id=\"divMemoMainBody1\">\r\n");
      out.write("      <tr>\r\n");
      out.write("           <td width=\"100\" class=\"tbl_field\">소송구분</td>\r\n");
      out.write("           <td colspan=\"3\" width=\"660\" class=\"tbl_list_left\">           \t                 \r\n");
      out.write("               <input type=\"radio\" id=\"INCDNT_GB4\" name=\"INCDNT_GB\" value=\"\" class=\"input\" onfocus=\"this.blur()\"> 전체&nbsp;<input type=\"radio\" id=\"INCDNT_GB1\" name=\"INCDNT_GB\" value=\"1\" class=\"input\" onfocus=\"this.blur()\"> 행정소송 &nbsp;<input type=\"radio\" id=\"INCDNT_GB2\" name=\"INCDNT_GB\" value=\"2\" class=\"input\" onfocus=\"this.blur()\"> 민사소송 &nbsp;<input type=\"radio\" id=\"INCDNT_GB3\" name=\"INCDNT_GB\" value=\"3\" class=\"input\" onfocus=\"this.blur()\"> 국가소송                 \t                \t               \r\n");
      out.write("           </td>\r\n");
      out.write("      </tr>\t\t \r\n");
      out.write("      <tr>\r\n");
      out.write("        <td width=\"100\" class=\"tbl_field\">기간</td>\r\n");
      out.write("        <td colspan=\"3\" width=\"660\" class=\"tbl_list_left\">\t               \r\n");
      out.write("            <input type=\"text\" id=\"STDATE\" name=\"STDATE\" class=\"input\" style=\"width:100;\"> <a href=\"#a\" onclick=\"popUpCalendar(this, STDATE, 'yyyy-mm-dd');\"><img class=\"Lbtn\" src=\"/sosong/images/ic_cal.gif\" alt=\"달력\" /></a> ~\r\n");
      out.write("            <input type=\"text\" id=\"EDDATE\" name=\"EDDATE\" class=\"input\" style=\"width:100;\"> <a href=\"#a\" onclick=\"popUpCalendar(this, EDDATE, 'yyyy-mm-dd');\"><img class=\"Lbtn\" src=\"/sosong/images/ic_cal.gif\" alt=\"달력\" /></a>\t                          \r\n");
      out.write("        </td>\r\n");
      out.write("      </tr>\r\n");
      out.write("\t  <tr>\r\n");
      out.write("        <td width=\"100\" class=\"tbl_field\">담당부서</td>\r\n");
      out.write("        <td colspan=\"3\" width=\"660\" class=\"tbl_list_left\">\t               \r\n");
      out.write("            <input type=\"text\" id=\"DEPT_NAME\" name=\"DEPT_NAME\" class=\"input\" style=\"width:300;\">\t                          \r\n");
      out.write("        </td>\r\n");
      out.write("      </tr>\r\n");
      out.write("      <tr>\r\n");
      out.write("        <td width=\"100\" class=\"tbl_field\">조회 변호사</td>\r\n");
      out.write("        <td colspan=\"3\" width=\"660\" class=\"tbl_list_left\">\r\n");
      out.write("\t      <select id=\"SEL_LAWYER\" name=\"SEL_LAWYER\" class=\"input\" size=\"7\" multiple>    \t                \t\t                    \t\t              \r\n");
      out.write("\t\t  </select>\t\t\r\n");
      out.write("\t   </td>\r\n");
      out.write("      </tr>\r\n");
      out.write("      </table>\r\n");
      out.write("    \r\n");
      out.write("\t   <!-- ----------------------------------- 버튼 시작 ------------------------------------------>\r\n");
      out.write("\t   <table width=\"100%\" height=\"40\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" id=\"divMemoMainBody2\">\r\n");
      out.write("\t     <tr>\r\n");
      out.write("\t       <td></td>\r\n");
      out.write("\t       <td align=\"right\">\r\n");
      out.write("\t       <table border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("\t         <tr>\r\n");
      out.write("\t          <td>\r\n");
      out.write("\t           <table border=\"0\" cellspacing=\"0\" cellpadding=\"0\" class=\"btn\" id=\"changebtn2\" style=\"display:block;\">\r\n");
      out.write("\t             <tr>\r\n");
      out.write("\t               <td><img src=\"/sosong/images/btn_type1_head.gif\"></td>\r\n");
      out.write("\t               <td background=\"/sosong/images/btn_type1_bg.gif\" class=\"btn_type1\" nowrap><a href=\"#this\" class=\"btn\" id=\"initial\">검색초기화</a></td>\r\n");
      out.write("\t               <td><img src=\"/sosong/images/btn_type1_end.gif\"></td>\r\n");
      out.write("\t             </tr>\r\n");
      out.write("\t           </table>\r\n");
      out.write("\t           </td>\r\n");
      out.write("\t           <td>\r\n");
      out.write("\t           <table border=\"0\" cellspacing=\"0\" cellpadding=\"0\" class=\"btn\" id=\"tblAddMemo21\" style=\"filter:none;\">\r\n");
      out.write("\t             <tr>\r\n");
      out.write("\t               <td><img src=\"/sosong/images/btn_type0_head.gif\"></td>\r\n");
      out.write("\t               <td background=\"/sosong/images/btn_type0_bg.gif\" class=\"btn_type1\" nowrap><a href=\"#this\" class=\"btn\" id=\"inquery\"><font color=\"white\">조회</font></a></td>\r\n");
      out.write("\t               <td><img src=\"/sosong/images/btn_type0_end.gif\"></td>\r\n");
      out.write("\t             </tr>\r\n");
      out.write("\t           </table>                \r\n");
      out.write("\t           </td>\t\t\r\n");
      out.write("\t         </tr>\r\n");
      out.write("\t       </table>\r\n");
      out.write("\t       </td>\r\n");
      out.write("\t     </tr>\r\n");
      out.write("\t     <tr>\r\n");
      out.write("\t       <td align=\"left\"></td>\r\n");
      out.write("\t       <td align=\"right\">\r\n");
      out.write("\t       <table border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("\t         <tr>\r\n");
      out.write("\t         <!-- \r\n");
      out.write("\t           <td>\r\n");
      out.write("\t           <table border=\"0\" cellspacing=\"0\" cellpadding=\"0\" class=\"btn\" id=\"changebtn2\" style=\"display:block;\">\r\n");
      out.write("\t             <tr>\r\n");
      out.write("\t               <td><img src=\"/sosong/images/btn_type1_head.gif\"></td>\r\n");
      out.write("\t               <td background=\"/sosong/images/btn_type1_bg.gif\" class=\"btn_type1\" nowrap><a href=\"#this\" class=\"btn\" id=\"initial\">검색초기화</a></td>\r\n");
      out.write("\t               <td><img src=\"/sosong/images/btn_type1_end.gif\"></td>\r\n");
      out.write("\t             </tr>\r\n");
      out.write("\t           </table>\r\n");
      out.write("\t           </td>\r\n");
      out.write("\t           -->\t\t\t\t\r\n");
      out.write("\t           <td>\t           \r\n");
      out.write("\t           <table border=\"0\" cellspacing=\"0\" cellpadding=\"0\" class=\"btn\" id=\"changebtn2\" style=\"display:block;\">\r\n");
      out.write("\t             <tr>\r\n");
      out.write("\t               <td><img src=\"/sosong/images/btn_type1_head.gif\"></td>\r\n");
      out.write("\t               <td background=\"/sosong/images/btn_type1_bg.gif\" class=\"btn_type1\" nowrap><a href=\"#this\" class=\"btn\" id=\"print\">프린트</a></td>\r\n");
      out.write("\t               <td><img src=\"/sosong/images/btn_type1_end.gif\"></td>\r\n");
      out.write("\t             </tr>\r\n");
      out.write("\t           </table>\t          \r\n");
      out.write("\t           </td>\t           \t\t\t\t\t\r\n");
      out.write("\t           <td>\r\n");
      out.write("\t           <table border=\"0\" cellspacing=\"0\" cellpadding=\"0\" class=\"btn\" id=\"tblAddMemoTempSave21\" style=\"filter:none;\">\r\n");
      out.write("\t             <tr>\r\n");
      out.write("\t               <td><img src=\"/sosong/images/btn_type1_head.gif\"></td>\r\n");
      out.write("\t               <td background=\"/sosong/images/btn_type1_bg.gif\" class=\"btn_type1\" nowrap><a href=\"#this\" class=\"btn\" id=\"excel\">엑셀다운로드</a></td>\r\n");
      out.write("\t               <td><img src=\"/sosong/images/btn_type1_end.gif\"></td>\r\n");
      out.write("\t             </tr>\r\n");
      out.write("\t           </table>                \r\n");
      out.write("\t           </td>\t                                         \r\n");
      out.write("\t         </tr>\r\n");
      out.write("\t       </table>\r\n");
      out.write("\t       </td>\r\n");
      out.write("\t     </tr>\r\n");
      out.write("\t     <tr>\r\n");
      out.write("\t       <td class=\"margin_btn\" colspan=\"2\"></td>\r\n");
      out.write("\t     </tr>\r\n");
      out.write("\t   </table>\t\r\n");
      out.write("       <!-- ----------------------------------- 버튼 끝 ------------------------------------------>\r\n");
      out.write("    \r\n");
      out.write("\t\t<table class=\"tbl2\">\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t            <th width=\"250\">구분</th>\r\n");
      out.write("\t            <th width=\"200\">계</th>\r\n");
      out.write("\t\t\t\t<th width=\"200\">착수금</th>\r\n");
      out.write("\t\t\t\t<th width=\"200\">승소사례금</th>\t            \t\t\t\t\t\t\r\n");
      out.write("          \t</tr>\r\n");
      out.write("\t\t\t<tbody id='mytable'>\t\t\t\t\r\n");
      out.write("\t\t\t</tbody>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("</table>\r\n");
      out.write("</form>\r\n");
      out.write("\t<div id=\"PAGE_NAVI\" align='center'></div>\r\n");
      out.write("\t<input type=\"hidden\" id=\"PAGE_INDEX\" name=\"PAGE_INDEX\"/>\r\n");
      out.write("\t<input type=\"hidden\" id=\"RECORD_COUNT\" name=\"RECORD_COUNT\" value=\"10\"/>\t\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("<form id=\"commonForm\" name=\"commonForm\"></form>");
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f0.setParent(null);
    // /WEB-INF/include/include-header.jspf(15,36) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f0.setValue("/js/jquery.min.js");
    int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
    if (_jspx_th_c_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f1 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f1.setParent(null);
    // /WEB-INF/include/include-header.jspf(16,36) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f1.setValue("/js/jquery-ui.js");
    int _jspx_eval_c_005furl_005f1 = _jspx_th_c_005furl_005f1.doStartTag();
    if (_jspx_th_c_005furl_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f1);
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f2 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f2.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f2.setParent(null);
    // /WEB-INF/include/include-header.jspf(18,13) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f2.setValue("/js/common.js");
    int _jspx_eval_c_005furl_005f2 = _jspx_th_c_005furl_005f2.doStartTag();
    if (_jspx_th_c_005furl_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f2);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f2);
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f3 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f3.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f3.setParent(null);
    // /WEB-INF/jsp/incident/incidentStatisticsList2.jsp(74,19) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f3.setValue("/incident/selectIncidentStatisticsList2.do");
    int _jspx_eval_c_005furl_005f3 = _jspx_th_c_005furl_005f3.doStartTag();
    if (_jspx_th_c_005furl_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f3);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f3);
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f4 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f4.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f4.setParent(null);
    // /WEB-INF/jsp/incident/incidentStatisticsList2.jsp(169,21) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f4.setValue("/incident/excelIncidentStatistics2.do");
    int _jspx_eval_c_005furl_005f4 = _jspx_th_c_005furl_005f4.doStartTag();
    if (_jspx_th_c_005furl_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f4);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f4);
    return false;
  }
}
